### ISSUE TITLE
Request workspace/executeCommand failed

### ISSUE THREAD

**Issue by biergit** [spring-projects/sts4#1018]
**Describe the bug**
vscode-spring-boot-debug-log complains about `Request workspace/executeCommand failed`

Stacktrace:

```
Error - 09:36:39] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.springframework.ide.vscode.commons.languageserver.util.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:129)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessMemoryMetricsLiveData.getHeapMemoryMetrics()" because "data" is null
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessCommandHandler.handleLiveMetricsProcessRequest(SpringProcessCommandHandler.java:310)
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessCommandHandler.lambda$new$5(SpringProcessCommandHandler.java:83)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleLanguageServer.executeCommand(SimpleLanguageServer.java:273)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleWorkspaceService.executeCommand(SimpleWorkspaceService.java:145)
	... 16 more

```

**To Reproduce**
VS Code 1.76.2
Spring Boot Extension Pack

Run or debug application

**Comment by BoykoAlex** [comment]
What's the context of this error? Were you trying to look at the memory graphs? What did you do as a user in VSCode that resulted in the error above? Is this issue reliably reproducible?

**Comment by donywan** [comment]
1. Switch `Problems` tool.
2. Upgrade pom dependents. `Newer minor version of Spring Boot available: 3.5.5`

> What's the context of this error? Were you trying to look at the memory graphs? What did you do as a user in VSCode that resulted in the error above? Is this issue reliably reproducible?

**Comment by martinlippert** [comment]
@donywan Switching to the problems view in VSCode is related to this error showing up?!? I can't see a relationship here. The error above looks related to fetching data from a running Spring Boot application to display some live metrics data...

**Comment by martinlippert** [comment]
But in any case, if someone can describe steps how to reproduce this, that would be hugely appreciated.

**Comment by martinlippert** [comment]
Added a check to avoid the NPEs, but if you have a project and/or steps how to reliably reproduce this, that would still be highly appreciated.
