### ISSUE TITLE
latest pre-release builds of VSCode extension are broken

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1057]
The latest CI builds of the VSCode extension seem to be completely broken. Installing the pre-release version into VSCode or the nightly CI build from a VSIX build results in a completely broken experience. The language server seems to start up, but is being shutdown immediately (for unknown reasons).

I experienced this with a simple petclinic sample project in my workspace.

The error message that I am seeing on the VSCode output tab for the Spring Tools extension looks like this:

```
Redirecting server logs to /Users/mlippert/Desktop/vscode-logs.txt
Redirecting log output to: /Users/mlippert/Desktop/vscode-logs.txt
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:05] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:06] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:06] Client vscode-spring-boot: connection to server is erroring. Shutting down server.
[Error - 12:30:07] Stopping server timed out
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
[Error - 12:30:07] Stopping server failed
Error: Stopping the server timed out
    at /Users/mlippert/.vscode/extensions/vmware.vscode-spring-boot-1.47.2023061304/node_modules/vscode-languageclient/lib/common/client.js:933:23
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
```

**Comment by BoykoAlex** [comment]
It is fixed with this PR: https://github.com/openrewrite/rewrite-static-analysis/pull/122. We need to wait until the JAR is published and then it'd be fixed for us too.
Essentially, any sys out calls in Boot LS or its dependencies corrupt JSON RPC comm between ls and the client since the comm is via standard in/out of the ls process. The comm expect only json messages with proper headers.

**Comment by BoykoAlex** [comment]
Yes, i see this fixed now. Next snapshot build will have this fixed.
