### ISSUE TITLE
Anonymous internal class compilation problem

### ISSUE THREAD

**Issue by bobchengit** [spring-projects/sts4#109]
There is an anonymous inner class implementation in the code. The anti-compiler looks at the compiled class and generates an anonymous class name that is inconsistent with the reference to the anonymous class name.

- part of source

` List<Map<String, Object>> datas = list.stream().collect(Collectors.groupingBy(TypeDeptCount::getType))
                .entrySet().stream().map(item -> item.getValue().stream().reduce(new HashMap<String, Object>() {
                    private static final long serialVersionUID = 1L;
                    {
                        put("count", 0);
                        put("type", item.getKey());
                    }
                }, (data1, val) -> {
                    data1.put(val.getCykbbm(), val.getCount());
                    data1.put("count", (Integer) data1.get("count") + val.getCount());
                    return data1;
                }, (data1, data2) -> {
                    data2.put("count", (Integer) data1.get("count") + (Integer) data2.get("count"));
                    data1.putAll(data2);
                    return data1;
                })).sorted((item1, item2) -> (Integer) item2.get("count") - (Integer) item1.get("count"))
                .collect(Collectors.toList());`

- Compiled code
`final List<TypeDeptCount> list = (List<TypeDeptCount>)this.mapper.getBaErrTypeDeptCount(qo);
        final List<Map<String, Object>> datas = list.stream().collect((Collector<? super Object, ?, Map<Object, List<? super Object>>>)Collectors.groupingBy((Function<? super Object, ?>)TypeDeptCount::getType)).entrySet().stream().map(item -> item.getValue().stream().reduce((**BaqcSummaryService.BaqcSummaryService$2**)new HashMap<String, Object>(item) {
            private static final long serialVersionUID = 1L;
            
            {
                ((HashMap<String, Integer>)this).put("count", 0);
                this.put("type", entry.getKey());
            }
        }, (data1, val) -> {
            data1.put(val.getCykbbm(), val.getCount());
            data1.put("count", data1.get("count") + val.getCount());
            return data1;
        }, (data1, data2) -> {
            data2.put("count", data1.get("count") + data2.get("count"));
            data1.putAll(data2);
            return data1;
        })).sorted((item1, item2) -> item2.get("count") - item1.get("count")).collect((Collector<? super Object, ?, List<Map<String, Object>>>)Collectors.toList());`

- Inner Compiled code
`import java.util.*;

class **BaqcSummaryService$1** extends HashMap<String, Object> {
    private static final long serialVersionUID = 1L;
    
    {
        ((HashMap<String, Integer>)this).put("count", 0);
        this.put("type", entry.getKey());
    }
}`

**Comment by kdvolder** [comment]
Sorry I'm going to need more context / details to understand what the problem is here, and how to reproduce it. Can you spell it out a bit more please. I really don't have clue right now about:

1) what is wrong exactly wrong in the wall of text you posted.
2) why we should consider this to be wrong (e.g. why do we even care how a code decompiles does that even matter? If it behaves the same when you run it its not really a problem)
3) what steps can I take to reproduce and observe the 'wrong behavior' myself (a complete sample project would be much easier for us to work with than some snippets than need to be pasted into something that makes them compile correctly, that we have to reverse engineer from the given snippets).
4) assuming it really is a problem... who should we blame (the jdt compiler? The spring framework? Some maven compiler plugin ...  whatever)

Now, I know it may be hard/impossible for you to answer the 4th question. And I don't expect you to. That's were we come in. But before we can get to a point were we can try to debug this and figure it out,  we really need a bit more help from you with the first 3 points here.

**Comment by kdvolder** [comment]
I'd like to add that although this ticket is closed (as it is most likely not an STS issue). You can still add more information and my offer to help figure out more precisely what is causing this bug still stands. But with the information that was provided in the ticket so far, unfortunately I don't really have enough to even attempt at reproducing the problem at all.

**Comment by bobchengit** [comment]
Think you ! I will upload a demo to github.

**Comment by bobchengit** [comment]
@kdvolder @martinlippert ，I have uploaded a demo, using STS4 to run the error, using STS3.8 normal。
https://github.com/bobchengit/sts4-problem-demo.git
ERROR:`Caused by: java.lang.ClassNotFoundException: com.kindo.demo.Run$2`
Thinks

**Comment by kdvolder** [comment]
Okay, so this project doesn't quite work 'out of the box' for me. Aparantly it requires lombok which is not something that comes pre-installed with Eclipse or STS. I simplified the project by getting rid of lombok and just creating getter / setters for the @Data class manutally. The problem still happens so this rules it out lombok as the potential cause of the problem.

When I build and run the project from Eclipse I get this:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/kindo/demo/Run$2
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.kindo.demo.Run$2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

At first sight, I'd say this is probably a bug in the JDT compiler which should be reported on Eclipse bugzilla tracker. But let me experiment a bit more and see if the same problem happens when we just build and run this project with maven on the commandline.

**Comment by kdvolder** [comment]
Simplified sample project some more remove all the test related bits (junit dependencies and test resource/sources). Problem still happens.

**Comment by kdvolder** [comment]
Runs fine when I just built it on the commandline via these commands:

```
mvn clean package
java -cp target/java-core-0.0.1-SNAPSHOT.jar com.kindo.demo.Run
```

So yes, this seems like almost certainly a bug/problem in the Eclipse JDT compiler.

**Comment by kdvolder** [comment]
What we should do next (I intend to do it myself a bit later, unless someone else beats me to it :-)

- package up the simplified project (i.e. no lombok, no dependencies, probably doesn't even need to be a maven project)
- try to reproduce this problem with a Vanilla Eclipse (I'm almost certain that it should be reproducible since its really just a plain java project with nothing special about it, no spring, no lombok, no dependencies).
- write up a good description of the exact steps to reproduce, with attached simplified sample project. Raise a bug ticket here  https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT

**Comment by kdvolder** [comment]
[sts4-problem-demo-no-lombok.zip](https://github.com/spring-projects/sts4/files/2488625/sts4-problem-demo-no-lombok.zip)

Attaching the 'simplified' sample project here for safekeeping for the time being until I have time to submit bugreport to Eclipse bugzilla.

**Comment by bobchengit** [comment]
@kdvolder ，Thank you for your answer.

**Comment by kdvolder** [comment]
No problem and thanks for bumping the thread. I almost forgot I promised to follow up with an Eclipse bug report. 

Finally got round to it. Eclipse bug report filed here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=540520
