### ISSUE TITLE
eclipse shortcut ctrl+f7 gives error

### ISSUE THREAD

**Issue by sgulci** [spring-projects/sts4#111]
Hi all,

today i install sts4 eclipse, when i use Ctrl+F7 for switching view it gives below error 
 
![image](https://user-images.githubusercontent.com/3424995/47011967-d3257580-d14b-11e8-96a6-e6755dd7d93a.png)

i use windows 10, java 1.8.0_131 
 
thanks

**Comment by martinlippert** [comment]
Please open the Error Log view and take a look if you can find more details for this error in that list. If so, it would be great if you could post the full stack trace here.

**Comment by sgulci** [comment]
error log here 

> eclipse.buildId=4.0.0.201809220817-RELEASE
> java.version=1.8.0_131
> java.vendor=Oracle Corporation
> BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
> Framework arguments:  -product org.springframework.boot.ide.branding.sts4
> Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springframework.boot.ide.branding.sts4
> 
> This is a continuation of log file D:\Users\sgulci\eclipse-workspace\.metadata\.bak_1.log
> Created Time: 2018-10-16 12:59:06.637
> 
> org.eclipse.jface
> Error
> Tue Oct 16 14:19:25 EET 2018
> Problems occurred when invoking code from plug-in: "org.eclipse.jface".
> 
> java.lang.NullPointerException
> 	at org.eclipse.ui.internal.ViewReference.getPartName(ViewReference.java:73)
> 	at org.eclipse.ui.internal.CycleViewHandler.getWorkbenchPartReferenceText(CycleViewHandler.java:94)
> 	at org.eclipse.ui.internal.FilteredTableBaseHandler$6.getText(FilteredTableBaseHandler.java:858)
> 	at org.eclipse.jface.viewers.ColumnLabelProvider.update(ColumnLabelProvider.java:37)
> 	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:144)
> 	at org.eclipse.jface.viewers.AbstractTableViewer.doUpdateItem(AbstractTableViewer.java:394)
> 	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:478)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
> 	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
> 	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2161)
> 	at org.eclipse.jface.viewers.AbstractTableViewer.createItem(AbstractTableViewer.java:286)
> 	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefreshAll(AbstractTableViewer.java:723)
> 	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:615)
> 	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:607)
> 	at org.eclipse.jface.viewers.AbstractTableViewer.lambda$0(AbstractTableViewer.java:569)
> 	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1449)
> 	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1410)
> 	at org.eclipse.jface.viewers.AbstractTableViewer.inputChanged(AbstractTableViewer.java:569)
> 	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:289)
> 	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1687)
> 	at org.eclipse.ui.internal.FilteredTableBaseHandler.openDialog(FilteredTableBaseHandler.java:216)
> 	at org.eclipse.ui.internal.FilteredTableBaseHandler.execute(FilteredTableBaseHandler.java:132)
> 	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
> 	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:207)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:582)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:651)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:441)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$2(KeyBindingDispatcher.java:384)
> 	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1193)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1054)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1064)
> 	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1106)
> 	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1102)
> 	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1745)
> 	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5160)
> 	at org.eclipse.swt.widgets.Tree.WM_KEYDOWN(Tree.java:6095)
> 	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4800)
> 	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:5963)
> 	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4792)
> 	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
> 	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2309)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3559)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
> 
>

**Comment by martinlippert** [comment]
Thanks for the detailed error log, that helps a lot. Looks like there is no Spring-Tools-specific element included here, so we need to search for this in the Eclipse platform area. Can you reproduce this error using a vanilla Eclipse 2018-09 install? Would be great if you could try that, then we can decide whether to investigate this here or file a bug for Eclipse itself.

**Comment by sgulci** [comment]
i installed eclipse 2018-09 vanilla and it is worked fine,

**Comment by martinlippert** [comment]
Okay, thanks a lot for testing. Can you provide a few steps how to reproduce this? Does this happen immediately after starting up a fresh STS4 with an empty workspace and pressing Ctrl+F7 ?

**Comment by kdvolder** [comment]
This kind of error trace may be dependent on some (old) state in the workspace. Something like an old view or perspective's state that somehow trips up Eclipse when it is trying to restore that state. Finding out exactly what it is, or how to reproduce it could be very hard. 

The first thing worth to try is to start STS in a new workspace to check if perhaps that makes the problem go away. If you can still reproduce this problem in a brand new workspace, then please take note of exactly what you did to make it happen so we can repeat the steps as well.

**Comment by kdvolder** [comment]
I imported the project into a new STS 4 workspace but it doesn't even compile.

Errors:

```
Description	Resource	Path	Location	Type
The method groupingBy(Function<? super T,? extends K>) in the type Collectors is not applicable for the arguments (TypeDeptCount::getType)	Run.java	/java-core/src/main/java/com/kindo/demo	line 19	Java Problem
The method setCount(int) is undefined for the type TypeDeptCount	Run.java	/java-core/src/main/java/com/kindo/demo	line 17	Java Problem
The method setCykbbm(String) is undefined for the type TypeDeptCount	Run.java	/java-core/src/main/java/com/kindo/demo	line 16	Java Problem
The type TypeDeptCount does not define getType(T) that is applicable here	Run.java	/java-core/src/main/java/com/kindo/demo	line 19	Java Problem
```

**Comment by kdvolder** [comment]
Oh sorry, looks like I got some wires crossed. The comments above where meant for a different issue ticket. Please disregard (and I will delete them).

**Comment by sgulci** [comment]
when i create clean workspace folder problem solved, thanks a lot.
