### ISSUE TITLE
LSP(Spring Boot Language Server) error

### ISSUE THREAD

**Issue by drc5521** [spring-projects/sts4#1140]
**Describe the bug**
when I open sts4(V4.20.1).It will pop up an error as shown in the figure.

**To Reproduce**
![Snipaste](https://github.com/spring-projects/sts4/assets/55195642/5515eec3-119a-458e-87c0-ecd8c9708040)
```
10:31:58.960 [Project-Reconciler-1] ERROR o.s.i.v.b.v.g.ProjectVersionDiagnosticProvider - 
java.lang.IllegalArgumentException: port out of range:-1
	at java.base/java.net.InetSocketAddress.checkPort(InetSocketAddress.java:152)
	at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:233)
	at org.springframework.ide.vscode.boot.app.RestTemplateFactory.createRestTemplate(RestTemplateFactory.java:53)
	at org.springframework.ide.vscode.boot.validation.generations.SpringProjectsClient.get(SpringProjectsClient.java:78)
	at org.springframework.ide.vscode.boot.validation.generations.SpringProjectsClient.fromEmbedded(SpringProjectsClient.java:57)
	at org.springframework.ide.vscode.boot.validation.generations.SpringProjectsClient.getSpringProjects(SpringProjectsClient.java:44)
	at org.springframework.ide.vscode.boot.validation.generations.SpringIoProjectsProvider.cache(SpringIoProjectsProvider.java:84)
	at org.springframework.ide.vscode.boot.validation.generations.SpringIoProjectsProvider.getProject(SpringIoProjectsProvider.java:75)
	at org.springframework.ide.vscode.boot.validation.generations.UpdateBootVersion.validate(UpdateBootVersion.java:49)
	at org.springframework.ide.vscode.boot.validation.generations.ProjectVersionDiagnosticProvider.getDiagnostics(ProjectVersionDiagnosticProvider.java:60)
	at org.springframework.ide.vscode.boot.validation.BootVersionValidationEngine.reconcile(BootVersionValidationEngine.java:50)
	at org.springframework.ide.vscode.boot.common.ProjectReconcileScheduler.lambda$scheduleValidation$0(ProjectReconcileScheduler.java:85)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.springframework.ide.vscode.boot.common.ProjectReconcileScheduler.lambda$scheduleValidation$1(ProjectReconcileScheduler.java:83)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:171)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by BoykoAlex** [comment]
Duplicate of #1137 - The workaround is in Pereferences General -> Network Connections switch to "Direct" from "Native"

**Comment by kiranbarikdd** [comment]
Alreday set as Direct but still gettign same issue

**Comment by martinlippert** [comment]
@kiranbarikdd Do you see the exact same stack trace mentioning the port? And which version of the Spring Tools do you have installed?

**Comment by kiranbarikdd** [comment]
@martinlippert  I have installed below version, yes, i got this problem frequenly.
Version: 4.29.1.RELEASE
Build Id: 202503181406
Revision: 806640e3af881dd5d3e9fc6e108e051fa1e1f7c2

**Comment by martinlippert** [comment]
@kiranbarikdd Can you update to the latest release and let us know whether this still happens or not and what your network connection looks like (behind a proxy, preferences inside of Eclipse). Thanks!!!
