### ISSUE TITLE
issue starting multiple projects simultaneously in the Boot Dashboard

### ISSUE THREAD

**Issue by navy1978** [spring-projects/sts4#1191]
Hello,
I've encountered an issue when attempting to start multiple projects simultaneously in the Boot Dashboard. Despite selecting them together, the startup process fails to locate the main class for each project. The console displays a recurring message similar to this:

```
Error: Could not find or load main class xxx.yyyy.MyApplication
Caused by: java.lang.ClassNotFoundException: xxx.yyyy.MyApplication
```

this is the stacktrace in metadata .log:
```


!ENTRY org.eclipse.jdt.apt.pluggable.core 1 1 2024-02-14 14:48:22.170
!MESSAGE Hibernate/JPA static Metamodel Generator 6.3.2.Final

!ENTRY org.eclipse.jdt.apt.pluggable.core 1 1 2024-02-14 14:48:23.776
!MESSAGE Hibernate/JPA static Metamodel Generator 6.3.2.Final

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:24.981
!MESSAGE Failed to save JDT index: Index for /myapp1-api
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:25.001
!MESSAGE Failed to save JDT index: Index for /myapp2-api
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:966)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:25.010
!MESSAGE Failed to save JDT index: Index for /myapp3-api
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:25.085
!MESSAGE Failed to save JDT index: Index for /myapp4
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 0 2024-02-14 14:48:25.101
!MESSAGE Failed to update qualified index.
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.index.MetaIndex.save(MetaIndex.java:99)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveMetaIndex(IndexManager.java:1245)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1221)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.apt.pluggable.core 1 1 2024-02-14 14:48:25.435
!MESSAGE Hibernate/JPA static Metamodel Generator 6.3.2.Final

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:27.013
!MESSAGE Failed to save JDT index: Index for /myapp1
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:27.014
!MESSAGE Failed to save JDT index: Index for /myapp2
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:966)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:27.014
!MESSAGE Failed to save JDT index: Index for /myapp3
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:27.037
!MESSAGE Failed to save JDT index: Index for /myapp4
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 0 2024-02-14 14:48:27.038
!MESSAGE Failed to update qualified index.
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.index.MetaIndex.save(MetaIndex.java:99)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveMetaIndex(IndexManager.java:1245)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1221)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:29.294
!MESSAGE Failed to save JDT index: Index for /myapp1
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:29.295
!MESSAGE Failed to save JDT index: Index for /myapp2
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:966)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:29.295
!MESSAGE Failed to save JDT index: Index for /myapp3
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:29.306
!MESSAGE Failed to save JDT index: Index for /myapp4
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 0 2024-02-14 14:48:29.307
!MESSAGE Failed to update qualified index.
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.index.MetaIndex.save(MetaIndex.java:99)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveMetaIndex(IndexManager.java:1245)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1221)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:45.619
!MESSAGE Failed to save JDT index: Index for /myapp1
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:45.619
!MESSAGE Failed to save JDT index: Index for /myapp2
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:966)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:45.620
!MESSAGE Failed to save JDT index: Index for /myapp3
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 4 2024-02-14 14:48:45.631
!MESSAGE Failed to save JDT index: Index for /myapp4
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndex(IndexManager.java:1152)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1196)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.eclipse.jdt.core 4 0 2024-02-14 14:48:45.632
!MESSAGE Failed to update qualified index.
!STACK 0
java.io.UTFDataFormatException
	at org.eclipse.jdt.internal.core.index.DiskIndex.readStreamChars(DiskIndex.java:984)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readChunk(DiskIndex.java:756)
	at org.eclipse.jdt.internal.core.index.DiskIndex.readAllDocumentNames(DiskIndex.java:641)
	at org.eclipse.jdt.internal.core.index.DiskIndex.mergeWith(DiskIndex.java:533)
	at org.eclipse.jdt.internal.core.index.Index.save(Index.java:228)
	at org.eclipse.jdt.internal.core.index.MetaIndex.save(MetaIndex.java:99)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveMetaIndex(IndexManager.java:1245)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.saveIndexes(IndexManager.java:1221)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.notifyIdle(IndexManager.java:837)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:509)
	at java.base/java.lang.Thread.run(Thread.java:840)

!ENTRY org.springframework.ide.eclipse.boot.dash 4 0 2024-02-14 14:48:59.676
!MESSAGE Failed to connect to Boot app
!STACK 0
java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:732)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
	at org.springframework.ide.eclipse.boot.dash.liveprocess.DefaultLiveProcessCommandExecutor.executeCommand(DefaultLiveProcessCommandExecutor.java:60)
	at org.springframework.ide.eclipse.boot.dash.BootDashActivator$1.stateChanged(BootDashActivator.java:219)
	at org.springframework.ide.eclipse.boot.dash.BootDashActivator$1.stateChanged(BootDashActivator.java:1)
	at org.springframework.ide.eclipse.boot.dash.util.RunStateTracker.updateOwnerStatesAndFireEvents(RunStateTracker.java:216)
	at org.springframework.ide.eclipse.boot.dash.util.RunStateTracker$1.gotValue(RunStateTracker.java:151)
	at org.springframework.ide.eclipse.boot.dash.util.RunStateTracker$1.gotValue(RunStateTracker.java:1)
	at org.springsource.ide.eclipse.commons.livexp.core.LiveExpression.changed(LiveExpression.java:137)
	at org.springsource.ide.eclipse.commons.livexp.core.LiveExpression.refresh(LiveExpression.java:81)
	at org.springsource.ide.eclipse.commons.livexp.core.LiveVariable.setValue(LiveVariable.java:46)
	at org.springframework.ide.eclipse.boot.dash.util.AbstractPollingAppReadyStateMonitor$1.run(AbstractPollingAppReadyStateMonitor.java:51)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

FYI: starting them one by one everything works fine

I forgot to mention I'm on STS 4.21.0.
Thank you.

**Comment by martinlippert** [comment]
> ```
> Error: Could not find or load main class xxx.yyyy.MyApplication
> Caused by: java.lang.ClassNotFoundException: xxx.yyyy.MyApplication
> ```

But I am assuming that the main class name that appears on the console is the right one, correct?

**Comment by BoykoAlex** [comment]
Even after launching each app separately you still cannot select them all and launch?

**Comment by BoykoAlex** [comment]
Overall it seems like the JDT index is corrupted... Can you try deleting `.index` files under `<workspace folder>/.metadata/.plugins/org.eclipse.jdt.core`? Shut down Eclipse, delete files, start the Eclipse. I hope it should re-index java types.
STS plugins don't write into the index but rather ask the index to find types with main method... I wouldn't expect this to corrupt the index...

**Comment by BoykoAlex** [comment]
Also, it'd be great if you could attach here the projects you're having in the workspace which reproduce the problem for you. It'd likely help us reproducing the issue on our side.

**Comment by navy1978** [comment]
> > ```
> > Error: Could not find or load main class xxx.yyyy.MyApplication
> > Caused by: java.lang.ClassNotFoundException: xxx.yyyy.MyApplication
> > ```
> 
> But I am assuming that the main class name that appears on the console is the right one, correct?

Yes the class is correct 


> Even after launching each app separately you still cannot select them all and launch?

Not sure I have memories that this could not fix the issue, even if today it did it



> Overall it seems like the JDT index is corrupted... Can you try deleting `<workspace folder>/.metadata/.plugins/org.eclipse.jdt.core` folder? Shut down Eclipse, delete the folder, start the Eclipse. I hope it should re-index java types. STS plugins don't write into the index but rather ask the index to find types with main method... I wouldn't expect this to corrupt the index... (I have tried launching a few apps at once - seemed okay)

I will do that as sson as it will happen again and I will keep you updated. This happened a lot of times for us (to me and one of my colleagues)

**Comment by navy1978** [comment]
It has happened again and indeed deleting <workspace folder>/.metadata/.plugins/org.eclipse.jdt.core triggered the indexing.
