### ISSUE TITLE
NPE exception while scanning for symbols

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1239]
```
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "allProjectSymbols" is null
	at org.springframework.ide.vscode.boot.app.SpringSymbolIndex.getDocsFromPath(SpringSymbolIndex.java:605)
	at org.springframework.ide.vscode.boot.app.SpringSymbolIndex.getDocsPerProjectFromPaths(SpringSymbolIndex.java:594)
	at org.springframework.ide.vscode.boot.app.SpringSymbolIndex.deleteDocuments(SpringSymbolIndex.java:647)
	at org.springframework.ide.vscode.boot.app.SpringSymbolIndex.lambda$8(SpringSymbolIndex.java:310)
	at org.springframework.ide.vscode.commons.util.BasicFileObserver.lambda$6(BasicFileObserver.java:131)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3612)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.ide.vscode.commons.util.BasicFileObserver.notify(BasicFileObserver.java:131)
	at org.springframework.ide.vscode.commons.util.BasicFileObserver.notifyFilesDeleted(BasicFileObserver.java:97)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleWorkspaceService.lambda$2(SimpleWorkspaceService.java:117)
	at org.springframework.ide.vscode.commons.util.AsyncRunner.lambda$1(AsyncRunner.java:75)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73)
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32)
	at reactor.core.publisher.MonoCallableOnAssembly.call(MonoCallableOnAssembly.java:91)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:228)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by martinlippert** [comment]
Fixed with https://github.com/spring-projects/sts4/commit/2bd054a6b402b7cc7d5b254a21063762b7aaec95
