### ISSUE TITLE
Upgraded to 4.23.0: MarketplaceDiscoveryStrategy failed with an error

### ISSUE THREAD

**Issue by space88man** [spring-projects/sts4#1272]
**Describe the bug**
In Eclipse Marketplace -> Installed tab

```
MarketplaceDiscoveryStrategy failed with an error
Unexpected response for '3394048,807489,5026683,3581018,1336,58287,2953952,5578890,2177882,4123770,2306961,1789419'
```

**To Reproduce**
Help -> Eclipse Marketplace ... -> Installed

**Additional Notes**
* all other tabs in Eclipse Marketplace are working  
    this is a STS installation that has been upgraded many times
* clean install of  eclipse-jee works on all tabs  
* clean install of  STS 4.23.0 works on all tabs

**Comment by martinlippert** [comment]
Is there maybe an exception or error details showing up related to this when you open the `Error Log` view?

You mentioning that the instance that is showing this error has been updated many times makes me worry that this might be hard to debug, especially if a plain vanilla installation works fine.

**Comment by space88man** [comment]
Yes - this might be too complicated to narrow done.

**Comment by martinlippert** [comment]
If you want to investigate situations like this in more detail, the Error Log view is one of the first step.

If that doesn't help - especially after multiple upgrades - you can open the `Console` view, open a `OSGi Host Console` from the dropdown, type in `ss`, and press enter. This gives you the status of all the installed bundles in your IDE. Sometimes -especially after upgrades - there are incompatibilities appearing over time that you would see in this overview list, e.g. if the status of a bundle is `INSTALLED` instead of something else. This is usually the steps that I follow to investigate those situations. Unfortunately, even if you identify an issue in there, it would be mostly interesting to us, since we could try to prevent specific situations from happening in the future. Usually, the user can't do much about those situations within their IDE installs directly.

So installing a fresh version is the best way forward, I think.

**Comment by rparks52** [comment]
I am also having this error, I can provide the error from the error log.. 
Stack Trace: 
`org.eclipse.core.runtime.CoreException: Unexpected response for '2963400,311774,1617241,1687099,2953952,58287,3029282,3799227,4123770,2963451'
	at org.eclipse.epp.internal.mpc.core.service.DefaultMarketplaceService.getNodesById(DefaultMarketplaceService.java:386)
	at org.eclipse.epp.internal.mpc.core.service.DefaultMarketplaceService.getNodes(DefaultMarketplaceService.java:328)
	at org.eclipse.epp.internal.mpc.core.service.CachingMarketplaceService.getNodes(CachingMarketplaceService.java:164)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceDiscoveryStrategy.computeInstalled(MarketplaceDiscoveryStrategy.java:831)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceDiscoveryStrategy.installed(MarketplaceDiscoveryStrategy.java:814)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceCatalog.lambda$6(MarketplaceCatalog.java:106)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceCatalog.runDiscoveryOperation(MarketplaceCatalog.java:529)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceCatalog.performDiscovery(MarketplaceCatalog.java:488)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceCatalog.installed(MarketplaceCatalog.java:106)
	at org.eclipse.epp.internal.mpc.ui.wizards.MarketplaceViewer.lambda$6(MarketplaceViewer.java:681)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
`

Session Data: 
```
eclipse.buildId=4.28.0.20230608-1200
java.version=17.0.7
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

This is a continuation of log file C:\Users\randall\eclipse-workspace\.metadata\.bak_2.log
Created Time: 2024-12-13 10:38:36.735
```

**Comment by martinlippert** [comment]
@rparks52 Can you double check if the error occurs when using the latest release as well? That would be great.

Maybe the same or a related issue is filed here: https://github.com/eclipse-mpc/epp.mpc/issues/9 - and that is probably the repo where these errors regarding issues with the Eclipse marketplace should be reported to.

**Comment by phavel** [comment]
I have the same problem. 

My version:
Version: 4.32.2.RELEASE
Build Id: 202511091838
Revision: c943bbb2b13c44e9337849d7f23690c7cf6f1a16
