### ISSUE TITLE
Invalid thread access on SWT

### ISSUE THREAD

**Issue by helospark** [spring-projects/sts4#128]
Receiving the following exception with Eclipse 2018-09:

When running an application with Run -> Spring Boot application, I cannot see the bean annotations, I'm receiving the following exception (100s of them):
```
REPORT

anonymousId         4d17c0b9-2546-4447-bf71-ab5688582e39
name                
email               
comment             
eclipseBuildId      4.9.0.I20180906-0745
eclipseProduct      org.eclipse.epp.package.java.product
javaRuntimeVersion  1.8.0_191-b12
osgiWs              win32
osgiOs              Windows10
osgiOsVersion       10.0.0
osgiArch            x86_64
severity            UNKNOWN


STATUS

pluginId            org.eclipse.osgi
pluginVersion       3.13.100.v20180827-1536
code                0
severity            4
message             An error occurred while automatically activating bundle org.springframework.tooling.ls.eclipse.commons (624).
fingerprint         c8a51a71a06a3d231410143ea2306bf6

Exception:org.osgi.framework.BundleException: Exception in org.springframework.tooling.ls.eclipse.commons.LanguageServerCommonsActivator.start() of bundle org.springframework.tooling.ls.eclipse.commons.
	 at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:803)
	 at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:732)
	 at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
	 at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
	 at org.eclipse.osgi.container.Module.doStart(Module.java:584)
	 at org.eclipse.osgi.container.Module.start(Module.java:452)
	 at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:471)
	 at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	 at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:557)
	 at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:331)
	 at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	 at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:473)
	 at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	 at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	 at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	 at java.lang.ClassLoader.loadClass(null:-1)
	 at org.springframework.tooling.boot.ls.DelegatingStreamConnectionProvider.<init>(DelegatingStreamConnectionProvider.java:64)
	 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(null:-2)
	 at sun.reflect.NativeConstructorAccessorImpl.newInstance(null:-1)
	 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(null:-1)
	 at java.lang.reflect.Constructor.newInstance(null:-1)
	 at java.lang.Class.newInstance(null:-1)
	 at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:190)
	 at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:934)
	 at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	 at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	 at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:114)
	 at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:196)
	 at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrapperForConnection(LanguageServiceAccessor.java:340)
	 at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrappers(LanguageServiceAccessor.java:299)
	 at org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfosFor(LanguageServiceAccessor.java:444)
	 at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$1.run(ConnectDocumentToLanguageServerSetupParticipant.java:75)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.swt.SWTException: Invalid thread access
	 at org.eclipse.swt.SWT.error(SWT.java:4595)
	 at org.eclipse.swt.SWT.error(SWT.java:4510)
	 at org.eclipse.swt.SWT.error(SWT.java:4481)
	 at org.eclipse.swt.widgets.Display.error(Display.java:1185)
	 at org.eclipse.swt.widgets.Display.checkDevice(Display.java:737)
	 at org.eclipse.swt.widgets.Display.disposeExec(Display.java:1130)
	 at org.eclipse.jface.resource.ColorRegistry.hookDisplayDispose(ColorRegistry.java:259)
	 at org.eclipse.jface.resource.ColorRegistry.<init>(ColorRegistry.java:122)
	 at org.springframework.tooling.ls.eclipse.commons.LanguageServerCommonsActivator.start(LanguageServerCommonsActivator.java:93)
	 at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:782)
	 at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	 at java.security.AccessController.doPrivileged(null:-2)
	 at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:775)
	 at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:732)
	 at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1005)
	 at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:357)
	 at org.eclipse.osgi.container.Module.doStart(Module.java:584)
	 at org.eclipse.osgi.container.Module.start(Module.java:452)
	 at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:471)
	 at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	 at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:557)
	 at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:331)
	 at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	 at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:473)
	 at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	 at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	 at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	 at java.lang.ClassLoader.loadClass(null:-1)
	 at org.springframework.tooling.boot.ls.DelegatingStreamConnectionProvider.<init>(DelegatingStreamConnectionProvider.java:64)
	 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(null:-2)
	 at sun.reflect.NativeConstructorAccessorImpl.newInstance(null:-1)
	 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(null:-1)
	 at java.lang.reflect.Constructor.newInstance(null:-1)
	 at java.lang.Class.newInstance(null:-1)
	 at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:190)
	 at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:934)
	 at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	 at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	 at org.eclipse.lsp4e.LanguageServersRegistry$ExtensionLanguageServerDefinition.createConnectionProvider(LanguageServersRegistry.java:114)
	 at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:196)
	 at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrapperForConnection(LanguageServiceAccessor.java:340)
	 at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrappers(LanguageServiceAccessor.java:299)
	 at org.eclipse.lsp4e.LanguageServiceAccessor.getLSPDocumentInfosFor(LanguageServiceAccessor.java:444)
	 at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant$1.run(ConnectDocumentToLanguageServerSetupParticipant.java:75)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


BUNDLES

name                org.eclipse.core.jobs
version             3.10.100.v20180817-1215

name                org.eclipse.jface
version             3.14.100.v20180828-0836

name                org.eclipse.lsp4e
version             0.7.0.201809061243

name                org.eclipse.osgi
version             3.13.100.v20180827-1536

name                org.eclipse.swt
version             3.108.0.v20180904-1901

name                org.springframework.tooling.boot.ls
version             1.0.0.201809220747

name                org.springframework.tooling.ls.eclipse.commons
version             4.0.0.201809220747
```

I have a standalone Eclipse 2018-09, and I have installed the STS4 plugin.

Based on a quick look in the stacktrace, it appears that `ColorRegistry` constructor in the bundle is not called by the display's UI thread. However may be caused by plugin-order (see below Eclipse issue), after installing PDE plugin, seems like this exception disappeared from one of the computers I have tried.
I was able to find a similar old issue in Eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=296512

I have been able to reproduce this issue on two computers with Windows 10 with both Java 8 and Java 10, however now that I try to find reliable repro step, it not always fails with this issue, but maybe someone knows, what causes this.

**Comment by kdvolder** [comment]
Hmmm... I don't know exactly what is going on but I think your hunch that it will happen... or not... depending on plugin activation ordering is probably spot on.

We are creating the ColorRegistry object in our bundle's start method. It looks like for the most part this will work. But in rare occasions it might be doing some kind of setup code that must be run in the UI thread.

I don't think budle activation methods will ever run in the ui thread themselves, but I think when we get lucky (seems to be the common case, since we have no other bug reports of this) the code that needs to run in the ui thread is probably not being executed (I'm guessing its one of those things that only gets done once, and so if another bundle has already done this... then we are fine).

Just guesssing a bit though.

Whatever the case may be, I think it is pretty clear that we shold not be calling the ColorRegistry constructor without somehow making sure it is running on the ui thread and this is something that we control, so we should be able to fix.
