### ISSUE TITLE
Eclipse Marketplace Discovery Strategy failed with an error In Installed tab when build up to version 4.32.0

### ISSUE THREAD

**Issue by LonieN** [spring-projects/sts4#1284]
An anyone help me with this error when I update to Eclipse version 4.32.0. Thank you

> org.eclipse.core.runtime.CoreException: Unexpected response for
>  '2306961,1103239,3581018,1617241,4716941,5012014,
> 4528322,1166,4290168,5026683,5321178,2177882,2433251,264,3184658'

![image](https://github.com/spring-projects/sts4/assets/30336860/230bca9f-846a-4540-aebc-b9b767c9d255)
![image](https://github.com/spring-projects/sts4/assets/30336860/9b663ba9-7489-4763-86ae-bee0aef69b80)

**Comment by martinlippert** [comment]
I haven't seen this myself yet, could be related to a network issue. Are you behind a proxy?

**Comment by LonieN** [comment]
I don't behind a proxy, I can access tabs on Eclipse Marketplace and can sign in my account but when I click on "Installed" tab will show errror dialog like this

**Comment by LonieN** [comment]
> I haven't seen this myself yet, could be related to a network issue. Are you behind a proxy?

I don't behind a proxy, I can access tabs on Eclipse Marketplace and can sign in my account but when I click on "Installed" tab will show error dialog like this 

<img width="443" alt="image" src="https://github.com/spring-projects/sts4/assets/30336860/8cf85cd8-5161-4bd6-8b3d-044b3ee846ea">

![image](https://github.com/spring-projects/sts4/assets/30336860/76c6fff6-993f-4596-bf38-65c2ed81d533)

**Comment by martinlippert** [comment]
Ah, okay, so this happens only when you click on the `Installed` tab, but everything else works? Trying this from a plain Spring Tools for Eclipse distribution doesn't reproduce this, so we need to look deeper into this. Looks like you are running a JEE package of Eclipse. Did you install anything into that already? Or does the error show up for you using a plain vanilla Eclipse JEE package install? Or only after you installed certain extensions?

**Comment by LonieN** [comment]
> Ah, okay, so this happens only when you click on the `Installed` tab, but everything else works? Trying this from a plain Spring Tools for Eclipse distribution doesn't reproduce this, so we need to look deeper into this. Looks like you are running a JEE package of Eclipse. Did you install anything into that already? Or does the error show up for you using a plain vanilla Eclipse JEE package install? Or only after you installed certain extensions?

Yes, I am using JEE Eclipse IDE version 4.30.0.20231201-1200 (20231201) and have installed all the necessary tools plugins package for development and everything is still running smoothly. When there was a notification that there was an update to version 20240606, I then upgraded to version 4.32.0.20240606-1231. After successfully updating and restarting the IDE, I checked about version: 2024-06 (4.32.0) . After that, I went to the Marketplace (Installed tab) to see if there were any new updates for any packages, but I got the error as above. Not sure why, I haven't installed any additional packages, could there be a conflict of versions of the plugin packages?

![image](https://github.com/spring-projects/sts4/assets/30336860/9938184f-35e1-4ce5-b39e-c8b18619730a)

**Comment by martinlippert** [comment]
@LonieN It is probably worth to start with a fresh installation of the latest Eclipse JEE package and re-install the third-party plugins into that. If you want to automate that, you can script the installation of additional plugins into Eclipse (e.g. an updated version of https://gist.github.com/martinlippert/5155155 might give you some inspiration on that).

If you want to debug the issue in more detail, I would recommend to file and discuss this with the Marketplace client project (https://github.com/eclipse-mpc/epp.mpc)

**Comment by LonieN** [comment]
> @LonieN It is probably worth to start with a fresh installation of the latest Eclipse JEE package and re-install the third-party plugins into that. If you want to automate that, you can script the installation of additional plugins into Eclipse (e.g. an updated version of https://gist.github.com/martinlippert/5155155 might give you some inspiration on that).
> 
> If you want to debug the issue in more detail, I would recommend to file and discuss this with the Marketplace client project (https://github.com/eclipse-mpc/epp.mpc)

Thanks so much. I'll try as you mentioned :)

**Comment by MarcoSchool** [comment]
> > I haven't seen this myself yet, could be related to a network issue. Are you behind a proxy?
> 
> I don't behind a proxy, I can access tabs on Eclipse Marketplace and can sign in my account but when I click on "Installed" tab will show error dialog like this
> <img alt="image" width="443" src="https://private-user-images.githubusercontent.com/30336860/344560964-8cf85cd8-5161-4bd6-8b3d-044b3ee846ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMjI0NDksIm5iZiI6MTczMTEyMjE0OSwicGF0aCI6Ii8zMDMzNjg2MC8zNDQ1NjA5NjQtOGNmODVjZDgtNTE2MS00YmQ2LThiM2QtMDQ0YjNlZTg0NmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDAzMTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZmZlYmEyMmU1ZTFkMjMzMGVlZGYyMDAxMDA1NWFkNmYxNDE1MzI5Y2NmNDYzODgwMDI1MGFkNTBlZWVlNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TCbKzRflIhv7MpXC0eFYmwZ8MWC5tOeR74B15ZuAndQ">
> 
> ![image](https://private-user-images.githubusercontent.com/30336860/344561058-76c6fff6-993f-4596-bf38-65c2ed81d533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMjI0NDksIm5iZiI6MTczMTEyMjE0OSwicGF0aCI6Ii8zMDMzNjg2MC8zNDQ1NjEwNTgtNzZjNmZmZjYtOTkzZi00NTk2LWJmMzgtNjVjMmVkODFkNTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDAzMTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZDgzODg2Zjc2MTVlNTA1YjM4Mzk2NjRmMjFkZGI4ZGZlM2Q5YmE1OTJlN2FiNjYxMDIwNmZhMzIxNWM4MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gYX8w6w0E-p1uU3ntCj9HvdWvy1ep_A3W8NgT_TSE40)

same problem occurs with me here. When clicking "installed" tab.
I am on an STS 
(Spring Tool Suite 4 
Version: 4.26.0.RELEASE
Build Id: 202410162246
Revision: 59e1b0ca76b2f5da1c5810c6cc9ceaf7c0bfa052)
 
Unexpected response for '2963451,322004,2177882,1794107,3581018,1789419,2234530,2963400,979,5321178,2706327,1617241,807489,1139,1963651,4716941'

Unexpected response for '979,3581018,2706327,4716941,2963400,1789419,2234530,322004,1794107,2177882,5321178,1963651,1617241,1139,2963451,807489'

Unexpected response for '1794107,2706327,1789419,2234530,807489,3581018,4716941,2963400,1139,2177882,322004,2963451,1963651,5321178,979,1617241'

and I found this "org.eclipse.core.runtime.CoreException: Unexpected response for '979,3581018,2706327,4716941,2963400,1789419,2234530,322004,1794107,2177882,5321178,1963651,1617241,1139,2963451,807489'
	at org.eclipse.epp.internal.mpc.core.service.DefaultMarketplaceService.getNodesById(DefaultMarketplaceService.java:386)
	at org.eclipse.epp.internal.mpc.core.service.DefaultMarketplaceService.getNodes(DefaultMarketplaceService.java:328)
	at org.eclipse.epp.internal.mpc.core.service.CachingMarketplaceService.getNodes(CachingMarketplaceService.java:164)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceDiscoveryStrategy.computeInstalled(MarketplaceDiscoveryStrategy.java:831)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceDiscoveryStrategy.installed(MarketplaceDiscoveryStrategy.java:814)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceCatalog.lambda$6(MarketplaceCatalog.java:106)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceCatalog.runDiscoveryOperation(MarketplaceCatalog.java:529)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceCatalog.performDiscovery(MarketplaceCatalog.java:488)
	at org.eclipse.epp.internal.mpc.ui.catalog.MarketplaceCatalog.installed(MarketplaceCatalog.java:106)
	at org.eclipse.epp.internal.mpc.ui.wizards.MarketplaceViewer.lambda$6(MarketplaceViewer.java:681)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
"

**Comment by martinlippert** [comment]
@MarcoSchool Reading the follow-up comments above, can you provide more details?
