### ISSUE TITLE
Request textDocument/inlayHint failed

### ISSUE THREAD

**Issue by Ki10V01T** [spring-projects/sts4#1359]
Version of Spring Boot Tools is v1.57.0

Hello, colleagues.
I recently ran into a problem. Your extension displays a message in the lower right corner of the vscode window about the problems that are occurring. Changing any settings has no effect.

Nothing needs to be done to reproduce the problem. Just write code.

Below is a stack trace about the problem that has occurred.

```
Activating 'vscode-spring-boot' extension
"spring-boot.ls.java.home" setting not specified or empty value
Found java executable: /home/dimidrol/.vscode/extensions/redhat.java-1.35.0-linux-x64/jre/17.0.12-linux-x86_64/bin/java
isJavaEightOrHigher => true
Redirecting server logs to /dev/null
Disabling server log output. No more output will be sent after this.
[Error - 4:00:50 PM] Request textDocument/inlayHint failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "org.springframework.ide.vscode.commons.languageserver.util.InlayHintHandler.handle(org.springframework.ide.vscode.commons.util.text.TextDocument, org.eclipse.lsp4j.Range, org.eclipse.lsp4j.jsonrpc.CancelChecker)" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "org.springframework.ide.vscode.commons.languageserver.util.InlayHintHandler.handle(org.springframework.ide.vscode.commons.util.text.TextDocument, org.eclipse.lsp4j.Range, org.eclipse.lsp4j.jsonrpc.CancelChecker)" is null
	at org.springframework.ide.vscode.commons.languageserver.composable.CompositeLanguageServerComponents$5.lambda$handle$2(CompositeLanguageServerComponents.java:184)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.springframework.ide.vscode.commons.languageserver.composable.CompositeLanguageServerComponents$5.handle(CompositeLanguageServerComponents.java:185)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleTextDocumentService.lambda$inlayHint$19(SimpleTextDocumentService.java:587)
	... 5 more

[Error - 4:00:52 PM] Request textDocument/inlayHint failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "org.springframework.ide.vscode.commons.languageserver.util.InlayHintHandler.handle(org.springframework.ide.vscode.commons.util.text.TextDocument, org.eclipse.lsp4j.Range, org.eclipse.lsp4j.jsonrpc.CancelChecker)" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "org.springframework.ide.vscode.commons.languageserver.util.InlayHintHandler.handle(org.springframework.ide.vscode.commons.util.text.TextDocument, org.eclipse.lsp4j.Range, org.eclipse.lsp4j.jsonrpc.CancelChecker)" is null
	at org.springframework.ide.vscode.commons.languageserver.composable.CompositeLanguageServerComponents$5.lambda$handle$2(CompositeLanguageServerComponents.java:184)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.springframework.ide.vscode.commons.languageserver.composable.CompositeLanguageServerComponents$5.handle(CompositeLanguageServerComponents.java:185)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleTextDocumentService.lambda$inlayHint$19(SimpleTextDocumentService.java:587)
	... 5 more

```

**Comment by BoykoAlex** [comment]
Hope fully fixed with 88d357f45e58fe01a30ec2808b3c137adbb5b925. There should be a snapshot build available within an hour form now on this page: https://cdn.spring.io/spring-tools/snapshot/STS4/nightly-distributions.html (VSIXs on the bottom). Otherwise pre-release on Tuesday morning will be available.

**Comment by Ki10V01T** [comment]
Thank you for your prompt response!) In that case, I will wait for the next update.
It's just that this particular problem has been haunting for the last two versions

**Comment by OrlandPy** [comment]
Just in case it helps someone...

I was having the same problem with my spring-boot extension in vs code. I fixed it adding the next config in my vscode's settings.json file
`"spring-boot.ls.java.home": "$env:JAVA_HOME\\bin\\java.exe"`

![image](https://github.com/user-attachments/assets/1bc02b65-17d5-4bd5-bbce-a37bd080922d)

I used my JAVA_HOME env, because sometimes I need to work with legacys projects with a diferent java version and I did not want to edit this configuration every time. Only the env var and I am ready to go

**Comment by martinlippert** [comment]
@OrlandPy The preference `spring-boot.ls.java.home` is unrelated to the Java runtime and version that you use for your projects. It is the JVM that is used to run the language server process behind the scenes and it has to be a JDK 21 or newer. The language server will not work properly if you specify "random" JDKs that you use for your projects, so please configure this preference to point to a specific JDK 21 - in case you need this preference at all.
