### ISSUE TITLE
`NoSuchFileException` beim AdHocSpringPropertyProvider

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#1404]
Seen this from under the hood while testing new annotation location information:

```
java.nio.file.NoSuchFileException: /Users/martinlippert/Engineering/demos/cli-ai/demo/src/test/resources
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3918)
	at java.base/java.nio.file.Files.walk(Files.java:3973)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.getIndexFromSourceFolder(AdHocSpringPropertyIndexProvider.java:121)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.lambda$5(AdHocSpringPropertyIndexProvider.java:109)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.lambda$4(AdHocSpringPropertyIndexProvider.java:108)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.getIndex(AdHocSpringPropertyIndexProvider.java:106)
	at org.springframework.ide.vscode.boot.java.conditionals.ConditionalOnPropertyCompletionProcessor.findProperties(ConditionalOnPropertyCompletionProcessor.java:72)
	at org.springframework.ide.vscode.boot.java.conditionals.ConditionalOnPropertyCompletionProcessor.getCompletionCandidates(ConditionalOnPropertyCompletionProcessor.java:57)
	at org.springframework.ide.vscode.boot.java.annotations.AnnotationAttributeCompletionProcessor.createCompletionProposals(AnnotationAttributeCompletionProcessor.java:136)
	at org.springframework.ide.vscode.boot.java.annotations.AnnotationAttributeCompletionProcessor.provideCompletions(AnnotationAttributeCompletionProcessor.java:71)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaCompletionEngine.collectCompletionsForAnnotations(BootJavaCompletionEngine.java:117)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaCompletionEngine.lambda$0(BootJavaCompletionEngine.java:59)
	at org.springframework.ide.vscode.boot.java.utils.CompilationUnitCache.withCompilationUnit(CompilationUnitCache.java:236)
	at org.springframework.ide.vscode.boot.java.utils.CompilationUnitCache.withCompilationUnit(CompilationUnitCache.java:196)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaCompletionEngine.getCompletions(BootJavaCompletionEngine.java:53)
	at org.springframework.ide.vscode.commons.languageserver.completion.CompositeCompletionEngine.getCompletions(CompositeCompletionEngine.java:62)
	at org.springframework.ide.vscode.commons.languageserver.completion.VscodeCompletionEngineAdapter.getCompletions(VscodeCompletionEngineAdapter.java:216)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleTextDocumentService.lambda$2(SimpleTextDocumentService.java:306)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.nio.file.NoSuchFileException: /Users/martinlippert/Engineering/demos/cli-ai/demo/target/generated-sources/annotations
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3918)
	at java.base/java.nio.file.Files.walk(Files.java:3973)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.getIndexFromSourceFolder(AdHocSpringPropertyIndexProvider.java:121)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.lambda$5(AdHocSpringPropertyIndexProvider.java:109)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.lambda$4(AdHocSpringPropertyIndexProvider.java:108)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.getIndex(AdHocSpringPropertyIndexProvider.java:106)
	at org.springframework.ide.vscode.boot.java.conditionals.ConditionalOnPropertyCompletionProcessor.findProperties(ConditionalOnPropertyCompletionProcessor.java:72)
	at org.springframework.ide.vscode.boot.java.conditionals.ConditionalOnPropertyCompletionProcessor.getCompletionCandidates(ConditionalOnPropertyCompletionProcessor.java:57)
	at org.springframework.ide.vscode.boot.java.annotations.AnnotationAttributeCompletionProcessor.createCompletionProposals(AnnotationAttributeCompletionProcessor.java:136)
	at org.springframework.ide.vscode.boot.java.annotations.AnnotationAttributeCompletionProcessor.provideCompletions(AnnotationAttributeCompletionProcessor.java:71)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaCompletionEngine.collectCompletionsForAnnotations(BootJavaCompletionEngine.java:117)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaCompletionEngine.lambda$0(BootJavaCompletionEngine.java:59)
	at org.springframework.ide.vscode.boot.java.utils.CompilationUnitCache.withCompilationUnit(CompilationUnitCache.java:236)
	at org.springframework.ide.vscode.boot.java.utils.CompilationUnitCache.withCompilationUnit(CompilationUnitCache.java:196)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaCompletionEngine.getCompletions(BootJavaCompletionEngine.java:53)
	at org.springframework.ide.vscode.commons.languageserver.completion.CompositeCompletionEngine.getCompletions(CompositeCompletionEngine.java:62)
	at org.springframework.ide.vscode.commons.languageserver.completion.VscodeCompletionEngineAdapter.getCompletions(VscodeCompletionEngineAdapter.java:216)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleTextDocumentService.lambda$2(SimpleTextDocumentService.java:306)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
java.nio.file.NoSuchFileException: /Users/martinlippert/Engineering/demos/cli-ai/demo/target/generated-test-sources/test-annotations
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3918)
	at java.base/java.nio.file.Files.walk(Files.java:3973)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.getIndexFromSourceFolder(AdHocSpringPropertyIndexProvider.java:121)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.lambda$5(AdHocSpringPropertyIndexProvider.java:109)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.lambda$4(AdHocSpringPropertyIndexProvider.java:108)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at org.springframework.ide.vscode.boot.metadata.AdHocSpringPropertyIndexProvider.getIndex(AdHocSpringPropertyIndexProvider.java:106)
	at org.springframework.ide.vscode.boot.java.conditionals.ConditionalOnPropertyCompletionProcessor.findProperties(ConditionalOnPropertyCompletionProcessor.java:72)
	at org.springframework.ide.vscode.boot.java.conditionals.ConditionalOnPropertyCompletionProcessor.getCompletionCandidates(ConditionalOnPropertyCompletionProcessor.java:57)
	at org.springframework.ide.vscode.boot.java.annotations.AnnotationAttributeCompletionProcessor.createCompletionProposals(AnnotationAttributeCompletionProcessor.java:136)
	at org.springframework.ide.vscode.boot.java.annotations.AnnotationAttributeCompletionProcessor.provideCompletions(AnnotationAttributeCompletionProcessor.java:71)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaCompletionEngine.collectCompletionsForAnnotations(BootJavaCompletionEngine.java:117)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaCompletionEngine.lambda$0(BootJavaCompletionEngine.java:59)
	at org.springframework.ide.vscode.boot.java.utils.CompilationUnitCache.withCompilationUnit(CompilationUnitCache.java:236)
	at org.springframework.ide.vscode.boot.java.utils.CompilationUnitCache.withCompilationUnit(CompilationUnitCache.java:196)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaCompletionEngine.getCompletions(BootJavaCompletionEngine.java:53)
	at org.springframework.ide.vscode.commons.languageserver.completion.CompositeCompletionEngine.getCompletions(CompositeCompletionEngine.java:62)
	at org.springframework.ide.vscode.commons.languageserver.completion.VscodeCompletionEngineAdapter.getCompletions(VscodeCompletionEngineAdapter.java:216)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleTextDocumentService.lambda$2(SimpleTextDocumentService.java:306)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by martinlippert** [comment]
Fixed with https://github.com/spring-projects/sts4/commit/b5fff4e5f12cbf30121e300dd7948e1c16d43737
