### ISSUE TITLE
 Missing system library

### ISSUE THREAD

**Issue by Joshuahope** [spring-projects/sts4#1442]
project_jdk_version:1.8
spring_tool_jdk_version:21
errorMeg:
15:31:16.457 [pool-5-thread-1] ERROR o.s.i.v.boot.app.SpringSymbolIndex - SpringIndexerJava threw exception
java.lang.IllegalStateException: Missing system library
	at org.eclipse.jdt.core.dom.ASTParser.checkForSystemLibrary(ASTParser.java:311)
	at org.eclipse.jdt.core.dom.ASTParser.getClasspath(ASTParser.java:272)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:1107)
	at org.springframework.ide.vscode.boot.java.utils.ASTParserCleanupEnabled.createASTs(ASTParserCleanupEnabled.java:91)
	at org.springframework.ide.vscode.boot.java.utils.SpringIndexerJava.scanFiles(SpringIndexerJava.java:590)
	at org.springframework.ide.vscode.boot.java.utils.SpringIndexerJava.scanFiles(SpringIndexerJava.java:519)
	at org.springframework.ide.vscode.boot.java.utils.SpringIndexerJava.initializeProject(SpringIndexerJava.java:162)
	at org.springframework.ide.vscode.boot.app.SpringSymbolIndex$InitializeProject.run(SpringSymbolIndex.java:897)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
error_branch:pre_release
normal_branch:1.59.0
the_consequences_of_errors:Unable to use API navigation

**Comment by martinlippert** [comment]
This happens when using VSCode? Does the output for the spring boot tools reveal which exact JDK is being found for running the Spring Tools? And does this happen with every project or just specific ones?

**Comment by BoykoAlex** [comment]
Occurs for a project with compliance level Java 1.8 with JRE 1.8 on the classpath. By default the compliance level is set to Java 21. JDT parser checks the classpath for sys libs throws exception for high compliance level with Java 1.8 on the classpath.
Fix via ad1d5d3a7e2f16dce9ce75206a00425b0e151bfa
