### ISSUE TITLE
STS4 throwing errors on startup using adoptopenjdk 11

### ISSUE THREAD

**Issue by drkknght** [spring-projects/sts4#149]
I get the following error using adoptopenjdk 11 with STS 4
 
!SESSION 2018-11-23 23:29:45.892 -----------------------------------------------
eclipse.buildId=4.0.1.201810300749-RELEASE
java.version=11.0.1
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.springframework.boot.ide.branding.sts4
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springframework.boot.ide.branding.sts4

!ENTRY org.eclipse.osgi 4 0 2018-11-23 23:29:54.227
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Display.getMessageCount(Display.java:2029)
	at org.eclipse.swt.widgets.Display.foregroundIdleProc(Display.java:1317)
	at org.eclipse.swt.internal.win32.OS.VtblCall(Native Method)
	at org.eclipse.swt.widgets.Display.init(Display.java:2711)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:144)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:472)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:463)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:749)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:163)
	at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:185)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:128)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

**Comment by drkknght** [comment]
[1543095435007.log](https://github.com/spring-projects/sts4/files/2612606/1543095435007.log)
I get the following error

**Comment by drkknght** [comment]
Yes, this us against vanilla eclipse.

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 28, 2018 at 9:09 AM, Alex Boyko<notifications@github.com> wrote:   
Is that error from vanilla Eclipse? No STS4 involved? If yes, I'd try raising that against Eclipse platform https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform or just ask on the eclipse forum if that JDK is supported: https://www.eclipse.org/forums/

**Comment by martinlippert** [comment]
The error log that you attached for vanilla Eclipse looks like the general issues when running Eclipse on a JDK11 (independent of the vendor being Oracle or AdoptOpenJDK). But STS4 should work with a JDK11 in general, so I am wondering whether that STS4-related error is something else. It could still be grounded in a bug in the Eclipse platform though.

Can you double check a vanilla Eclipse 2018-12 milestone build to see if that makes a difference?

**Comment by martinlippert** [comment]
I tried recent builds of STS 4 again using OpenJDK versions with HotSpot and OpenJ9 VMs and everything seems to be running fine now. In case you opt-in to the OpenJ9 world, make sure to pick the large heap versions of the OpenJ9 downloads to run Eclipse/STS with.

**Comment by pcjose** [comment]
Upon running the STS4 directly from the command line, we could see this internal error when /Applications/SpringToolSuite4.app/Contents/MacOS   user1 $ ./SpringToolSuite4 
Error: could not find libjava.dylib
Failed to GetJREPath()

**Comment by kdvolder** [comment]
@pcjose While the error is not much to go on, I suspect this may be something related to how the JVM is installed on your machine and the Eclipse launcher not being able to find where it is.

Found this: https://stackoverflow.com/questions/37368603/intellij-15-error-could-not-find-libjava-dylib
So maybe read that and see if it helps at all.

Also... in my experience, when the launcher is having problem finding the JVM, or finding the wrong JVM etc. It usually helps if you edit the `STS.ini` or `eclipse.ini` file and add an explicit pointer to the JVM you intend STS to run with. To do this simply open the file with a text editor and add something like this to the front of this file:

```
-vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/java
...
```

Read more about the ini file here: https://wiki.eclipse.org/Eclipse.ini

That info refers to `eclipse.ini`. For STS the name will be `STS4.ini` or `STS.ini` but it is really the same thing.
