### ISSUE TITLE
About 'org.eclipse.equinox.internal.p2.engine.phases.CheckTrust '

### ISSUE THREAD

**Issue by mysmlz** [spring-projects/sts4#162]
Here are the logs.
##### log1
```eclipse.buildId=3.9.6.201809180749-RELEASE-e49
java.version=1.8.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -data file:/D:/workspace/ -product org.springsource.sts.ide

org.eclipse.equinox.p2.engine
错误
Fri Dec 07 17:05:30 CST 2018
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
```
##### log2
```
eclipse.buildId=3.9.6.201809180749-RELEASE-e49
java.version=1.8.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -data file:/D:/workspace/ -product org.springsource.sts.ide

org.eclipse.equinox.p2.engine
错误
Fri Dec 07 17:05:30 CST 2018
Error with signed content.

java.security.SignatureException: 处理文件签名时出现错误：D:\spring-tool-suite-3.9.6.RELEASE-e4.9.0-win32-x86_64\sts-bundle\sts-3.9.6.RELEASE\features\org.springframework.tooling.boot.ls.feature_4.0.2.201811300741
	at org.eclipse.osgi.internal.signedcontent.SignedBundleHook.getSignedContent(SignedBundleHook.java:225)
	at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.checkCertificates(CertificateChecker.java:77)
	at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.start(CertificateChecker.java:58)
	at org.eclipse.equinox.internal.p2.engine.phases.CheckTrust.completePhase(CheckTrust.java:55)
	at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:255)
	at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:105)
	at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:80)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:48)
	at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:178)
	at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:76)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:190)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.security.SignatureException: 无法验证此 jar 中签名人“META-INF/PIVOTAL.RSA”的签名：D:\spring-tool-suite-3.9.6.RELEASE-e4.9.0-win32-x86_64\sts-bundle\sts-3.9.6.RELEASE\features\org.springframework.tooling.boot.ls.feature_4.0.2.201811300741
	at org.eclipse.osgi.internal.signedcontent.PKCS7Processor.verifySFSignature(PKCS7Processor.java:425)
	at org.eclipse.osgi.internal.signedcontent.SignatureBlockProcessor.processSigner(SignatureBlockProcessor.java:101)
	at org.eclipse.osgi.internal.signedcontent.SignatureBlockProcessor.process(SignatureBlockProcessor.java:65)
	at org.eclipse.osgi.internal.signedcontent.SignedBundleFile.initializeSignedContent(SignedBundleFile.java:47)
	at org.eclipse.osgi.internal.signedcontent.SignedBundleHook.getSignedContent(SignedBundleHook.java:221)
	... 12 more

```
##### log3
```
eclipse.buildId=3.9.6.201809180749-RELEASE-e49
java.version=1.8.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -product org.springsource.sts.ide -data file:/D:/workspace/ -product org.springsource.sts.ide

org.eclipse.equinox.p2.engine
错误
Fri Dec 07 17:05:30 CST 2018
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
```

**Comment by mysmlz** [comment]
em,Maybe Chinese doesn't affect reading.

**Comment by martinlippert** [comment]
When does this happen? Looks like you are trying to install SpringTools4 into an existing Eclipse installation. Is that correct?

This works for me, so in case I am right here there must be something different on your machine. Maybe the download got corrupted or your machine has trouble verifying the signature of that JAR file. What happens if you copy the mentioned JAR of the bundle to a temporary location and run `jarsigner -verify` on it?

**Comment by mysmlz** [comment]
**When it is automatically updated**
![image](https://user-images.githubusercontent.com/38951157/50038354-5898a980-0059-11e9-98dc-e2374297d2c1.png)
**Then I click "next","next",.... and "finish",then **
![image](https://user-images.githubusercontent.com/38951157/50038360-749c4b00-0059-11e9-997b-891cddb326f7.png)

(and "spring quick search" is ok)

**Comment by mysmlz** [comment]
**some configurations:**
```
applicationXMI=org.eclipse.ui.workbench/LegacyIDE.e4xmi
awt.toolkit=sun.awt.windows.WToolkit
com.genuitec.eclipse.theming.ui.isDark=false
com.genuitec.eclipse.theming.ui.isDevStyle=false
ds.delayed.keepInstances=true
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=3.9.6.201809180749-RELEASE-e49
eclipse.commands=-os
win32
-ws
win32
-arch
x86_64
-showsplash
-launcher
D:\spring-tool-suite-3.9.6.RELEASE-e4.9.0-win32-x86_64\sts-bundle\sts-3.9.6.RELEASE\STS.exe
-name
STS
--launcher.library
D:\spring-tool-suite-3.9.6.RELEASE-e4.9.0-win32-x86_64\sts-bundle\sts-3.9.6.RELEASE\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.800.v20180827-1352\eclipse_1705.dll
-startup
D:\spring-tool-suite-3.9.6.RELEASE-e4.9.0-win32-x86_64\sts-bundle\sts-3.9.6.RELEASE\\plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar
--launcher.overrideVmargs
-product
org.springsource.sts.ide
-vm
D:\jre8\bin\server\jvm.dll
eclipse.home.location=file:/D:/spring-tool-suite-3.9.6.RELEASE-e4.9.0-win32-x86_64/sts-bundle/sts-3.9.6.RELEASE/
eclipse.launcher=D:\spring-tool-suite-3.9.6.RELEASE-e4.9.0-win32-x86_64\sts-bundle\sts-3.9.6.RELEASE\STS.exe
eclipse.launcher.name=STS
eclipse.p2.data.area=@config.dir/../p2/
eclipse.p2.profile=DefaultProfile
eclipse.product=org.springsource.sts.ide
eclipse.startTime=1544841165255
eclipse.stateSaveDelayInterval=30000
eclipse.vm=D:\jre8\bin\server\jvm.dll
eclipse.vmargs=-Dosgi.requiredJavaVersion=1.8
-Xms1024m
-Dosgi.module.lock.timeout=10
-Dorg.eclipse.swt.browser.IEVersion=10001
-Xmx2048m
-Djava.class.path=D:\spring-tool-suite-3.9.6.RELEASE-e4.9.0-win32-x86_64\sts-bundle\sts-3.9.6.RELEASE\\plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar
equinox.init.uuid=true
equinox.use.ds=true
file.encoding=GBK
```

**Comment by martinlippert** [comment]
What happens if you run the `jarsigner -verify` for that file in question? (the one that shows up in the error message)

**Comment by martinlippert** [comment]
Closing this one since we haven't got additional feedback on this. If this is still an issue, please comment and we can re-open.

**Comment by UserSina** [comment]
Download `org.eclipse.tm.terminal.connector.ssh.feature_10.2.0.202012191711.jar` from [this link](https://download.eclipse.org/justj/?file=releases/2021-03/202101151000/features
) and extract to `sts_directory\features\org.eclipse.tm.terminal.connector.ssh.feature_10.2.0.202012191711`.
