### ISSUE TITLE
Boot Properties Editor Code Completions not work

### ISSUE THREAD

**Issue by cenggel** [spring-projects/sts4#164]
spring-tool-suite-4-4.0.2.RELEASE-e4.9.0-macosx.cocoa.x86_64.dmg
spring-tool-suite-4-4.1.0.CI-B1407-e4.10.0-macosx.cocoa.x86_64.dmg
Mac osx 10.11.6
jdk 1.8

when edit .yml  Code Completions not work.

**Comment by BoykoAlex** [comment]
I'm working with exactly the same CI build on mac OSX: `spring-tool-suite-4-4.1.0.CI-B1407-e4.10.0-macosx.cocoa.x86_64.dmg`

Code completions work for me when i edit `application.yml`.
Is your file names `application.yml` and located under `src/main/resources` in your boot maben project?
Did you open the `application.yml` file with __Generic Editor__:
![screen shot 2018-12-11 at 21 49 21](https://user-images.githubusercontent.com/6433390/49843959-03c20e00-fd8f-11e8-83d4-b06265722a77.png)

**Comment by cenggel** [comment]
Yes, I did it but code completion not appeared.

![image](https://user-images.githubusercontent.com/6281382/49909903-b7282100-febb-11e8-9219-d3fcc9f84d4c.png)

![image](https://user-images.githubusercontent.com/6281382/49910035-33baff80-febc-11e8-9a03-f9d400115651.png)

sts3.9.2 completion works fine 

![image](https://user-images.githubusercontent.com/6281382/49910095-695fe880-febc-11e8-9bb7-bcd68d8aa7c4.png)

How can I check what wrong for my environment ?

**Comment by BoykoAlex** [comment]
Close STS4
Run `jps` command in the console
Check if you have any processes like that: 
`29173 1.1.0.201810300740-spring-boot-language-server-1.1.0-SNAPSHOT.jar`
Kill them manually: `kill -6 <pid>`
Open STS
Close all editors
Open preferences and check-mark Spring Boot here:
![screen shot 2018-12-12 at 21 09 22](https://user-images.githubusercontent.com/6433390/49910851-439df980-fe52-11e8-83a8-b09a82dbd4ef.png)

Open the YAML and try content assists again
The console view would show the language server log. If CA is not working still attach the contents of the console view here.
Also check for various lsp4e or sts errors in the error view.

**Comment by cenggel** [comment]
console log :

```11:33:11.738 [main] INFO  o.s.i.v.b.a.BootLanguagServerBootApp - Starting BootLanguagServerBootApp v1.2.0-SNAPSHOT on tsings-MacBook-Pro.local with PID 32886 (/Applications/SpringToolSuite4.app/Contents/Eclipse/configuration/org.eclipse.osgi/526/data/1.2.0.201812112357-spring-boot-language-server-1.2.0-SNAPSHOT.jar started by tsing in /Applications/SpringToolSuite4.app/Contents/MacOS)
11:33:11.742 [main] INFO  o.s.i.v.b.a.BootLanguagServerBootApp - No active profile set, falling back to default profiles: default
11:33:11.817 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@387c703b: startup date [Thu Dec 13 11:33:11 CST 2018]; root of context hierarchy
11:33:12.604 [main] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
11:33:13.869 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
11:33:13.893 [main] INFO  o.s.i.v.b.a.BootLanguagServerBootApp - Started BootLanguagServerBootApp in 3.209 seconds (JVM running for 4.121)
11:33:13.896 [LanguageServerApp-lifecycle] INFO  o.s.i.v.c.l.LanguageServerRunner - Server ready to start after 4125 ms
11:33:13.899 [LanguageServerApp-lifecycle] INFO  o.s.ide.vscode.commons.util.Log - Starting LS
11:33:13.900 [LanguageServerApp-lifecycle] INFO  o.s.ide.vscode.commons.util.Log - Connected to parent using stdio
11:33:14.013 [pool-3-thread-1] INFO  o.s.i.v.c.l.u.SimpleLanguageServer - Initializing
11:33:14.028 [pool-3-thread-1] INFO  o.s.i.v.c.l.u.SimpleLanguageServer - Returning server capabilities to client: ServerCapabilities [
  textDocumentSync = Either [
    left = Incremental
    right = null
  ]
  hoverProvider = true
  completionProvider = CompletionOptions [
    resolveProvider = true
    triggerCharacters = null
  ]
  signatureHelpProvider = null
  definitionProvider = true
  typeDefinitionProvider = null
  implementationProvider = null
  referencesProvider = true
  documentHighlightProvider = true
  documentSymbolProvider = true
  workspaceSymbolProvider = true
  codeActionProvider = null
  codeLensProvider = CodeLensOptions [
    resolveProvider = false
  ]
  documentFormattingProvider = null
  documentRangeFormattingProvider = null
  documentOnTypeFormattingProvider = null
  renameProvider = null
  documentLinkProvider = null
  colorProvider = null
  executeCommandProvider = null
  workspace = WorkspaceServerCapabilities [
    workspaceFolders = WorkspaceFoldersOptions [
      supported = true
      changeNotifications = Either [
        left = 2c8c4fa1-bd9c-428b-b176-cb967426fa16
        right = null
      ]
    ]
  ]
  experimental = null
]
11:33:14.113 [SimpleLanguaserver main thread] INFO  o.s.i.v.c.l.u.SimpleLanguageServer - Initialization completed after 4341 ms
11:33:16.093 [pool-3-thread-1] WARN  o.e.lsp4j.jsonrpc.RemoteEndpoint - Unmatched cancel notification for request id 4
11:33:19.165 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Project Created: file:/Users/tsing/Documents/workspace-spring-tool-suite-4-4.10/demo-2
11:33:19.169 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Classpath has 76 entries 32 source attachements
11:33:19.170 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.a.BootLanguageServerInitializer - A project changed demo-2, triggering reconcile on all open documents
11:33:19.213 [Reconciler-1] INFO  o.s.ide.vscode.commons.util.Log - Indexing Spring Boot Properties for demo-2
11:33:19.247 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Project Created: file:/Users/tsing/Documents/workspace-spring-tool-suite-4-4.10/demo
11:33:19.253 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Classpath has 84 entries 56 source attachements
11:33:19.253 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.a.BootLanguageServerInitializer - A project changed demo, triggering reconcile on all open documents
11:33:19.605 [Reconciler-1] INFO  o.s.ide.vscode.commons.util.Log - Indexing Spring Boot Properties for demo-2 DONE
11:33:19.605 [Reconciler-1] INFO  o.s.ide.vscode.commons.util.Log - Indexed 1007 properties.
```

jps :
`32886 1.2.0.201812112357-spring-boot-language-server-1.2.0-SNAPSHOT.jar`

**Comment by cenggel** [comment]
have error log

**Comment by BoykoAlex** [comment]
Did you launch your STS with Java 11? Do you have any errors on you project?
I'd make sure that STS is launched with Java 8 and when you run `Maven -> Update Project...` action non errors on the project shown.
If you have any errors with your project classpath then STS4 tooling may not recognize your project as Spring Boot project and hence there won't be any content assists or any other features working with the Boot properties YAML file

**Comment by cenggel** [comment]
STS launched by java 8 

![image](https://user-images.githubusercontent.com/6281382/50065493-c4ae1580-01f1-11e9-8389-e333d864c1a3.png)

and not have any errors for project.

![image](https://user-images.githubusercontent.com/6281382/50065606-603f8600-01f2-11e9-85b8-e07b10d2ea63.png)

Which version of java 8 you used? 
My java version is :
```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
```

**Comment by BoykoAlex** [comment]
This is old JDK. Try use the latest JDK. Mine is not latest, quite old, but it's 1.8.0_151

**Comment by cenggel** [comment]
I upgrade jdk to `java version "1.8.0_191"`  reinstall my sts4  create new workspace  and new boot project . But nothing changed . Code completions also not work for me.

**Comment by martinlippert** [comment]
@cenggel this is really strange, since everything looks like it should just work... :-( What happens if you create and open a file called `application.properties` in your demo project and open that? Is content-assist showing up there?

**Comment by cenggel** [comment]
@martinlippert  edit `application.properties` in my demo project content-assist not showing up  too .

**Comment by martinlippert** [comment]
Can you paste the content of your SpringTools4.ini file? Just guessing around, since I am running out of ideas here.

**Comment by martinlippert** [comment]
I also tried your demo project with the latest STS4 CI distribution build and the content-assist shows up just fine for the `application.yml` file. It takes a while when you invoke it for the first time, since it indexes stuff from the classpath, but it works. Maybe something is timing out in your case.

From what I can observe is that the log output from the language server (once you enabled that in the preferences), it shows additional output right after you hit content-assist for the first time in that application.yml file. Can you double check that? Maybe with a fresh STS4 install from the CI builds at http://dist.springsource.com/snapshot/STS4/nightly-distributions.html, using the latest version on Eclipse 4.10? Can you try that?

I am sorry for this taking so long to debug, seems like a really strange and hard-to-diagnose issue...

**Comment by martinlippert** [comment]
And thanks for all your patience... :-)

**Comment by cenggel** [comment]
Thanks for your replay .

This is my spring-tool-suite-4-4.0.2.RELEASE-e4.9.0-macosx.cocoa.x86_64 `SpringToolSuite4.ini`
```
-startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.5.100.v20180827-1352.jar
--launcher.library
../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.800.v20180827-1352
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vmargs
-Dosgi.requiredJavaVersion=1.8
--add-modules=ALL-SYSTEM
-Xms40m
-XstartOnFirstThread
-Dorg.eclipse.swt.internal.carbon.smallFonts
-Xdock:icon=../Resources/sts4.icns
-Xmx1200m
```

I installed new eclipse 2018-12 and sts from [http://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.10](http://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.10)
but still not work .

I had tried spring-tool-suite-4-4.1.0.CI-B1426-e4.9.0-macosx.cocoa.x86_64.dmg  spring-tool-suite-4-4.0.2.RELEASE-e4.9.0-macosx.cocoa.x86_64.dmg  all  content-assist not showing up .

**Comment by BoykoAlex** [comment]
What happens if you enter string value for `server.port=qqqq` in properties or whatever it translates to yaml... do you get the red squiggly line under "qqqq"?
Do you see the live hints when If you start your demo boot app? `@SpringBootApplication` gets greenish background in the Java editor, if you hover over it you'd get some info about live running app. Does this work? Just curious if it is just the CA or everything...
Also, I'm very curious if it all works with VSCode rather than Eclipse on your system. Are you familiar with VSCode? It has the same Spring Boot extension that will allow to edit `application.yml` and `application.properties` files... 
https://code.visualstudio.com/download
Once downloaded, open it, then open the `demo` project folder via `File` menu.
Note the vertical toolbar on the left. The bottom button is extensions. Click it. Type `spring boot` in the text box. The first 2 extensions in the list would be: `Spring Boot Tools` and `Spring Boot Extension Pack` (the second has a number of extensions including the first one). Once installed VSCode would prompt you to reload the window. Reload it. Then open the `applicationn.yml` and try to work with it.

**Comment by cenggel** [comment]
`server.port: aaa` can get red squiggly line under "aaa" . like below

![image](https://user-images.githubusercontent.com/6281382/50269577-9f2b4100-0469-11e9-87ab-480eae011ace.png)

I can't see live hints when I start my project. 
![image](https://user-images.githubusercontent.com/6281382/50269707-1cef4c80-046a-11e9-830d-0733815978af.png)

**Comment by cenggel** [comment]
I download vscode and install spring boot tools , when edit yaml  file have  validation but content-assist can't shown up .

When start project live application information hovers can't work .

It is my os problem ?

![image](https://user-images.githubusercontent.com/6281382/50271879-13b5ae00-0471-11e9-87e4-303f88edd457.png)

**Comment by BoykoAlex** [comment]
Maybe it has to do something with the OS... but at first sight it looks like the language server process works for some features like linting and not working for others like content assists...
One more thing to try in Eclipse STS: Press `Cmd-6`. This should produce a list of Spring workspace symbols (beans, request mappings, various annotations). Do you see stuff from your demo project in that list?

Unfortunately, so far it seems like some debugging on your system would be necessary to get to the bottom of this... We'd have to come up with instructions for you... Think the easiest would be debugging Language Server with VSCode...

**Comment by kdvolder** [comment]
Live hovers not working may be because they require spring-boot-actuator on the project. But this is not the case for content assist, that should work regardless.

What is really puzzling here is that you get the squigly line and information hover for the properties. This means that the property metadata is definitely known to the language server meaning it seems to be all working fine in that regards. But the content-assist, which is based on the same information, does not work. Now that is strange.

Perhaps it might be a thread that is 'stuck' in a deadlock or something like that. If you could try to use `jps` and `jstack` to collect a stacktrace from the language server process and attach it here maybe it can show something interesting. 

If you use jps you can get a list of java processes. The language server will look something like this:

```
32188 1.2.0.201812192021-spring-boot-language-server-1.2.0-SNAPSHOT.jar
```

Note the process-id (`32188` here). Then run command `jstack 32188`.

**Comment by cenggel** [comment]
Cmd＋6 quick navigating spring symbols both working on eclipse and vscode .

I have add the `spring-boot-actuator` in pom.xml . When I not added `spring-boot-actuator`  dependency mouse hover on `@SpringBootApplication` have hint to say live hint need `spring-boot-actuator` .
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-actuator</artifactId>
</dependency>
```

language server jstack is :
```
2018-12-21 08:58:13
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode):

"pool-2-thread-1" #24 prio=5 os_prio=31 tid=0x00007fdda75f4000 nid=0x1507 waiting on condition [0x0000700001b67000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007806547b0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"parallel-2" #23 daemon prio=5 os_prio=31 tid=0x00007fdda76a5000 nid=0x6103 waiting on condition [0x0000700001a64000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007808bd6c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"elastic-2" #22 daemon prio=5 os_prio=31 tid=0x00007fdda3fbf000 nid=0x5f03 waiting on condition [0x0000700001961000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007808be8b8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"parallel-1" #21 daemon prio=5 os_prio=31 tid=0x00007fdda374d000 nid=0x3507 waiting on condition [0x000070000185e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007808bdb68> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Attach Listener" #20 daemon prio=9 os_prio=31 tid=0x00007fdda30fc000 nid=0x5d03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Reconciler-1" #19 daemon prio=5 os_prio=31 tid=0x00007fdda673c800 nid=0x5b03 waiting on condition [0x0000700001658000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007803cab60> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"elastic-evictor-1" #18 daemon prio=5 os_prio=31 tid=0x00007fdda528f800 nid=0x5903 waiting on condition [0x0000700001555000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007808bf188> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Timer-0" #17 prio=5 os_prio=31 tid=0x00007fdda60c0000 nid=0x5703 in Object.wait() [0x0000700001452000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000078067c398> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x000000078067c398> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"SimpleLanguaserver main thread" #16 daemon prio=5 os_prio=31 tid=0x00007fdda3bea800 nid=0x5503 waiting on condition [0x000070000134f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000780495ba0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-3-thread-1" #15 prio=5 os_prio=31 tid=0x00007fdda7226800 nid=0x5303 runnable [0x000070000124c000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	- locked <0x00000007800f4738> (a java.io.BufferedInputStream)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:75)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"DestroyJavaVM" #14 prio=5 os_prio=31 tid=0x00007fdda5f64800 nid=0x1703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"LanguageServerApp-lifecycle" #13 prio=5 os_prio=31 tid=0x00007fdda5ec1800 nid=0x510b waiting on condition [0x0000700001149000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000780adca48> (a java.util.concurrent.FutureTask)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor$1.get(ConcurrentMessageProcessor.java:44)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor$1.get(ConcurrentMessageProcessor.java:40)
	at org.springframework.ide.vscode.commons.languageserver.LanguageServerRunner.startAsClient(LanguageServerRunner.java:139)
	at org.springframework.ide.vscode.commons.languageserver.LanguageServerRunner.start(LanguageServerRunner.java:94)
	at org.springframework.ide.vscode.commons.languageserver.LanguageServerRunner.lambda$run$0(LanguageServerRunner.java:61)
	at org.springframework.ide.vscode.commons.languageserver.LanguageServerRunner$$Lambda$265/1634132079.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x00007fdda3000800 nid=0x4903 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fdda202e800 nid=0x4703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fdda202e000 nid=0x4503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fdda3844000 nid=0x4303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fdda3858800 nid=0x3713 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fdda2027000 nid=0x3003 in Object.wait() [0x000070000092e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000780008e98> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x0000000780008e98> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fdda2004000 nid=0x2e03 in Object.wait() [0x000070000082b000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000780008ed8> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x0000000780008ed8> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=31 tid=0x00007fdda383e000 nid=0x2c03 runnable

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007fdda3803800 nid=0x2403 runnable

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007fdda2810800 nid=0x2603 runnable

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007fdda2811800 nid=0x2803 runnable

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007fdda3002800 nid=0x2a03 runnable

"VM Periodic Task Thread" os_prio=31 tid=0x00007fdda2832000 nid=0x4b03 waiting on condition

JNI global references: 979
```

**Comment by kdvolder** [comment]
Nothing suspicious looking in the stack dump. So unfortunately that didn't help :-(

I'm thinking something may be wrong on the Eclipse side. I suspect something to do with how lsp4e enables functionality based on document content types. I vaguely remember in the past that reconcile don't follow the same rules as completions and hovers. Is your file called 'applition.yml' or is it something else like 'application-development.yml'?

**Comment by cenggel** [comment]
@kdvolder  I tried `application.yml` `application-dev.yml` `bootstrap.yml` .

eclipse config:

![image](https://user-images.githubusercontent.com/6281382/50389743-ee72b980-0768-11e9-9235-cf9ad11bc9ac.png)

![image](https://user-images.githubusercontent.com/6281382/50389791-9092a180-0769-11e9-9a71-34e505813d99.png)

**Comment by martinlippert** [comment]
OK, maybe this is a stupid thought, but are you talking about content-assist not showing up AUTOMATICALLY while typing something or after typing `.` ?!?

That happens in STS3, but not in the STS4 editors. In the STS4 editors you have to invoke the content-assist manually by pressing `CTRL+Space`. Are you talking about this difference?

**Comment by cenggel** [comment]
@martinlippert  Thanks for your replay!  I found the content-assist showing up key is not `CTRL+Space` , in my eclipse default binding to  `ALT+/`  so when press `CTRL+Space`  can't showing content-assist.

How to AUTOMATICALLY showing up content-assist in the STS4 editors ？It is possible ?

**Comment by martinlippert** [comment]
@cenggel Just to verify, you can get content-assist to show up for property files on your end by using the content-assist key binding that is configured on your install, right?

If so, we should close this issue and open a new one for the "show content-assist automatically", which should certainly be possible to implement. Agree?

**Comment by martinlippert** [comment]
Ok, great, will close this one and opened another one for the automatic content-assist here: https://github.com/spring-projects/sts4/issues/182
