### ISSUE TITLE
not support spring-base project yet?

### ISSUE THREAD

**Issue by user20161119** [spring-projects/sts4#203]
```
Spring Tool Suite 4 

Version: 4.1.2.RELEASE
Build Id: 201902210640
```

just tried the new version spring tool suite,not support spring4 based project yet? i checked the change log said integrate tomcat and support spring-based project

> Eclipse) STS4 distribution now includes m2e-wtp extensions by default, allowing war-packaged Spring (Boot) projects to be deployed to a local Tomcat installation via the Servers integration in Eclipse (#154)

tomcat start up error

````
二月 23, 2019 9:24:39 下午 org.apache.tomcat.util.digester.SetPropertiesRule begin
警告: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.jee.server:ec-api' did not find a matching property.
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Server version:        Apache Tomcat/8.5.31
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Server built:          Apr 27 2018 20:24:25 UTC
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Server number:         8.5.31.0
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: OS Name:               Windows 10
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: OS Version:            10.0
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Architecture:          amd64
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Java Home:             C:\work\devTools\jdk1.8.0_171\jre
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: JVM Version:           1.8.0_171-b11
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: JVM Vendor:            Oracle Corporation
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: CATALINA_BASE:         C:\work\workspace4.0\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: CATALINA_HOME:         C:\work\devTools\apache-tomcat-8.5.31
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:56473
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -javaagent:C:\work\devTools\sts-4.0.1.RELEASE\configuration\org.eclipse.osgi\801\0\.cp\lib\javaagent-shaded.jar
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -Dcatalina.base=C:\work\workspace4.0\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -Dcatalina.home=C:\work\devTools\apache-tomcat-8.5.31
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -Dwtp.deploy=C:\work\workspace4.0\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -Djava.endorsed.dirs=C:\work\devTools\apache-tomcat-8.5.31\endorsed
二月 23, 2019 9:24:39 下午 org.apache.catalina.startup.VersionLoggerListener log
信息: Command line argument: -Dfile.encoding=GBK
二月 23, 2019 9:24:39 下午 org.apache.catalina.core.AprLifecycleListener lifecycleEvent
信息: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [C:\work\devTools\jdk1.8.0_171\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:/work/devTools/jdk1.8.0_171/bin/../jre/bin/server;C:/work/devTools/jdk1.8.0_171/bin/../jre/bin;C:/work/devTools/jdk1.8.0_171/bin/../jre/lib/amd64;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\work\devTools\jdk1.8.0_171\bin;C:\work\devTools\Git\cmd;C:\work\devTools\apache-maven-3.5.4\bin;C:\work\devTools\jdk1.8.0_171\jre\bin;C:\work\devTools\TortoiseSVN\bin;C:\work\devTools\sqlplus\instantclient_12_2;;C:\WINDOWS\System32\OpenSSH\;C:\work\devTools\TortoiseGit\bin;C:\work\devTools\nodejs\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\work\devTools\sts-4.0.1.RELEASE;;.]
二月 23, 2019 9:24:39 下午 org.apache.coyote.AbstractProtocol init
信息: Initializing ProtocolHandler ["http-nio-8080"]
二月 23, 2019 9:24:40 下午 org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
信息: Using a shared selector for servlet write/read
二月 23, 2019 9:24:40 下午 org.apache.coyote.AbstractProtocol init
信息: Initializing ProtocolHandler ["ajp-nio-8009"]
二月 23, 2019 9:24:40 下午 org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
信息: Using a shared selector for servlet write/read
二月 23, 2019 9:24:40 下午 org.apache.catalina.startup.Catalina load
信息: Initialization processed in 1341 ms
二月 23, 2019 9:24:40 下午 org.apache.catalina.core.StandardService startInternal
信息: Starting service [Catalina]
二月 23, 2019 9:24:40 下午 org.apache.catalina.core.StandardEngine startInternal
信息: Starting Servlet Engine: Apache Tomcat/8.5.31
二月 23, 2019 9:24:42 下午 org.apache.jasper.servlet.TldScanner scanJars
信息: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
二月 23, 2019 9:24:42 下午 org.apache.catalina.core.StandardContext listenerStart
严重: Error configuring application listener of class [org.springframework.web.context.ContextLoaderListener]
java.lang.ClassNotFoundException: org.springframework.web.context.ContextLoaderListener
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1308)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1136)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:544)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:525)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4714)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

二月 23, 2019 9:24:42 下午 org.apache.catalina.core.StandardContext listenerStart
严重: Skipped installing application listeners due to previous error(s)
二月 23, 2019 9:24:42 下午 org.apache.catalina.core.StandardContext startInternal
严重: One or more listeners failed to start. Full details will be found in the appropriate container log file
二月 23, 2019 9:24:42 下午 org.apache.catalina.core.StandardContext startInternal
严重: Context [] startup failed due to previous errors
二月 23, 2019 9:24:42 下午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["http-nio-8080"]
二月 23, 2019 9:24:42 下午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["ajp-nio-8009"]
二月 23, 2019 9:24:42 下午 org.apache.catalina.startup.Catalina start
信息: Server startup in 2784 ms
二月 23, 2019 9:24:47 下午 org.apache.catalina.core.StandardServer await
信息: A valid shutdown command was received via the shutdown port. Stopping the Server instance.
二月 23, 2019 9:24:47 下午 org.apache.coyote.AbstractProtocol pause
信息: Pausing ProtocolHandler ["http-nio-8080"]
二月 23, 2019 9:24:48 下午 org.apache.coyote.AbstractProtocol pause
信息: Pausing ProtocolHandler ["ajp-nio-8009"]
二月 23, 2019 9:24:48 下午 org.apache.catalina.core.StandardService stopInternal
信息: Stopping service [Catalina]
二月 23, 2019 9:24:48 下午 org.apache.coyote.AbstractProtocol stop
信息: Stopping ProtocolHandler ["http-nio-8080"]
二月 23, 2019 9:24:48 下午 org.apache.coyote.AbstractProtocol stop
信息: Stopping ProtocolHandler ["ajp-nio-8009"]
二月 23, 2019 9:24:48 下午 org.apache.coyote.AbstractProtocol destroy
信息: Destroying ProtocolHandler ["http-nio-8080"]
二月 23, 2019 9:24:48 下午 org.apache.coyote.AbstractProtocol destroy
信息: Destroying ProtocolHandler ["ajp-nio-8009"]
```

**Comment by user20161119** [comment]
by the way,my project start in Spring tool suite 3 success.

**Comment by martinlippert** [comment]
would it be possible to share the project, so that we can try to reproduce? And a few steps how to reproduce, using that project?

**Comment by user20161119** [comment]
> would it be possible to share the project, so that we can try to reproduce? And a few steps how to reproduce, using that project?

it's private project can not be shared,it is simple maven web project,work well within spring tool suite 3

**Comment by user20161119** [comment]
check the project maven pom
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                             http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.yiqing.ec</groupId>
		<artifactId>ec-parent</artifactId>
		<version>1.0</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	<artifactId>ec-h5</artifactId>
	<packaging>war</packaging>

	<name>ec h5 project</name>
	
	<profiles>
		<profile>
			<id>local</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
			     <runtime.env>local</runtime.env>
			</properties>
		</profile>
		<profile>
			<id>dev</id>
			<properties>
			     <runtime.env>dev</runtime.env>
			</properties>
		</profile>
		<profile>
			<id>qa</id>
			<properties>
			     <runtime.env>qa</runtime.env>
			</properties>
		</profile>
		<profile>
			<id>stage</id>
			<properties>
			     <runtime.env>stage</runtime.env>
			</properties>
		</profile>
		
		<profile>
			<id>prod</id>
			<properties>
			     <runtime.env>prod</runtime.env>
			</properties>
		</profile>
	</profiles>
	

	<dependencies>
		<dependency>
			<groupId>com.yiqing.ec</groupId>
			<artifactId>ec-common</artifactId>
			<version>${project.version}</version>
		</dependency>
		
		<dependency>
		  <groupId>com.yiqing.core</groupId>
	       <artifactId>yiqing-core-service-api</artifactId>
		</dependency>
		
		<dependency>
				<groupId>com.yiqing.common</groupId>
				<artifactId>yiqing-common</artifactId>
		</dependency>
			
				<!-- https://mvnrepository.com/artifact/net.sf.json-lib/json-lib -->
		<dependency>
		    <groupId>net.sf.json-lib</groupId>
		    <artifactId>json-lib</artifactId>
		    <version>2.4</version>
		    <classifier>jdk15</classifier>  
		    
		</dependency>
			
		<!-- Servlet,JSP -->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>javax.servlet.jsp</groupId>
			<artifactId>jsp-api</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
		</dependency>


		<!-- Spring Framework -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<exclusions>
				<!-- Exclude Commons Logging in favor of SLF4j -->
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
		</dependency>


		<!-- Various Application Context utilities, including EhCache, JavaMail, 
			Quartz, and Freemarker integration Define this if you need any of these integrations -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-support</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
		</dependency>
		
        <dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
		</dependency>
		
        <dependency>
           <groupId>xmlpull</groupId>
           <artifactId>xmlpull</artifactId>
           <version>1.1.3.1</version>
        </dependency>
         
         <dependency>
           <groupId>commons-lang</groupId>
           <artifactId>commons-lang</artifactId>
           <version>2.4</version>
         </dependency>

		<!-- Logging -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
		</dependency>

		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</dependency>

		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<finalName>${project.artifactId}</finalName>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
				<excludes>
				    <exclude>rebel.xml</exclude>
					<exclude>dev/*</exclude>
					<exclude>qa/*</exclude>
					<exclude>local/*</exclude>
					<exclude>stage/*</exclude>
					<exclude>prod/*</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources/${runtime.env}</directory>
			</resource>
		</resources>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<archive>
						<manifestEntries>
							<app-build-time>${maven.build.timestamp}</app-build-time>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<configuration>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>

		</plugins>
	</build>
</project>
```

**Comment by martinlippert** [comment]
Hard to say what is going wrong, the pom.xml file that you provided can't be resolved locally due to a number of missing dependencies.

How does your project look like in your IDE when you import this as a Maven project into Spring Tools 4? Does the `Maven Dependencies` classpath container show up? Does it contain all the libraries that you are referring to? Or is that different compared to the project being imported into an STS3 installation?

The CNFE that I can see in the exception log that you provided above seems to indicate that this is caused by something not being deployed to the server.

**Comment by user20161119** [comment]
maven dependency is the same as in STS3
![image](https://user-images.githubusercontent.com/123967/53393452-5ba80280-39d7-11e9-856b-f64eb73b9ad9.png)

**Comment by user20161119** [comment]
i tried deploy a simple-maven-web project within tomcat8,work correctly.but not figure out why my other project not work.

**Comment by martinlippert** [comment]
Hard to say from the distance... You could take a look at the deployed app in Tomcat to see if all the necessary libs are there. Maybe something goes wrong in that area?

**Comment by user20161119** [comment]
re-download sts4 and re-config tomcat,work for the project success.thanks

**Comment by martinlippert** [comment]
Glad to hear that. And thanks for letting us know and closing this issue, much appreciated.
