### ISSUE TITLE
STS 4.2.0_RELEASE - Mint 19.1 - Session crashes on java object method call

### ISSUE THREAD

**Issue by casper5822** [spring-projects/sts4#273]
Hello,
when i click on a Java Object and the textView methods popup appears, the linux session is killed (auto logout) and goes back to login page.

My Spring4 ini file:

-startup
plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.1000.v20190125-2016
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM

-----------------------------------------------------------------------------------------------------------------------------
In the xsession-errors i get this:

Spring Tool Suite 4:10666): Gtk-CRITICAL **: 17:59:33.273: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Spring Tool Suite 4:10666): Gtk-CRITICAL **: 17:59:33.446: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Spring Tool Suite 4:10666): Gtk-CRITICAL **: 17:59:33.447: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Avviso del gestore finestre: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3c000a4 (workspace-)
Avviso del gestore finestre: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.

(Spring Tool Suite 4:10666): Gtk-CRITICAL **: 17:59:46.581: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Spring Tool Suite 4:10666): Gtk-CRITICAL **: 17:59:48.165: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Spring Tool Suite 4:10666): Gtk-CRITICAL **: 17:59:48.239: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Spring Tool Suite 4:10666): Gtk-CRITICAL **: 17:59:48.243: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(Spring Tool Suite 4:10666): Gtk-CRITICAL **: 17:59:51.980: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.springframework.tooling.boot.ls.jdt.SpringBootJavaCompletionProposalComputer.computeCompletionProposals(SpringBootJavaCompletionProposalComputer.java:55)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:336)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:340)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:334)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:291)
	at org.eclipse.jface.text.contentassist.ContentAssistant$2.lambda$0(ContentAssistant.java:2014)
	at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4795)
	at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:2013)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:2010)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:575)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.lambda$0(CompletionProposalPopup.java:505)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:500)
	at org.eclipse.jface.text.contentassist.ContentAssistant$AutoAssistListener.lambda$0(ContentAssistant.java:380)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4582)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 11 requests (11 known processed) with 0 events remaining.
Gdk-Message: 18:00:02.966: Spring Tool Suite 4: Fatal IO error 104 (Connessione interrotta dal corrispondente) on X server :0.

-----------------------------------------------------------------------------------------------------------------------------

In the STS Error log this error is present:

eclipse.buildId=4.2.0.201903290612-RELEASE
java.version=11.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=it_IT
Framework arguments:  -product org.springframework.boot.ide.branding.sts4
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.springframework.boot.ide.branding.sts4

org.eclipse.lsp4e
Error
Sat Apr 13 14:15:02 CEST 2019

java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.eclipse.lsp4e.operations.hover.LSBasedHover.getHoverInfo(LSBasedHover.java:108)
	at org.springframework.tooling.boot.ls.jdt.SpringBootJavaHoverProvider.getHoverInfo2(SpringBootJavaHoverProvider.java:43)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:167)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:133)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:169)

In the linux journal this systemd operations are displayed:

lightdm[21193]: pam_succeed_if(lightdm:auth): requirement "user ingroup nopasswdlogin" not met by user "casper"
systemd[1]: session-c7.scope: Killing process 21110 (lightdm) with signal SIGTERM.
systemd[1]: session-c7.scope: Killing process 21126 (gnome-keyring-d) with signal SIGTERM.
systemd[1]: session-c7.scope: Killing process 21129 (lightdm-greeter) with signal SIGTERM.
systemd[1]: session-c7.scope: Killing process 21134 (dbus-daemon) with signal SIGTERM.
systemd[1]: session-c7.scope: Killing process 21135 (slick-greeter) with signal SIGTERM.
systemd[1]: session-c7.scope: Killing process 21141 (dconf-service) with signal SIGTERM.
systemd[1]: session-c7.scope: Killing process 21164 (at-spi-bus-laun) with signal SIGTERM.
systemd[1]: session-c7.scope: Killing process 21169 (dbus-daemon) with signal SIGTERM.
systemd[1]: session-c7.scope: Killing process 21175 (at-spi2-registr) with signal SIGTERM.
systemd[1]: session-c7.scope: Killing process 21177 (gvfsd) with signal SIGTERM.
systemd[1]: session-c7.scope: Killing process 21184 (gvfsd-fuse) with signal SIGTERM.
systemd[1]: Stopping Session c7 of user lightdm.

Thank you for the help.
Best regards

**Comment by martinlippert** [comment]
I haven't seen this myself before, so we need to investigate this a bit. As a first step, I would like to see if the error message and the session kill is related or not. Therefore, please startup your STS4 install, go to the `Preferences -> Language Servers` and disable (uncheck) the `Spring Boot Language Server` for `Java Source File` - then restart your STS4 installation and continue as usual. Does the session still kill happen?

**Comment by casper5822** [comment]
I fixed the problem.
It is related to nvidia driver with linux Mint 19.1 and Secure Boot enabled.
When the OS starts, the nvidia drivers of my GTX 950M are not loaded, so when i call sts functions the X server crashes and Mint goes to login again.
So i turn off the Secure Boot and it works.

Thank you in advance.
Hope this will be usefull for other people.

Best regards

**Comment by martinlippert** [comment]
Ok, thanks for sharing, might indeed be useful for others. Thanks!!!
