### ISSUE TITLE
Code Completion is not working for application.properties file.

### ISSUE THREAD

**Issue by bpadhiyar4** [spring-projects/sts4#364]
!ENTRY org.springframework.tooling.ls.eclipse.commons 1 0 2019-09-09 21:26:34.912
!MESSAGE Entering DelegatingStreamConnectionProvider()

!ENTRY org.springframework.tooling.ls.eclipse.commons 1 0 2019-09-09 21:26:34.922
!MESSAGE DelegatingStreamConnectionProvider classloader = org.eclipse.osgi.internal.loader.EquinoxClassLoader@7965aa0c[org.springframework.tooling.boot.ls:1.10.0.201908130624(id=624)]

!ENTRY org.springframework.tooling.ls.eclipse.commons 1 0 2019-09-09 21:26:34.927
!MESSAGE SpringBootLanguageServer exists!

!ENTRY org.eclipse.lsp4e 4 0 2019-09-09 21:26:35.133
!MESSAGE java.util.concurrent.CancellationException
!STACK 0
java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.getCompletionProposalAutoActivationCharacters(LSContentAssistProcessor.java:250)
	at org.eclipse.jface.text.contentassist.ContentAssistant.isAutoActivationTriggerChar(ContentAssistant.java:1196)
	at org.eclipse.jface.text.contentassist.ContentAssistant$AutoAssistListener.keyPressed(ContentAssistant.java:326)
	at org.eclipse.jface.text.contentassist.ContentAssistant$AutoAssistListener.verifyKey(ContentAssistant.java:357)
	at org.eclipse.jface.text.TextViewer$VerifyKeyListenersManager.verifyKey(TextViewer.java:480)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:70)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1080)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:779)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6093)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5787)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1080)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1107)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1490)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4877)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:353)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4759)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3545)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
Caused by: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
	at org.eclipse.lsp4e.LanguageServerWrapper.stop(LanguageServerWrapper.java:379)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:199)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:612)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:514)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.collectHighlights(HighlightReconcilingStrategy.java:197)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.lambda$0(HighlightReconcilingStrategy.java:124)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.lsp4e 4 0 2019-09-09 21:26:35.135
!MESSAGE java.util.concurrent.CancellationException
!STACK 0
java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.getContextInformationAutoActivationCharacters(LSContentAssistProcessor.java:289)
	at org.eclipse.jface.text.contentassist.ContentAssistant.isAutoActivationTriggerChar(ContentAssistant.java:1200)
	at org.eclipse.jface.text.contentassist.ContentAssistant$AutoAssistListener.keyPressed(ContentAssistant.java:326)
	at org.eclipse.jface.text.contentassist.ContentAssistant$AutoAssistListener.verifyKey(ContentAssistant.java:357)
	at org.eclipse.jface.text.TextViewer$VerifyKeyListenersManager.verifyKey(TextViewer.java:480)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:70)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1080)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:779)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6093)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5787)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1080)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1107)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1490)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4877)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:353)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4759)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4770)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3545)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
Caused by: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
	at org.eclipse.lsp4e.LanguageServerWrapper.stop(LanguageServerWrapper.java:379)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:199)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:612)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:514)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.collectHighlights(HighlightReconcilingStrategy.java:197)
	at org.eclipse.lsp4e.operations.highlight.HighlightReconcilingStrategy.lambda$0(HighlightReconcilingStrategy.java:124)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.springframework.tooling.ls.eclipse.commons 1 0 2019-09-09 21:26:35.697
!MESSAGE Entering DelegatingStreamConnectionProvider()

!ENTRY org.springframework.tooling.ls.eclipse.commons 1 0 2019-09-09 21:26:35.701
!MESSAGE DelegatingStreamConnectionProvider classloader = org.eclipse.osgi.internal.loader.EquinoxClassLoader@7965aa0c[org.springframework.tooling.boot.ls:1.10.0.201908130624(id=624)]

!ENTRY org.springframework.tooling.ls.eclipse.commons 1 0 2019-09-09 21:26:35.706
!MESSAGE SpringBootLanguageServer exists!

**Comment by kdvolder** [comment]
Can you provide some context with the above wall of text? Are you experiencing a problem? If so please explain a little what your trying to do and what is not working.

**Comment by bpadhiyar4** [comment]
STS version =  4.3.2.RELEASE

**Below is the configuration**

*** Date: Monday, 9 September, 2019 at 9:32:05 pm India Standard Time

*** Platform Details:

System properties:
applicationXMI=org.eclipse.ui.workbench/LegacyIDE.e4xmi
awt.toolkit=sun.awt.windows.WToolkit
ds.delayed.keepInstances=true
ds.delayed.keepInstances.default=true
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.3.2.201908130627-RELEASE
eclipse.commands=-data
file:/C:/Users/admin/Documents/workspace-spring-tool-suite-4-4.3.2.RELEASE/
-os
win32
-ws
win32
-arch
x86_64
-showsplash
-launcher
D:\Tools\spring-tool-suite-4-4.3.2.RELEASE-e4.12.0-win32.win32.x86_64\sts-4.3.2.RELEASE\SpringToolSuite4.exe
-name
SpringToolSuite4
--launcher.library
D:\Tools\spring-tool-suite-4-4.3.2.RELEASE-e4.12.0-win32.win32.x86_64\sts-4.3.2.RELEASE\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.1000.v20190125-2016\eclipse_1801.dll
-startup
D:\Tools\spring-tool-suite-4-4.3.2.RELEASE-e4.12.0-win32.win32.x86_64\sts-4.3.2.RELEASE\\plugins/org.eclipse.equinox.launcher_1.5.400.v20190515-0925.jar
--launcher.overrideVmargs
-exitdata
d10_98
-product
org.springframework.boot.ide.branding.sts4
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-vm
C:\Program Files\Java\jdk1.8.0_181\bin\javaw.exe
eclipse.home.location=file:/D:/Tools/spring-tool-suite-4-4.3.2.RELEASE-e4.12.0-win32.win32.x86_64/sts-4.3.2.RELEASE/
eclipse.launcher=D:\Tools\spring-tool-suite-4-4.3.2.RELEASE-e4.12.0-win32.win32.x86_64\sts-4.3.2.RELEASE\SpringToolSuite4.exe
eclipse.launcher.name=SpringToolSuite4
eclipse.p2.data.area=@config.dir/../p2/
eclipse.p2.profile=DefaultProfile
eclipse.product=org.springframework.boot.ide.branding.sts4
eclipse.startTime=1568042404810
eclipse.stateSaveDelayInterval=30000
eclipse.vm=C:\Program Files\Java\jdk1.8.0_181\bin\javaw.exe
eclipse.vmargs=-jar
D:\Tools\spring-tool-suite-4-4.3.2.RELEASE-e4.12.0-win32.win32.x86_64\sts-4.3.2.RELEASE\\plugins/org.eclipse.equinox.launcher_1.5.400.v20190515-0925.jar
equinox.init.uuid=true
file.encoding=Cp1252
file.encoding.pkg=sun.io
file.separator=\
gosh.args=--nointeractive
guice.disable.misplaced.annotation.check=true
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=D:\Tools\spring-tool-suite-4-4.3.2.RELEASE-e4.12.0-win32.win32.x86_64\sts-4.3.2.RELEASE\\plugins/org.eclipse.equinox.launcher_1.5.400.v20190515-0925.jar
java.class.version=52.0
java.endorsed.dirs=C:\Program Files\Java\jdk1.8.0_181\jre\lib\endorsed
java.ext.dirs=C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext;C:\Windows\Sun\Java\lib\ext
java.home=C:\Program Files\Java\jdk1.8.0_181\jre
java.io.tmpdir=C:\Users\admin\AppData\Local\Temp\
java.library.path=C:\Program Files\Java\jdk1.8.0_181\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;E:\oracle\product\10.2.0\db_1\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Python37-32\Scripts\;C:\Program Files (x86)\Python37-32\:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_181\bin;C:\adb;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\curl;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\admin\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\admin\AppData\Local\Programs\Python\Python37-32\;C:\Program Files\Java\jdk1.8.0_181\bin;C:\Program Files (x86)\Python37-32\Scripts\;C:\Program Files (x86)\Python37-32\Scripts;C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\bin;D:\Flutter SDK\flutter\bin;C:\Users\admin\AppData\Local\Android\Sdk\tools;C:\Users\admin\AppData\Local\Android\Sdk\platform-tools;C:\Users\admin\AppData\Roaming\npm;C:\Users\admin\Downloads\solidity-windows;;C:\Users\admin\Downloads\web3j-3.6.0\web3j-3.6.0\bin;C:\Users\admin\Downloads\go-ipfs;.
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_181-b13
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.8.0_181
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.181-b13
jetty.git.hash=e1bc35120a6617ee3df052294e433f3a25ce7097

**Comment by bpadhiyar4** [comment]
> Can you provide some context with the above wall of text? Are you experiencing a problem? If so please explain a little what your trying to do and what is not working.

i am started learning spring boot everything is working fine but only the content-assits for the application.properties file is not working. Whenever i pressed ctrl + space sts given error like error in computation.

**Comment by kdvolder** [comment]
What kind of project are you using? Is there a chance you can zip up project contents and attach it to the bug report? Usually when this kind of problem happens it has something to do with some specific aspects of the project contents.

To rule out some things, can you try creating a brand new 'empty' project with "New Spring Starter Project" project wizard? Just create a project, with 'web' + 'actuator' starter dependencies. Then open its `application.properties` and see if it gives you completions. If it does than it is most likely something specific about your project that causes the problem. If it also doesn't work then we have to look in a different direction.

**Comment by bpadhiyar4** [comment]
I tried many ways like creating new project using wizard orr enable spring boot language server or updating spring boot support but they all are not worked for me.

**Comment by kdvolder** [comment]
Okay, if even a new project from the 'New Spring Starter' wizard doesn't work then it probably isn't because of the project itself. But due to something else. Let me try to do a bit of testing myself on Windows using STS 4.3.2 to see if a basic STS 4.3.2 setup on Windows works for me. I'll report back in a bit the result.

**Comment by kdvolder** [comment]
It works for me. Here's what  did:

- I installed a fresh STS 4.3.2 on my test Windows VM. 
- Created a "New Spring Starter" project in a brand new workspace 
- waited a bit until the project was setup 
- opened application.properties file.
- type 'appname<CTRL-space>'

At first it didn't work but I think this is normal. It takes a bit of time to start the lanuage server and for the language server to index property metadata from the project's classpath. However after a few seconds wait, tried again and now everything works.

I think maybe there is a problem with the your STS installation. We've had a number of reports from people on Windows having issues because Windows built-in zip utility doesn't properly handle long path names and it unpacks the STS zip file incorrectly as a result.

Maybe this is your problem? If you used the standard/builtin windows zip/unzip utility then it almost certainly is the case. If so please try downloading a fresh copy of the STS full distribution zip (https://download.springsource.com/release/STS4/4.3.2.RELEASE/dist/e4.12/spring-tool-suite-4-4.3.2.RELEASE-e4.12.0-win32.win32.x86_64.zip). Then unzip it with either `7zip` or even just using the `jar` command from the terminal (I personally use command like `jar xvf <path-to-zip>`. This is convenient, since we are using Java we typically have jar installed already.

**Comment by kdvolder** [comment]
For reference, these are the reports about long path problems on Windows that we have received previously: 

https://github.com/spring-projects/sts4/issues/349
https://github.com/spring-projects/sts4/issues/304

**Comment by bpadhiyar4** [comment]
@kdvolder Thank you for your support issue was solved by unzipping  with cmd jar command. Folder name was too long for the window process.
