### ISSUE TITLE
Boot Hint stops working after upgrading the plugin is the newest version (0.1.3)

### ISSUE THREAD

**Issue by khe817** [spring-projects/sts4#38]
Boot hint breaks with the following error in the log:

```
[Timer-0] ERROR org.springframework.ide.vscode.commons.util.Log - Error
org.json.JSONException: JSONObject["contexts"] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at org.json.JSONObject.getJSONObject(JSONObject.java:636)
	at org.springframework.ide.vscode.commons.boot.app.cli.requestmappings.RequestMappingsParser20.parse(RequestMappingsParser20.java:23)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootApp.parseRequestMappingsJson(SpringBootApp.java:202)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootApp.getRequestMappings(SpringBootApp.java:227)
	at org.springframework.ide.vscode.boot.java.requestmapping.RequestMappingHoverProvider.getRequestMappingMethodFromRunningApp(RequestMappingHoverProvider.java:106)
	at org.springframework.ide.vscode.boot.java.requestmapping.RequestMappingHoverProvider.getLiveHoverHints(RequestMappingHoverProvider.java:61)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaHoverProvider.lambda$extractLiveHintsForAnnotation$2(BootJavaHoverProvider.java:170)
	at java.base/java.util.Optional.ifPresent(Optional.java:175)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaHoverProvider.extractLiveHintsForAnnotation(BootJavaHoverProvider.java:168)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaHoverProvider$1.visit(BootJavaHoverProvider.java:106)
	at org.eclipse.jdt.core.dom.SingleMemberAnnotation.accept0(SingleMemberAnnotation.java:162)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2867)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:618)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2867)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2867)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:257)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaHoverProvider.lambda$getLiveHoverHints$0(BootJavaHoverProvider.java:90)
	at org.springframework.ide.vscode.boot.java.utils.CompilationUnitCache.withCompilationUnit(CompilationUnitCache.java:113)
	at org.springframework.ide.vscode.boot.java.handlers.BootJavaHoverProvider.getLiveHoverHints(BootJavaHoverProvider.java:86)
	at org.springframework.ide.vscode.boot.java.utils.SpringLiveHoverWatchdog.update(SpringLiveHoverWatchdog.java:151)
	at org.springframework.ide.vscode.boot.java.utils.SpringLiveHoverWatchdog.update(SpringLiveHoverWatchdog.java:170)
	at org.springframework.ide.vscode.boot.java.utils.SpringLiveHoverWatchdog$2.run(SpringLiveHoverWatchdog.java:108)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

Boot hint in older version of Pivotal.vscode-boot-java plugin works.

I have tried to delete the tmp folder hsperf-<username> as the wiki suggests for when Boot Hint does not show up. It didn't do it.

##### Environment
- Operating System: windows 10
- JDK version: 1.8.0_131
- Visual Studio Code version: 1.19.3

**Comment by kdvolder** [comment]
Looks like this might a Boot 2.0 project, but yet up to the latests snapshot? As we have been tracking the changes in the actuator format that have been going to Boot 2.0. As Boot folks have changed it repeatedly and we only keep it working with snapshot, intending it to work with the final release. But we have not kept it working with older milestones of Boot 2.0. 

Long story short, assuming your boot project uses a milestone release of Boot 2.0 then it isn't expected to work. Please update your project to use Boot 2.0 snapshot or, when its out, Boot 2.0 release.

I'm closing this assuming that I've correctly guessed the problem. If it still doesn't work with latest snapshot, then feel free to re-open it and add additional details.
