### ISSUE TITLE
Internal Error canceling "Edit Starters" (time sensitive)

### ISSUE THREAD

**Issue by gigermocas** [spring-projects/sts4#384]
Right clicking on project and going to "Spring" - "Edit Starters" and clicking cancel triggers an Internal Error: Widget is disposed.

There's a sweet spot, canceling too soon or after all content is available works fine.
I can trigger this behavior pretty consistently.

I'm using 4.4.0.201909171436-RELEASE and Eclipse 2019-09 R (4.13.0)

**Comment by kdvolder** [comment]
Thanks for reporting this. This should be easy for us to fix if you attach the full stacktrace. Could you look in the Eclipse error log and attach / paste the stacktrace? You can open the error log via "Window >> Show View >> Other >> Error Log".

**Comment by kdvolder** [comment]
BTW: The error is harmless, though I can imagine it is annoying to see it all the time, so we should fix it of course :-)

**Comment by gigermocas** [comment]
Yeah, it's a pretty minor thing.

Here it goes:
`org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4711)
	at org.eclipse.swt.SWT.error(SWT.java:4626)
	at org.eclipse.swt.SWT.error(SWT.java:4597)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:452)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:351)
	at org.eclipse.swt.widgets.Text.getText(Text.java:1394)
	at org.eclipse.jface.dialogs.TitleAreaDialog.updateMessage(TitleAreaDialog.java:627)
	at org.eclipse.jface.dialogs.TitleAreaDialog.showMessage(TitleAreaDialog.java:613)
	at org.eclipse.jface.dialogs.TitleAreaDialog.setMessage(TitleAreaDialog.java:587)
	at org.springsource.ide.eclipse.commons.livexp.ui.DialogWithSections.updateStatus(DialogWithSections.java:212)
	at org.springsource.ide.eclipse.commons.livexp.ui.DialogWithSections.access$3(DialogWithSections.java:209)
	at org.springsource.ide.eclipse.commons.livexp.ui.DialogWithSections$3.runInUIThread(DialogWithSections.java:197)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3961)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3588)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)`
