### ISSUE TITLE
STS 4.6.2 and Eclipse 2020-06 RC1: FrameworkEvent ERROR

### ISSUE THREAD

**Issue by thokuest** [spring-projects/sts4#477]
Since Eclipse 2020-06  is due this month I thought it's time to give it a try. So I downloaded the _Eclipse IDE for Enterprise Java Developers_ 2020-06 RC1, started with an empty workspace and installed STS with all features via Marketplace client. The installation went smoothly without any issues. However, after a restart I observed that none of its features seem to be active. The error log reads:

```
eclipse.buildId=4.16.0.I20200528-0200
java.version=1.8.0_241
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -data file:/C:/dev/temp/ws/ -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.springframework.tooling.ls.eclipse.gotosymbol
Error
Tue Jun 09 15:24:20 CEST 2020
FrameworkEvent ERROR

org.osgi.framework.BundleException: Could not resolve module: org.springframework.tooling.ls.eclipse.gotosymbol [995]
  Unresolved requirement: Require-Bundle: org.springframework.ide.eclipse.boot.dash
    -> Bundle-SymbolicName: org.springframework.ide.eclipse.boot.dash; bundle-version="3.9.13.202005241057-CI-B2488"; singleton:="true"
       org.springframework.ide.eclipse.boot.dash [975]
         No resolution report for the bundle.  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.springframework.ide.eclipse.boot.dash [osgi.identity; osgi.identity="org.springframework.ide.eclipse.boot.dash"; type="osgi.bundle"; version:Version="3.9.13.202005241057-CI-B2488"; singleton:="true"] because it is exposed to package 'javax.annotation' from resources org.eclipse.osgi [osgi.identity; type="osgi.bundle"; version:Version="3.15.300.v20200520-1959"; osgi.identity="org.eclipse.osgi"; singleton:="true"] and javax.annotation [osgi.identity; osgi.identity="javax.annotation"; type="osgi.bundle"; version:Version="1.3.5.v20200504-1837"] via two dependency chains.

Chain 1:
  org.springframework.ide.eclipse.boot.dash [osgi.identity; osgi.identity="org.springframework.ide.eclipse.boot.dash"; type="osgi.bundle"; version:Version="3.9.13.202005241057-CI-B2488"; singleton:="true"]
    require: (osgi.wiring.bundle=org.eclipse.core.runtime)
     |
    provide: osgi.wiring.bundle: org.eclipse.core.runtime
  org.eclipse.osgi [osgi.identity; type="osgi.bundle"; version:Version="3.15.300.v20200520-1959"; osgi.identity="org.eclipse.osgi"; singleton:="true"]

Chain 2:
  org.springframework.ide.eclipse.boot.dash [osgi.identity; osgi.identity="org.springframework.ide.eclipse.boot.dash"; type="osgi.bundle"; version:Version="3.9.13.202005241057-CI-B2488"; singleton:="true"]
    import: (osgi.wiring.package=org.glassfish.jersey.client)
     |
    export: osgi.wiring.package=org.glassfish.jersey.client; uses:=org.glassfish.jersey
  org.glassfish.jersey.core.jersey-client [osgi.identity; osgi.identity="org.glassfish.jersey.core.jersey-client"; type="osgi.bundle"; version:Version="2.30.1.v20200513-1859"]
    import: (&(osgi.wiring.package=org.glassfish.jersey)(&(version>=2.30.1)(!(version>=3.0.0))))
     |
    export: osgi.wiring.package=org.glassfish.jersey; uses:=javax.annotation
  org.glassfish.jersey.core.jersey-common [osgi.identity; osgi.identity="org.glassfish.jersey.core.jersey-common"; type="osgi.bundle"; version:Version="2.30.1.v20200513-1859"]
    import: (&(osgi.wiring.package=javax.annotation)(&(version>=1.3.0)(!(version>=1.4.0))))
     |
    export: osgi.wiring.package: javax.annotation
  javax.annotation [osgi.identity; osgi.identity="javax.annotation"; type="osgi.bundle"; version:Version="1.3.5.v20200504-1837"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

I see the same errors for 

* org.springframework.tooling.boot.ls
* org.springframework.ide.eclipse.boot.dash.cf
* org.springframework.ide.eclipse.boot.dash

**Comment by martinlippert** [comment]
Hey @thokuest, thanks a lot for reporting this. I can reproduce this issue using the latest Eclipse 2020-06 RC builds and after installing the STS 4.6.2 release.

The good news here is that this is already fixed for the upcoming 4.7.0 release. If you want to give the nightly CI build a try, feel free to install it from here:

https://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.16

In this case, I would recommend to select the features from the update site manually, as described here: https://github.com/spring-projects/sts4/wiki/Installation#install-spring-tools-4-into-an-existing-eclipse-via-a-p2-repo

Or grab a ready-to-use distribution build from here:
http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

Hope this helps and thanks for reporting this as early feedback for the upcoming release. Much appreciated.
