### ISSUE TITLE
Boot dashboard in STS 4.16 not working with eclipse JEE 2020-06

### ISSUE THREAD

**Issue by hennejg** [spring-projects/sts4#485]
After installing STS 4 via the marketplace into a clean install of JEE 2020-06 no STS views (in particular the Boot Dashboard) are available. The error log contains four `FrameworkEvent ERROR` entries all pointing to "Unable to resolve resource org.springframework.ide.eclipse.boot.dash" as the culprit - here is an example:

```
org.osgi.framework.BundleException: Could not resolve module: org.springframework.ide.eclipse.boot.dash.cf [978]
  Unresolved requirement: Require-Bundle: org.springframework.ide.eclipse.boot.dash
    -> Bundle-SymbolicName: org.springframework.ide.eclipse.boot.dash; bundle-version="3.9.13.202005241057-CI-B2488"; singleton:="true"
       org.springframework.ide.eclipse.boot.dash [977]
         No resolution report for the bundle.  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.springframework.ide.eclipse.boot.dash [osgi.identity; osgi.identity="org.springframework.ide.eclipse.boot.dash"; type="osgi.bundle"; version:Version="3.9.13.202005241057-CI-B2488"; singleton:="true"] because it is exposed to package 'javax.annotation' from resources org.eclipse.osgi [osgi.identity; type="osgi.bundle"; version:Version="3.15.300.v20200520-1959"; osgi.identity="org.eclipse.osgi"; singleton:="true"] and javax.annotation [osgi.identity; osgi.identity="javax.annotation"; type="osgi.bundle"; version:Version="1.3.5.v20200504-1837"] via two dependency chains.

Chain 1:
  org.springframework.ide.eclipse.boot.dash [osgi.identity; osgi.identity="org.springframework.ide.eclipse.boot.dash"; type="osgi.bundle"; version:Version="3.9.13.202005241057-CI-B2488"; singleton:="true"]
    require: (osgi.wiring.bundle=org.eclipse.core.runtime)
     |
    provide: osgi.wiring.bundle: org.eclipse.core.runtime
  org.eclipse.osgi [osgi.identity; type="osgi.bundle"; version:Version="3.15.300.v20200520-1959"; osgi.identity="org.eclipse.osgi"; singleton:="true"]

Chain 2:
  org.springframework.ide.eclipse.boot.dash [osgi.identity; osgi.identity="org.springframework.ide.eclipse.boot.dash"; type="osgi.bundle"; version:Version="3.9.13.202005241057-CI-B2488"; singleton:="true"]
    import: (osgi.wiring.package=org.glassfish.jersey.client)
     |
    export: osgi.wiring.package=org.glassfish.jersey.client; uses:=org.glassfish.jersey
  org.glassfish.jersey.core.jersey-client [osgi.identity; osgi.identity="org.glassfish.jersey.core.jersey-client"; type="osgi.bundle"; version:Version="2.30.1.v20200513-1859"]
    import: (&(osgi.wiring.package=org.glassfish.jersey)(&(version>=2.30.1)(!(version>=3.0.0))))
     |
    export: osgi.wiring.package=org.glassfish.jersey; uses:=javax.annotation
  org.glassfish.jersey.core.jersey-common [osgi.identity; osgi.identity="org.glassfish.jersey.core.jersey-common"; type="osgi.bundle"; version:Version="2.30.1.v20200513-1859"]
    import: (&(osgi.wiring.package=javax.annotation)(&(version>=1.3.0)(!(version>=1.4.0))))
     |
    export: osgi.wiring.package: javax.annotation
  javax.annotation [osgi.identity; osgi.identity="javax.annotation"; type="osgi.bundle"; version:Version="1.3.5.v20200504-1837"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

I already cleaned out my ~/.p2 repository and reinstalled cleanly without success. Interestingly, the installation details show the "Spring IDE Boot Microservices Dash" under "Installed Software", but under "Plugins" the plugin seems to be missing. However, "Install new software", doesn't offer any relevant items to install from https://download.springsource.com/release/TOOLS/sts4/update/e4.16/.

**Comment by martinlippert** [comment]
We are aware of that issue and have fixed it already for the upcoming release (to be released very soon).

If you want to grab the CI build right now, you can install it manually via: https://github.com/spring-projects/sts4/wiki/Installation#install-spring-tools-4-into-an-existing-eclipse-via-a-p2-repo - but use the nightly CI update site: https://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.16 (instead of the release one).

The other option is to wait for the 4.7.0 release.

**Comment by hennejg** [comment]
Brilliant! Thanks!

**Comment by martinlippert** [comment]
The Spring Tools 4 for Eclipse 4.7.0 release got published a few moments ago, so please update.
