### ISSUE TITLE
Unable to read repository at ... Tag mismatch!

### ISSUE THREAD

**Issue by 2019-05-10** [spring-projects/sts4#502]
Just upgraded to Eclipse 2020-06, needed several attempts since STS always breaks the process.
Disabling STS for the moment helped me succeed, but now I am stuck with STS still not updating:

Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springframework.ide.eclipse.boot.dash_3.9.13.202006180736-RELEASE.jar. Tag mismatch!
Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springframework.ide.eclipse.boot.dash.cf_3.9.13.202006180736-RELEASE.jar. Tag mismatch!
Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springframework.ide.eclipse.boot.dash.source_3.9.13.202006180736-RELEASE.jar. Tag mismatch!
Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springframework.ide.eclipse.boot.wizard_3.9.13.202006180736-RELEASE.jar. Tag mismatch!
Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springsource.ide.eclipse.commons.cloudfoundry.client.v2.source_3.9.13.202006180736-RELEASE.jar. Tag mismatch!

Update site used:
https://dist.springsource.com/release/TOOLS/sts4/update/e4.16/

Note that it says _dist_ and yet ends up with _download_!

In another ticket someone proposed to use _dist_ instead of _download_, but even that workaround is broken now.
STS is the only update site that gives me such trouble.

**Comment by 2019-05-10** [comment]
Would it be at least possible to provide an archived update site for local use?
Thanks to whatever constraints there seem to be no easy way to mirror the site .

**Comment by kdvolder** [comment]
The update sites can indeed be a hassle. What you seem to be experiencing could have something to do with stale web-caches. Though I'm not entirely sure what you mean by 'Tag mismatch' is that the error message you are getting? I have never seen such a message so I don't know where it comes from.

In any case I recommend you avoid the update site finickyness and just download a fully-packaged and complete distrbution if STS instead of trying create one yourself by installing the STS bundles from an update site. STS is a complex product to package and the update sites / dependencies are indeed rather finicky and complex with variations across different versions of the Eclipse platform. This is why we recommend you download the full distribution build rather than put your trust in Eclipse Equinox/p2 to wire it all together correctly.

> Would it be at least possible to provide an archived update site for local use?

https://dist.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/sts4-4.7.0.RELEASE-e4.16.0-updatesite.zip

**Comment by kdvolder** [comment]
Note: I just tested the update site from https://dist.springsource.com/release/TOOLS/sts4/update/e4.16/

It installed fine for me as far as being able to read / download all the pieces.

I did run into another known issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=564475

That problem appears to be an issue with Eclipse / P2 not wiring things the same way when they are installed incrementally from multiple update sites (instead of 'full distribution' giving you a clean wiring of all the bundles as installed at once). In case you hit that problem too, this might save you a long read. Just add `-clean` argument to STS.ini file. I still recommend however you skip the update site and download the all in one distribution instead.

**Comment by kdvolder** [comment]
I'll close this now as I don't see anything for me to do here to 'fix a problem' at the moment. Feel free however to post further comments / questions if you need more help and we'll do our best to assist.

**Comment by 2019-05-10** [comment]
"Tag mismatch!" is part of the error message:

![image](https://user-images.githubusercontent.com/50481865/87014348-4f87a400-c1cc-11ea-8f5e-6dd6033124e0.png)

Basically, it's an Eclipse error, of course.
But given that your's is the only update site I have trouble with and given that even previously there were issues with your certificates (#441), it may be caused by your SSL setup ...

Here's the stacktrace from the log:
```
!ENTRY org.eclipse.equinox.p2.engine 4 4 2020-07-09 10:04:45.973
!MESSAGE An error occurred while collecting items to be installed
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2020-07-09 10:04:45.973
!MESSAGE session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
!SUBENTRY 1 org.eclipse.equinox.p2.transport.ecf 4 1002 2020-07-09 10:04:45.973
!MESSAGE Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springframework.ide.eclipse.boot.dash_3.9.13.202006180736-RELEASE.jar.
!STACK 0
javax.net.ssl.SSLException: Tag mismatch!
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:129)
at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1147)
at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1117)
at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:816)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer$1.performFileTransfer(AbstractRetrieveFileTransfer.java:178)
at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:74)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
at java.base/com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:623)
at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941)
at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2497)
at java.base/sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1629)
at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:262)
at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
... 12 more
!SUBENTRY 1 org.eclipse.equinox.p2.transport.ecf 4 1002 2020-07-09 10:04:45.974
!MESSAGE Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springframework.ide.eclipse.boot.dash.cf_3.9.13.202006180736-RELEASE.jar.
!STACK 0
javax.net.ssl.SSLException: Tag mismatch!
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:129)
at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1147)
at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1117)
at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:816)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer$1.performFileTransfer(AbstractRetrieveFileTransfer.java:178)
at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:74)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
at java.base/com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:623)
at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941)
at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2497)
at java.base/sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1629)
at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:262)
at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
... 12 more
!SUBENTRY 1 org.eclipse.equinox.p2.transport.ecf 4 1002 2020-07-09 10:04:45.974
!MESSAGE Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springframework.ide.eclipse.boot.dash.source_3.9.13.202006180736-RELEASE.jar.
!STACK 0
javax.net.ssl.SSLException: Tag mismatch!
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:129)
at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1147)
at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1117)
at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:816)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer$1.performFileTransfer(AbstractRetrieveFileTransfer.java:178)
at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:74)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
at java.base/com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:623)
at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941)
at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2497)
at java.base/sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1629)
at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:262)
at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
... 12 more
!SUBENTRY 1 org.eclipse.equinox.p2.transport.ecf 4 1002 2020-07-09 10:04:45.975
!MESSAGE Unable to read repository at https://download.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springsource.ide.eclipse.commons.cloudfoundry.client.v2.source_3.9.13.202006180736-RELEASE.jar.
!STACK 0
javax.net.ssl.SSLException: Tag mismatch!
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:129)
at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1147)
at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1117)
at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:816)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer$1.performFileTransfer(AbstractRetrieveFileTransfer.java:178)
at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:74)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
at java.base/com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:623)
at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941)
at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2497)
at java.base/sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1629)
at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:262)
at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190)
at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
... 12 more
```

**Comment by 2019-05-10** [comment]
> In any case I recommend you avoid the update site finickyness and just download a fully-packaged and complete distrbution of STS

How would that prevent the issue at the next update? Wouldn't I run into the same scenario again?

> > Would it be at least possible to provide an archived update site for local use?
> 
> https://dist.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/sts4-4.7.0.RELEASE-e4.16.0-updatesite.zip

That's great! Thank you so much!
Did I miss it or is that not linked to on the web site anywhere?
If not, I think it would be good to make it available as a regular download (or response to the update site URL when requesting via browser/wget).

**Comment by 2019-05-10** [comment]
Here's what I get with curl. 
Seems ok, except for maybe
`* ALPN, server did not agree to a protocol`
and, of course
`* Failed writing body (0 != 16384)`

```
curl -i -vvv https://download.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springsource.ide.eclipse.commons.cloudfoundry.client.v2.source_3.9.13.202006180736-RELEASE.jar
*   Trying 104.26.12.6:443...
* TCP_NODELAY set
* Connected to download.springsource.com (104.26.12.6) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Nov 24 00:00:00 2019 GMT
*  expire date: Oct  9 12:00:00 2020 GMT
*  subjectAltName: host "download.springsource.com" matched cert's "*.springsource.com"
*  issuer: CN=securityappliance.at.our.company
*  SSL certificate verify ok.
> GET /release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springsource.ide.eclipse.commons.cloudfoundry.client.v2.source_3.9.13.202006180736-RELEASE.jar HTTP/1.1
> Host: download.springsource.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
HTTP/1.0 200 OK
< Date: Thu, 09 Jul 2020 08:23:12 GMT
Date: Thu, 09 Jul 2020 08:23:12 GMT
< Content-Type: application/octet-stream
Content-Type: application/octet-stream
< Content-Length: 11305335
Content-Length: 11305335
* HTTP/1.0 connection set to keep alive!
< Connection: keep-alive
Connection: keep-alive
< Set-Cookie: __cfduid=da6f394dfa3da47ad1e81709dda864e741594282992; expires=Sat, 08-Aug-20 08:23:12 GMT; path=/; domain=.springsource.com; HttpOnly; SameSite=Lax
Set-Cookie: __cfduid=da6f394dfa3da47ad1e81709dda864e741594282992; expires=Sat, 08-Aug-20 08:23:12 GMT; path=/; domain=.springsource.com; HttpOnly; SameSite=Lax
< Last-Modified: Thu, 18 Jun 2020 14:11:11 GMT
Last-Modified: Thu, 18 Jun 2020 14:11:11 GMT
< ETag: "7b98bc64279f9ad7109d40493646a645"
ETag: "7b98bc64279f9ad7109d40493646a645"
< x-amz-version-id: y5lNPYHcn9unYgAo4lrBtKWUtW910Wcf
x-amz-version-id: y5lNPYHcn9unYgAo4lrBtKWUtW910Wcf
< X-Cache: Miss from cloudfront
X-Cache: Miss from cloudfront
< Via: 1.1 c923d89f70351e442aa1b87e2d6434f8.cloudfront.net (CloudFront)
Via: 1.1 c923d89f70351e442aa1b87e2d6434f8.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: ATL56-C1
X-Amz-Cf-Pop: ATL56-C1
< X-Amz-Cf-Id: QeM3YxiXBsv9uncC5VPUMZXOwaFAMnfd-psGXnjn19oq1h4kJyEqKA==
X-Amz-Cf-Id: QeM3YxiXBsv9uncC5VPUMZXOwaFAMnfd-psGXnjn19oq1h4kJyEqKA==
< Cache-Control: max-age=86400
Cache-Control: max-age=86400
< CF-Cache-Status: HIT
CF-Cache-Status: HIT
< Age: 56172
Age: 56172
< Accept-Ranges: bytes
Accept-Ranges: bytes
< cf-request-id: 03d444fc1a0000dfef1ebde200000001
cf-request-id: 03d444fc1a0000dfef1ebde200000001
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
Server: cloudflare
< CF-RAY: 5b00a4402bd8dfef-FRA
CF-RAY: 5b00a4402bd8dfef-FRA

<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 16384)
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
```

**Comment by martinlippert** [comment]
@2019-05-10 my result using curl looks similar, but slightly different.

It says `* ALPN, server accepted to use h2` instead of your `ALPN, server did not agree to a protocol`.
Adding `--output myfile.jar` results in a nicely downloaded artifact here.

We definitely need someone with deep network knowledge here to help out with this.


```
*   Trying 172.67.75.139...
* TCP_NODELAY set
* Connected to download.springsource.com (172.67.75.139) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Nov 24 00:00:00 2019 GMT
*  expire date: Oct  9 12:00:00 2020 GMT
*  subjectAltName: host "download.springsource.com" matched cert's "*.springsource.com"
*  issuer: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=CloudFlare Inc ECC CA-2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fe86680c400)
> GET /release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springsource.ide.eclipse.commons.cloudfoundry.client.v2.source_3.9.13.202006180736-RELEASE.jar HTTP/2
> Host: download.springsource.com
> User-Agent: curl/7.64.1
> Accept: */*
```

**Comment by martinlippert** [comment]
@2019-05-10 from what region are you executing the curl command? The IP for the download server is definitely different, so I guess the CDN offers you a different server than me, but I could try to reproduce this from without your region, too.

**Comment by 2019-05-10** [comment]
with `--output myfile.jar`
and this time the same IP as yours.

I am in Germany.

```
curl -i -vvv https://download.springsource.com/release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springsource.ide.eclipse.commons.cloudfoundry.client.v2.source_3.9.13.202006180736-RELEASE.jar --output myfile.jar
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 172.67.75.139:443...
* TCP_NODELAY set
* Connected to download.springsource.com (172.67.75.139) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [81 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1535 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [148 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Nov 24 00:00:00 2019 GMT
*  expire date: Oct  9 12:00:00 2020 GMT
*  subjectAltName: host "download.springsource.com" matched cert's "*.springsource.com"
*  issuer: CN=securityappliance.at.our.company
*  SSL certificate verify ok.
} [5 bytes data]
> GET /release/TOOLS/sts4/update/4.7.0.RELEASE/e4.16/plugins/org.springsource.ide.eclipse.commons.cloudfoundry.client.v2.source_3.9.13.202006180736-RELEASE.jar HTTP/1.1
> Host: download.springsource.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0{ [5 bytes data]
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0{ [5 bytes data]
< Date: Thu, 09 Jul 2020 09:56:08 GMT
{ [5 bytes data]
< Content-Type: application/octet-stream
{ [5 bytes data]
< Content-Length: 11305335
{ [5 bytes data]
* HTTP/1.0 connection set to keep alive!
< Connection: keep-alive
{ [5 bytes data]
< Set-Cookie: __cfduid=da40797a8272487a7eeecd0ed7382e37c1594288568; expires=Sat, 08-Aug-20 09:56:08 GMT; path=/; domain=.springsource.com; HttpOnly; SameSite=Lax
{ [5 bytes data]
< Last-Modified: Thu, 18 Jun 2020 14:11:11 GMT
{ [5 bytes data]
< ETag: "7b98bc64279f9ad7109d40493646a645"
{ [5 bytes data]
< x-amz-version-id: y5lNPYHcn9unYgAo4lrBtKWUtW910Wcf
{ [5 bytes data]
< X-Cache: Miss from cloudfront
{ [5 bytes data]
< Via: 1.1 c923d89f70351e442aa1b87e2d6434f8.cloudfront.net (CloudFront)
{ [5 bytes data]
< X-Amz-Cf-Pop: ATL56-C1
{ [5 bytes data]
< X-Amz-Cf-Id: QeM3YxiXBsv9uncC5VPUMZXOwaFAMnfd-psGXnjn19oq1h4kJyEqKA==
{ [5 bytes data]
< Cache-Control: max-age=86400
{ [5 bytes data]
< CF-Cache-Status: HIT
{ [5 bytes data]
< Age: 61748
{ [5 bytes data]
< Accept-Ranges: bytes
{ [5 bytes data]
< cf-request-id: 03d49a11390000c2e580069200000001
{ [5 bytes data]
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
{ [5 bytes data]
< Server: cloudflare
{ [5 bytes data]
< CF-RAY: 5b012c61fa5cc2e5-FRA
{ [5 bytes data]
<
{ [5 bytes data]
* TLSv1.2 (OUT), TLS alert, protocol version (582):
} [2 bytes data]
* OpenSSL SSL_read: error:1408F10B:SSL routines:ssl3_get_record:wrong version number, errno 0
2 10.7M    2  272k    0     0   180k      0  0:01:01  0:00:01  0:01:00  180k
* Closing connection 0
curl: (56) OpenSSL SSL_read: error:1408F10B:SSL routines:ssl3_get_record:wrong version number, errno 0
```

**Comment by martinlippert** [comment]
Don't understand yet why this behaves different. Need to get in touch with our admin, maybe he can shed some light on this, but that might take a while due to vacation time.

**Comment by martinlippert** [comment]
which version of `openssl` do you have installed on your machine? (`openssl version`)

**Comment by 2019-05-10** [comment]
OpenSSL 1.1.1g  21 Apr 2020

**Comment by kdvolder** [comment]
> How would that prevent the issue at the next update? Wouldn't I run into the same scenario again?

Fair enough. My advice was more in relation to the fact that Eclipse bundle installation / resolution is often finicky irrespective of whether you can even download the bundles.

I think you have presented some good evidence that perhaps there's something between about our download site's ssl config that somehow doesn't agree with your Eclipse SSL client. And that this may be something that can be fixed from our end. 

So let me re-open the ticket as there is possibly something to fix here on our end. 

Also I'll cc @trevormarshall into discussion as he's the person who manages the download site and its various configurations re certificates and the like.

**Comment by kdvolder** [comment]
@2019-05-10 AS to your suggestion to make it easier for folks to find the update site as a zip. That is also a very fair point. Indeed I don't think there's a public facing site where you can easily find that link. I'll raise a ticket to fix that.

**Comment by trevormarshall** [comment]
Is this occurring on a corporate network? I am curious about "CN=securityappliance.at.our.company".

There was a known issue affecting certificates within VMware's network, for example, and that has been fixed.

**Comment by 2019-05-10** [comment]
> Is this occurring on a corporate network? I am curious about "CN=securityappliance.at.our.company".

Yes, it is. 
I once had to import a root certificate for that to work. Chrome-based browsers constantly grumble about SSL certificate issues (and need a flag), but anything else usually works.

**Comment by 2019-05-10** [comment]
Any progress on this?
Just fell in the same hole again.

**Comment by martinlippert** [comment]
The issue within the VMware network got fixed, but I guess you are inside of a different corporate network, right? In that case, I think we need a network admin from your side to join the conversation to see what exactly goes wrong here. Can you trigger that on your side?

**Comment by martinlippert** [comment]
Any news on the previous comment?

**Comment by 2019-05-10** [comment]
Since I downloaded the latest updates as update site archive and thus installed locally, I can't really say.
When is the next update/release due, so I can make a note to remeber to test?

**Comment by martinlippert** [comment]
The 4.10.0 release is scheduled for mid of March (right after the Eclipse 2021-03 release). If you want to give the nightly CI update site a try, you can find them here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html.

**Comment by 2019-05-10** [comment]
Well, today it worked.
Talked to IT Security and apparently they now changed something regarding how their system handles JARs.
No idea, what exactly, since ZIPs always worked, but "ours is not to question why" ...

So, I am closing this.

**Comment by martinlippert** [comment]
@2019-05-10 Great to hear that is works now and thanks for letting us know, much appreciated.
