### ISSUE TITLE
Eclipse 2020-09: Unable to resolve plug-in "org.springframework.ide.eclipse.ui".

### ISSUE THREAD

**Issue by rakus** [spring-projects/sts4#555]
- STS4 4.8.0.202009151856-RELEASE
- Eclipse 2020-09 (4.17.0), Build id: 20200910-1200
- Windows 10 Enterprise (1803)
- JDK 11

In the error log of eclipse I found the message that `org.springframework.ide.eclipse.ui` could not be resolved.

This results in failing to create the "Spring Explorer" view and the Spring perspective does not have a Icon, but is labeled `<Spring>`.

I checked the feature and plugins directory. This plugin is indeed missing.

I tried to install software from https://download.springsource.com/release/TOOLS/sts4/update/e4.17/ , but this didn't offer to install the missing plugin.

BTW: STS was installed via Marketplace and I'm behind a Proxy requiring authentication.

```
Unable to resolve plug-in "org.springframework.ide.eclipse.ui".

java.io.IOException: Unable to resolve plug-in "org.springframework.ide.eclipse.ui".
	at org.eclipse.core.internal.runtime.PlatformURLPluginConnection.parse(PlatformURLPluginConnection.java:64)
	at org.eclipse.core.internal.runtime.PlatformURLPluginConnection.resolve(PlatformURLPluginConnection.java:73)
	at org.eclipse.core.internal.boot.PlatformURLHandler.openConnection(PlatformURLHandler.java:69)
	at org.eclipse.osgi.internal.url.URLStreamHandlerProxy.openConnection(URLStreamHandlerProxy.java:123)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at org.eclipse.core.internal.runtime.PlatformURLConverter.toFileURL(PlatformURLConverter.java:34)
	at org.eclipse.core.runtime.FileLocator.toFileURL(FileLocator.java:261)
	at org.eclipse.jface.resource.URLImageDescriptor.getFilePath(URLImageDescriptor.java:232)
```

**Comment by martinlippert** [comment]
It sounds like you are opening a workspace or projects with STS3 metadata included. Is that assumption correct?

If so, first of all, there is no need to install additional bundles or features. We have a guide to migrate an existing workspace from STS3 to STS4:

https://github.com/spring-projects/sts4/wiki/STS3-Migration

Hope that helps! If not, please comment and we can reopen and investigate further.
