### ISSUE TITLE
how can i close thread dump on sts console in linux system

### ISSUE THREAD

**Issue by soundlift** [spring-projects/sts4#680]
**env:**
Kernel: 5.13.13-arch1-1
OS: Arch
JDK: openjdk 8.u292-1
STS-4.11.1.RELEASE run with openjdk 11.0.12.u7-1

like this

```
[RemoteTestNG] detected TestNG version 7.0.1
09:42:30.033 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating CacheAwareContextLoaderDelegate from class [org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate]
09:42:30.047 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating BootstrapContext using constructor [public org.springframework.test.context.support.DefaultBootstrapContext(java.lang.Class,org.springframework.test.context.CacheAwareContextLoaderDelegate)]
09:42:30.098 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating TestContextBootstrapper for test class [com.dtcloud.huanghe.service.impl.task.TaskQueryCardServiceImplTest] from class [org.springframework.boot.test.context.SpringBootTestContextBootstrapper]
09:42:30.109 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Neither @ContextConfiguration nor @ContextHierarchy found for test class [com.dtcloud.huanghe.service.impl.task.TaskQueryCardServiceImplTest], using SpringBootContextLoader
09:42:30.112 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [com.dtcloud.huanghe.service.impl.task.TaskQueryCardServiceImplTest]: class path resource [com/dtcloud/huanghe/service/impl/task/TaskQueryCardServiceImplTest-context.xml] does not exist
09:42:30.113 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [com.dtcloud.huanghe.service.impl.task.TaskQueryCardServiceImplTest]: class path resource [com/dtcloud/huanghe/service/impl/task/TaskQueryCardServiceImplTestContext.groovy] does not exist
09:42:30.113 [main] INFO org.springframework.test.context.support.AbstractContextLoader - Could not detect default resource locations for test class [com.dtcloud.huanghe.service.impl.task.TaskQueryCardServiceImplTest]: no resource found for suffixes {-context.xml, Context.groovy}.
09:42:30.169 [main] DEBUG org.springframework.test.context.support.ActiveProfilesUtils - Could not find an 'annotation declaring class' for annotation type [org.springframework.test.context.ActiveProfiles] and class [com.dtcloud.huanghe.service.impl.task.TaskQueryCardServiceImplTest]
09:42:30.300 [main] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@f09733f, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@e350b40, org.springframework.test.context.event.ApplicationEventsTestExecutionListener@41a0aa7d, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@2794eab6, org.springframework.test.context.support.DirtiesContextTestExecutionListener@6340e5f0, org.springframework.test.context.event.EventPublishingTestExecutionListener@45099dd3]
09:42:30.352 [main] DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener - Before test class: context [DefaultTestContext@66982506 testClass = TaskQueryCardServiceImplTest, testInstance = [null], testMethod = [null], testException = [null], mergedContextConfiguration = [WebMergedContextConfiguration@70cf32e3 testClass = TaskQueryCardServiceImplTest, locations = '{}', classes = '{class com.dtcloud.huanghe.HuangheManagerApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@1189dd52, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@16d04d3d, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@f6efaab, org.springframework.boot.test.autoconfigure.actuate.metrics.MetricsExportContextCustomizerFactory$DisableMetricExportContextCustomizer@2a3b5b47, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@47eaca72, org.springframework.test.context.web.socket.MockServerContainerContextCustomizer@71d44a3, org.springframework.boot.test.context.SpringBootTestArgs@1, org.springframework.boot.test.context.SpringBootTestWebEnvironment@6fe7aac8], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> true]], class annotated with @DirtiesContext [false] with mode [null].
09:42:30.385 [main] DEBUG org.springframework.test.context.support.TestPropertySourceUtils - Adding inlined properties to environment: {spring.jmx.enabled=false, org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}
2021-09-10 09:42:30
Full thread dump OpenJDK 64-Bit Server VM (25.292-b10 mixed mode):

"logback-1" #25 daemon prio=5 os_prio=0 tid=0x00007fb5192ab000 nid=0x3869 waiting on condition [0x00007fb46b7d3000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000071aeb94f0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"ReaderThread" #21 prio=5 os_prio=0 tid=0x00007fb518ca9800 nid=0x3867 runnable [0x00007fb46b685000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x00000007223160e8> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x00000007223160e8> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.testng.remote.strprotocol.BaseMessageSender$ReaderThread.run(BaseMessageSender.java:267)

"Service Thread" #20 daemon prio=9 os_prio=0 tid=0x00007fb51811b800 nid=0x3864 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread11" #19 daemon prio=9 os_prio=0 tid=0x00007fb518116800 nid=0x3863 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread10" #18 daemon prio=9 os_prio=0 tid=0x00007fb518114800 nid=0x3862 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread9" #17 daemon prio=9 os_prio=0 tid=0x00007fb518112800 nid=0x3861 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread8" #16 daemon prio=9 os_prio=0 tid=0x00007fb518110800 nid=0x3860 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread7" #15 daemon prio=9 os_prio=0 tid=0x00007fb51810e800 nid=0x385f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread6" #14 daemon prio=9 os_prio=0 tid=0x00007fb51810c800 nid=0x385e waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread5" #13 daemon prio=9 os_prio=0 tid=0x00007fb51810a000 nid=0x385d waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread4" #12 daemon prio=9 os_prio=0 tid=0x00007fb518108000 nid=0x385c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread3" #11 daemon prio=9 os_prio=0 tid=0x00007fb5180fe000 nid=0x385b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #10 daemon prio=9 os_prio=0 tid=0x00007fb5180fb800 nid=0x385a waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #9 daemon prio=9 os_prio=0 tid=0x00007fb5180fa000 nid=0x3859 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #8 daemon prio=9 os_prio=0 tid=0x00007fb5180f7000 nid=0x3858 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JDWP Command Reader" #7 daemon prio=10 os_prio=0 tid=0x00007fb4b0001800 nid=0x3856 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JDWP Event Helper Thread" #6 daemon prio=10 os_prio=0 tid=0x00007fb5180f3000 nid=0x3854 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JDWP Transport Listener: dt_socket" #5 daemon prio=10 os_prio=0 tid=0x00007fb5180ef800 nid=0x3852 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007fb5180d6800 nid=0x3850 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007fb5180a5000 nid=0x384e in Object.wait() [0x00007fb4c155d000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000072230a580> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x000000072230a580> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007fb5180a0800 nid=0x384d in Object.wait() [0x00007fb4c165e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000722318468> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x0000000722318468> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00007fb518015800 nid=0x383e runnable [0x00007fb51f97b000]
   java.lang.Thread.State: RUNNABLE
	at ch.qos.logback.core.OutputStreamAppender.setLayout(OutputStreamAppender.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ch.qos.logback.core.joran.util.PropertySetter.invokeMethodWithSingleParameterOnThisObject(PropertySetter.java:251)
	at ch.qos.logback.core.joran.util.PropertySetter.setComplexProperty(PropertySetter.java:301)
	at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.end(NestedComplexPropertyIA.java:173)
	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	- locked <0x000000072239cb58> (a ch.qos.logback.core.spi.LogbackLock)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:188)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:165)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:282)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:240)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:216)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplicationRunListeners$$Lambda$135/970419381.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:374)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:123)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	- locked <0x0000000722302f68> (a org.springframework.test.context.cache.DefaultContextCache)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	- locked <0x0000000722302810> (a com.dtcloud.huanghe.service.impl.task.TaskQueryCardServiceImplTest)
	at org.testng.TestRunner$$Lambda$119/837457281.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

"VM Thread" os_prio=0 tid=0x00007fb518096800 nid=0x384c runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007fb51802a800 nid=0x383f runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007fb51802c800 nid=0x3840 runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007fb51802e000 nid=0x3841 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007fb518030000 nid=0x3842 runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007fb518032000 nid=0x3843 runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007fb518033800 nid=0x3844 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007fb518035800 nid=0x3845 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007fb518037000 nid=0x3846 runnable 

"GC task thread#8 (ParallelGC)" os_prio=0 tid=0x00007fb518039000 nid=0x3847 runnable 

"GC task thread#9 (ParallelGC)" os_prio=0 tid=0x00007fb51803a800 nid=0x3848 runnable 

"GC task thread#10 (ParallelGC)" os_prio=0 tid=0x00007fb51803c800 nid=0x3849 runnable 

"GC task thread#11 (ParallelGC)" os_prio=0 tid=0x00007fb51803e000 nid=0x384a runnable 

"GC task thread#12 (ParallelGC)" os_prio=0 tid=0x00007fb518040000 nid=0x384b runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007fb51811e000 nid=0x3865 waiting on condition 

JNI global references: 4053

Heap
 PSYoungGen      total 148992K, used 25271K [0x000000071a600000, 0x0000000724c00000, 0x00000007c0000000)
  eden space 128000K, 9% used [0x000000071a600000,0x000000071b2796d0,0x0000000722300000)
  from space 20992K, 59% used [0x0000000722300000,0x0000000722f34768,0x0000000723780000)
  to   space 20992K, 0% used [0x0000000723780000,0x0000000723780000,0x0000000724c00000)
 ParOldGen       total 339968K, used 88K [0x00000005cf200000, 0x00000005e3e00000, 0x000000071a600000)
  object space 339968K, 0% used [0x00000005cf200000,0x00000005cf216010,0x00000005e3e00000)
 Metaspace       used 19022K, capacity 19934K, committed 20096K, reserved 1067008K
  class space    used 2378K, capacity 2565K, committed 2688K, reserved 1048576K


  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.2)
```

all screen is thread dump logs
i can't focus on my logs;

help the kid!!!

**Comment by martinlippert** [comment]
Can you provide a few steps how to reproduce this issue (and maybe point to a sample project)?

**Comment by soundlift** [comment]
> Can you provide a few steps how to reproduce this issue (and maybe point to a sample project)?

i found a way to reproduce this issue in eclipse,
when i change "Installed JREs" default jre to openjdk8,then the "thread dump" will showing;
so, now i can fix this problom in eclipse;

but not work in sts;
i change default jre to "/opt/sts-4.11.1.RELEASE/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_16.0.2.v20210721-1149/jre" still can't fix it;

**Comment by martinlippert** [comment]
@soundlift Thanks for closing this. Did you find a solution that you would like to share here?

**Comment by soundlift** [comment]
> @soundlift Thanks for closing this. Did you find a solution that you would like to share here?

recover "Installed JREs" default jre;
problems solved
