### ISSUE TITLE
Cannot update vscode plugin to 1.34.0

### ISSUE THREAD

**Issue by Faputa** [spring-projects/sts4#784]
I have tried auto-updating and manual installation, and have re-installed vscode, but could not upgrade this plugin.

The following is the log output:
```
[2022-06-14 14:02:08.089] [renderer1] [warning] Skipping extension /c:/Users/Admin/.vscode/extensions/ms-vscode.references-view-0.0.89 with lower version 0.0.89.
[2022-06-14 14:02:08.132] [renderer1] [warning] [redhat.vscode-xml]: 无法注册“redhat.telemetry.enabled”。此属性已注册。
[2022-06-14 14:02:11.555] [renderer1] [error] SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at y.$getPassword (vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1724:49220)
[2022-06-14 14:03:03.373] [renderer1] [error] ENOENT: no such file or directory, open 'c:\Users\Admin\.vscode\extensions\.42480fe3-8c10-47d4-b952-e10bd249f6f6\language-server\META-INF\third-party-open-source-licenses\bsd 3-clause "new" or "revised" license (bsd-3-clause) - apl-v10.html': Extract: ENOENT: no such file or directory, open 'c:\Users\Admin\.vscode\extensions\.42480fe3-8c10-47d4-b952-e10bd249f6f6\language-server\META-INF\third-party-open-source-licenses\bsd 3-clause "new" or "revised" license (bsd-3-clause) - apl-v10.html'
    at F.extractAtLocation (vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:213215)
    at async F.extractUserExtension (vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:210606)
    at async $.extract (vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217251)
    at async $.doRun (vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218192)
[2022-06-14 14:12:18.292] [renderer1] [error] ["Download: EPERM: operation not permitted, rename 'c:\\Users\\Admin\\AppData\\Roaming\\Code\\CachedExtensionVSIXs\\.f8a4d69d-0246-4c53-8905-e70c38ca4b09' -> 'c:\\Users\\Admin\\AppData\\Roaming\\Code\\CachedExtensionVSIXs\\pivotal.vscode-spring-boot-1.34.0'","    at $.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:219042)","    at async $.doRun (vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217660)"]
[2022-06-14 14:12:18.295] [renderer1] [error] EPERM: operation not permitted, rename 'c:\Users\Admin\AppData\Roaming\Code\CachedExtensionVSIXs\.f8a4d69d-0246-4c53-8905-e70c38ca4b09' -> 'c:\Users\Admin\AppData\Roaming\Code\CachedExtensionVSIXs\pivotal.vscode-spring-boot-1.34.0': Download: EPERM: operation not permitted, rename 'c:\Users\Admin\AppData\Roaming\Code\CachedExtensionVSIXs\.f8a4d69d-0246-4c53-8905-e70c38ca4b09' -> 'c:\Users\Admin\AppData\Roaming\Code\CachedExtensionVSIXs\pivotal.vscode-spring-boot-1.34.0'
    at $.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:219042)
    at async $.doRun (vscode-file://vscode-app/c:/Users/Admin/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217660)
```

**Comment by abceleung** [comment]
I have the exact same issue
```
[2022-06-14 14:13:37.956] [renderer1] [error] ["Extract: ENOENT: no such file or directory, open 'c:\\Users\\User\\.vscode\\extensions\\.5c52bff3-5e6d-4fa9-ae10-9a92d6dd6fa7\\language-server\\META-INF\\third-party-open-source-licenses\\bsd 3-clause \"new\" or \"revised\" license (bsd-3-clause) - apl-v10.html'","    at F.extractAtLocation (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:213215)","    at async F.extractUserExtension (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:210606)","    at async $.extract (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217251)","    at async $.doRun (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218192)"]
[2022-06-14 14:13:38.017] [renderer1] [error] ENOENT: no such file or directory, open 'c:\Users\User\.vscode\extensions\.5c52bff3-5e6d-4fa9-ae10-9a92d6dd6fa7\language-server\META-INF\third-party-open-source-licenses\bsd 3-clause "new" or "revised" license (bsd-3-clause) - apl-v10.html': Extract: ENOENT: no such file or directory, open 'c:\Users\User\.vscode\extensions\.5c52bff3-5e6d-4fa9-ae10-9a92d6dd6fa7\language-server\META-INF\third-party-open-source-licenses\bsd 3-clause "new" or "revised" license (bsd-3-clause) - apl-v10.html'
    at F.extractAtLocation (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:213215)
    at async F.extractUserExtension (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:210606)
    at async $.extract (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217251)
    at async $.doRun (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:218192)
```

**Comment by craph** [comment]
I have the same type of issue : 
```
[2022-06-14 08:17:06.214] [renderer1] [error] EPERM: operation not permitted, rename 'c:\Users\User\AppData\Roaming\Code\CachedExtensionVSIXs\.f8d1d4fb-ee14-47ad-9f61-517489664c4a' -> 'c:\Users\User\AppData\Roaming\Code\CachedExtensionVSIXs\pivotal.vscode-spring-boot-1.34.0': Download: EPERM: operation not permitted, rename 'c:\Users\User\AppData\Roaming\Code\CachedExtensionVSIXs\.f8d1d4fb-ee14-47ad-9f61-517489664c4a' -> 'c:\Users\User\AppData\Roaming\Code\CachedExtensionVSIXs\pivotal.vscode-spring-boot-1.34.0'
    at $.downloadInstallableExtension (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:219042)
    at async $.doRun (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:76:217660)
```

**Comment by yuchengao0721** [comment]
I have same issue.It's been bothering me all day

**Comment by martinlippert** [comment]
It looks like this is an issue specific to running on Windows (guessing here). Can you confirm?

As a workaround, please try to go to the Extension tab, select the `Spring Boot Tools` extension, click on the gear icon, and select `Install Another Version`, and choose `1.33.0`. Does that work?

**Comment by craph** [comment]
> It looks like this is an issue specific to running on Windows (guessing here). Can you confirm?

Yes I'm in a Windows machine

**Comment by Faputa** [comment]
> It looks like this is an issue specific to running on Windows (guessing here). Can you confirm?
> 
> As a workaround, please try to go to the Extension tab, select the `Spring Boot Tools` extension, click on the gear icon, and select `Install Another Version`, and choose `1.33.0`. Does that work?

My current version is 1.33.0, I can install version 1.32.0.

**Comment by nagromc** [comment]
> It looks like this is an issue specific to running on Windows (guessing here). Can you confirm?
> 
> As a workaround, please try to go to the Extension tab, select the `Spring Boot Tools` extension, click on the gear icon, and select `Install Another Version`, and choose `1.33.0`. Does that work?

VS Code v1.68 doesn’t seem to have the _Install Another Version_ option any longer. And I cannot find the direct link to sideload the plugin.

**Comment by Faputa** [comment]
> > It looks like this is an issue specific to running on Windows (guessing here). Can you confirm?
> > As a workaround, please try to go to the Extension tab, select the `Spring Boot Tools` extension, click on the gear icon, and select `Install Another Version`, and choose `1.33.0`. Does that work?
> 
> My current version is 1.33.0, I can install version 1.32.0.

I tried again, I can upgrade from version 1.32.0 to 1.33.0, but not to version 1.34.0.

**Comment by nagromc** [comment]
> > It looks like this is an issue specific to running on Windows (guessing here). Can you confirm?
> > As a workaround, please try to go to the Extension tab, select the `Spring Boot Tools` extension, click on the gear icon, and select `Install Another Version`, and choose `1.33.0`. Does that work?
> 
> VS Code v1.68 doesn’t seem to have the _Install Another Version_ option any longer. And I cannot find the direct link to sideload the plugin.

NVM I just found `Spring Boot Tools` v1.33.0 at https://github.com/spring-projects/sts4/releases/tag/4.14.0.RELEASE

**Comment by thkerkmann** [comment]
Seems to be a file missing in the package?
ENOENT: no such file or directory, open 'c:\Users\TKE\.vscode\extensions\.f62567e7-14dc-48e7-963f-e1f0b99ac812\language-server\META-INF\third-party-open-source-licenses\bsd 3-clause "new" or "revised" license (bsd-3-clause) - apl-v10.html'

**Comment by martinlippert** [comment]
I am running a CI build that excludes those files from the package. Once I have a snapshot build around, I will post the download link here for you to try.

**Comment by martinlippert** [comment]
OK, here is an updated VSIX file: https://s3-us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.34.0-202206141051.vsix

Could someone give this a try by manually installing that via the Extension tab, then `Install from VSIX...` and report back here?

**Comment by Faputa** [comment]
> OK, here is an updated VSIX file: https://s3-us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.34.0-202206141051.vsix
> 
> Could someone give this a try by manually installing that via the Extension tab, then `Install from VSIX...` and report back here?

It work.

**Comment by martinlippert** [comment]
> > OK, here is an updated VSIX file: https://s3-us-west-1.amazonaws.com/s3-test.spring.io/sts4/vscode-extensions/snapshots/vscode-spring-boot-1.34.0-202206141051.vsix
> > Could someone give this a try by manually installing that via the Extension tab, then `Install from VSIX...` and report back here?
> 
> I tried it and it works.

That is great news. Thanks for the quick feedback. We will push out a new release then as soon as possible here.

**Comment by martinlippert** [comment]
The new version `1.35.0` that fixes this issue is available from the VSCode Marketplace now. Thanks for reporting this and for trying the workarounds.
