### ISSUE TITLE
STS debug hangs on hover

### ISSUE THREAD

**Issue by graha1989** [spring-projects/sts4#791]
Hi,

I am using:
Spring Tool Suite 4 
Version: 4.14.1.RELEASE
Build Id: 202204250734
on Ubuntu 20.04

And after the last update, I started getting the issue when hovering the method parameter variable in debug mode. Checking the .log file and found this:
`!ENTRY org.eclipse.jdt.debug.ui 4 150 2022-06-15 10:38:26.845
!MESSAGE Internal Error
!STACK 1
org.eclipse.debug.core.DebugException: Invalid stack frame
	at org.eclipse.jdt.internal.debug.core.model.JDIStackFrame.getUnderlyingStackFrame(JDIStackFrame.java:1371)
	at org.eclipse.jdt.internal.debug.core.model.JDIStackFrame.getUnderlyingThisObject(JDIStackFrame.java:1006)
	at org.eclipse.jdt.internal.debug.core.model.JDIStackFrame.updateVariables(JDIStackFrame.java:730)
	at org.eclipse.jdt.internal.debug.core.model.JDIStackFrame.getVariables0(JDIStackFrame.java:395)
	at org.eclipse.jdt.internal.debug.core.model.JDIStackFrame.getVariables(JDIStackFrame.java:307)
	at org.eclipse.jdt.internal.debug.ui.JavaDebugHover.containsVariable(JavaDebugHover.java:620)
	at org.eclipse.jdt.internal.debug.ui.JavaDebugHover.lambda$2(JavaDebugHover.java:639)
	at org.eclipse.jdt.internal.debug.ui.JavaDebugHover.findFirstFrameForVariable(JavaDebugHover.java:604)
	at org.eclipse.jdt.internal.debug.ui.JavaDebugHover.getHoverInfo2(JavaDebugHover.java:469)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:163)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
!SUBENTRY 1 org.eclipse.jdt.debug 4 100 2022-06-15 10:38:26.845
!MESSAGE Invalid stack frame`

After this Resume, Step into, Step over and Step return buttons are disabled and the code remains in the breakpoint.

What could cause this issue and is there a way I can solve it?

Thank you in advance,
Alex

**Comment by martinlippert** [comment]
This looks like an issue with the debug support in Eclipse itself and doesn't seem to be related to the Spring Tools. In case you can reproduce this error, I would suggest to try to reproduce this with the latest STS 4.15.1 and with the latest Eclipse 2022-06 release. If you can reproduce it reliably in Eclipse 2022-06, I would suggest to file an issue with the Eclipse project itself here: https://github.com/eclipse-jdt/eclipse.jdt.debug
