### ISSUE TITLE
Exception when launching from VSCode

### ISSUE THREAD

**Issue by minteo-as** [spring-projects/sts4#812]
When I launch debug from within VSCode I get the following exception:
```
[Error - 8:15:25 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.springframework.ide.vscode.commons.languageserver.util.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:126)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessStatus
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessCommandHandler.connect(SpringProcessCommandHandler.java:103)
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessCommandHandler.lambda$new$1(SpringProcessCommandHandler.java:63)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleLanguageServer.executeCommand(SimpleLanguageServer.java:264)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleWorkspaceService.executeCommand(SimpleWorkspaceService.java:135)
	... 17 more
Caused by: java.lang.ClassNotFoundException: org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessStatus
	... 21 more
```

I believe that this is happening after the extension updated to `2022-08-03 (4.15.2 RELEASE, incl. language servers version 1.37.0)`.

**Comment by martinlippert** [comment]
Thanks @minteo-as for reporting this. Can you take a look at the installation folder on your drive to see if the corresponding .class file exists? It should be located at this path:

`~/.vscode/extensions/pivotal.vscode-spring-boot-1.37.0/language-server/BOOT-INF/classes/org/springframework/ide/vscode/boot/java/livehover/v2` and then a file called `SpringProcessStatus.class`. Does that file exist?

**Comment by martinlippert** [comment]
@per-steinar would be great if you could take a look at this, too.

And do you have any steps how to reproduce this? And is this on Windows, Mac, or Linux?

**Comment by minteo-as** [comment]
I'm on MacOS 12.5.
The .class file exists, but the location is a bit different due to me having stated vscode with the following flag `--extensions-dir ~/.vscode_Services/exts`. My location of the .class file is `~/.vscode_Services/exts/pivotal.vscode-spring-boot-1.37.0/language-server/BOOT-INF/classes/org/springframework/ide/vscode/boot/java/livehover/v2`. Could this be the issue?

**Comment by minteo-as** [comment]
I don't have any reliable steps to reproduce, so it is hard to tell if downgrading helps! I have tried downgrading to `1.36.0` and I did not get any problems. Now I have upgraded to newest version again, and I have not experienced the problem since upgrading.

**Comment by martinlippert** [comment]
Hm, I am still puzzled why this happened, but if you can't reproduce this anymore, we should probably close the issue here. If you come across this again, please comment and we can re-open this anytime.
