### ISSUE TITLE
[spring-boot-3] live information hovers are broken when running Spring Boot 3 application

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#862]
Running petclinic from the springboot3 branch causes the live hovers to not work anymore.
The language server complains about things like:

```
09:08:01.185 [pool-6-thread-9] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - problem occured during process live data refresh
java.lang.Exception: no live data received, lets try again
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessConnectorOverJMX.refresh(SpringProcessConnectorOverJMX.java:148)
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessConnectorService.lambda$scheduleRefresh$4(SpringProcessConnectorService.java:258)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by martinlippert** [comment]
The underlying reason for this is that actuators are no longer configured to expose everything via JMX by default. You need to enable this for a project manually.

We should add this property automatically when launching a Spring Boot project and JMX/live hovers are enabled.
