### ISSUE TITLE
exception thrown in VSCode when using latest snapshots

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#891]
I am using VSCode with the latest pre-releases from:
- Language Support for Java
- Spring Boot Dashboard
- Spring Boot Tools (from the latest VSIX file)

I have a project open in my workspace, created from initializr (web + actuator), on Spring Boot 2.6.12.

After a little while, I see an error popup showing up, complaining about a problem when asking for `textDocument/codeAction`, and showing this exception in the log output:

```
java.util.concurrent.CompletionException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $
	at com.google.gson.Gson.fromJson(Gson.java:1070)
	at com.google.gson.Gson.fromJson(Gson.java:1129)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleTextDocumentService.lambda$computeCodeActions$10(SimpleTextDocumentService.java:445)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleTextDocumentService.computeCodeActions(SimpleTextDocumentService.java:442)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleTextDocumentService.lambda$codeAction$11(SimpleTextDocumentService.java:499)
	... 5 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
	at com.google.gson.internal.bind.JsonTreeReader.beginArray(JsonTreeReader.java:72)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:1058)
	... 10 more
```

**Comment by BoykoAlex** [comment]
This should fix it: https://github.com/spring-projects/sts4/commit/09c62da4147dd5d713525cccd3509c1954935dc8#diff-62f1453b6f943f2d06f4c1ff56d743db59a65f3857dafbf42c8299751be427ceR56
