### ISSUE TITLE
OpenRewrite unchecked, but always Language Server Background Job(Loading Rewrite Recipes)

### ISSUE THREAD

**Issue by w6et** [spring-projects/sts4#925]
**Describe the bug**

Version: 4.17.0.RELEASE
when i click  "package Explorer" from "java Source Window"
![image](https://user-images.githubusercontent.com/2731425/207499116-585c0db5-8b25-4be4-a931-89743dad9322.png)

**Comment by martinlippert** [comment]
Thanks @w6et for reporting this, the language server is probably loading the OpenRewrite recipes nevertheless the preference is disabled - and therefore doesn't need to do that. We should change that.

But the activity should really happen just once and not multiple times. Do you see this progress view entry multiple times? And do they run for a very long time (or even all the time)? Or do they disappear from the progress view again?

**Comment by gbaso** [comment]
Same here, Eclipse is unusable due to this. Constantly freezes due to dozens of (hanging) background jobs and has to be force-killed.

**Comment by BoykoAlex** [comment]
@w6et @gbaso I'd like to check if there are more than one language server started in these case or is it just the progress that is never terminated.
II wonder if you could try the following:
1. Shut down STS and vodecode and make sure that `jps` command executed from the terminal does not have `BootLanguageServerBootApp` in the list of java processes.
2. Start STS, work with your java code. Once you notice multiple **Loading Rewrite Recipes** jobs in the progress dialog run `jps` command again and take a note of how many `BootLanguageServerBootApp` are there. Wait 30 sec and run `jps` again, check if number of `BootLanguageServerBootApp` has changed.

Also, I'm curious whether you are seeing multiple **Loading Rewrite Recipes** jobs at startup of STS or eventually after working in STS for some time.

**Comment by martinlippert** [comment]
@w6et @gbaso Can you also enable the preference to push the logs from the Spring Boot language server via: `Preferences -> Language Servers -> Spring Language Servers`, then activate the `Spring Boot` entry, then retry the IDE. From there on, the log from the language server process appears in your Console view. Maybe you can paste the content of that log output while those problems appear that you describe?

In addition to that it would also be interesting to see if the problem completely goes away if you disable the Spring Boot language server altogether from the `Preferences -> Language Servers` list for all the file associations.

**Comment by BoykoAlex** [comment]
In order not to be bugged down by rogue **Loading Rewrite Recipes** jobs feel free to disable: **Start Language Server at startuo when Spring Boot is a dependency** preference setting.
![Screenshot 2022-12-14 at 11 29 51](https://user-images.githubusercontent.com/6433390/207652785-f4a017d1-72fd-4484-bd2a-f62958b11849.png)

The effect of disabling it is that the Language Server would start only when java source file, boot properties/yaml being edited which equivalent to the behaviour from previous releases. 

FYI: The preference setting on means that language server is started when spring-boot is on the classpath of any of the projects in the workspace and shut down when there is no spring-boot on the classpath of any of projects in the workspace. Somehow i suspect that quick language server shutdowns and start up which may result from springg-boot added and removed from the classpath in quick successions may result in the issue you describe here...

**Comment by gbaso** [comment]
@BoykoAlex disabling Start Language Server at startup solved the problem for now.

I'll try to dig in the logs and in jps later today.

**Comment by gbaso** [comment]
@martinlippert Enabling the logs immediately found an issue: startup takes almost 5 minutes, resulting in 1389 occurrences of "Validating Spring Boot version on project" between 29 maven modules. Fair to say this is not expected behaviour.

I'm currently on spring boot 2.6.5.

[spring_boot_language_server.log](https://github.com/spring-projects/sts4/files/10231378/spring_boot_language_server.log)

**Comment by BoykoAlex** [comment]
You can disable **Reconciling of Java Sources** under OpenRewrite preferences. It should have the same effect. See the screenshot from the description at the top 2nd checkbox.

We are working on minimizing project reconcile requests. The issue with very frequent project reconcile requests is different from the issue reported here though with unterminated jobs. 

We have pushed some initial work for reducing project reconciles it should be available tomorrow via nightly build update site (https://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.26). Feel free to give it a try if you find some free time. (Thanks in advance for trying it out!)

**Comment by BoykoAlex** [comment]
We are working on reducing the number of project reconcile requests as they are too frequent. Some initial work for this but it might help already should be available tomorrow via the nightly build update site: https://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.26

Note that unterminated jobs in the progress view originally reported in this issue is the result of Boot LS started and shutdown in quick successions on startup. It is a different issue.

**Comment by gbaso** [comment]
Thanks @BoykoAlex. I also had the problem of multiple LS Loading rewrite recipes. According to `jps` there is only one `BootLanguageServerBootApp`, despite multiple loading bars being shown in Eclipse.

> I'm curious whether you are seeing multiple Loading Rewrite Recipes jobs at startup of STS or eventually after working in STS for some time.

They start appearing shortly after startup, but they don't seem to be triggered by the startup itself.

> Do you recall performing changes to maven pom or gradle build files right before seeing those rogue jobs?

I'm doing maven module refactoring, which includes modifying poms, opening/closing projects and issuing maven updates.

**Comment by w6et** [comment]
> According to `jps` there is only one `BootLanguageServerBootApp`, despite multiple loading bars being shown in Eclipse.

me too！only one “BootLanguageServerBootApp”（pid changed，old terminated，new created） when i‘m seeing multiple Loading Rewrite Recipes jobs 

----------

> I'm curious whether you are seeing multiple Loading Rewrite Recipes jobs at startup of STS or eventually after working in STS for some time.

after working in STS for some time.I started muitiple sts.
D:\ide\sts4\SpringToolSuite4.exe --clean -data D:\works\sts41
D:\ide\sts4\SpringToolSuite4.exe --clean -data D:\works\sts42

I'm doing JavaFileName of 'Package Explorer view' to click


----------


> Do you recall performing changes to maven pom or gradle build files right before seeing those rogue jobs?

I'm not sure , The issue isn't reproduced yet.:sweat_smile:
(after enabled log、disabling start at startup if boot is a dependency、off some validation enablement, then I restarted and reverted above operations) I'm not sure what effected.
when problemed，the log seems endless(lot of Validating ).
now the log is no more refresh 

----------

**Comment by amcmike3** [comment]
Unsure if I had this specific issue but I had an excessive amount of loading bars from language server background jobs showing in my progress tab and unchecking "Preferences > Language Servers > Spring Langauge Servers > Spring Boot Langauge Server > start language server at start up" like mentioned above solved my issue.

**Comment by martinlippert** [comment]
Here is a summary of things that you can do to workaround the performance issues in the 4.17.0 release:
https://github.com/spring-projects/sts4/issues/922#issuecomment-1358023724

**Comment by CyberRookie** [comment]
> Unsure if I had this specific issue but I had an excessive amount of loading bars from language server background jobs showing in my progress tab and unchecking "Preferences > Language Servers > Spring Langauge Servers > Spring Boot Langauge Server > start language server at start up" like mentioned above solved my issue.

That solved my problem too after updating my STS to the latest Spring Boot Version and Java to SE-17 I was having that issue. Now the Eureka Server registers all my microservices.

**Comment by Sanjeevan-S** [comment]
> Unsure if I had this specific issue but I had an excessive amount of loading bars from language server background jobs showing in my progress tab and unchecking "Preferences > Language Servers > Spring Langauge Servers > Spring Boot Langauge Server > start language server at start up" like mentioned above solved my issue.

yep that fixed the problem!

**Comment by martinlippert** [comment]
We will ship a fix for this issue with the upcoming 4.17.1 release.

**Comment by AbstractAlao** [comment]
> Same here, Eclipse is unusable due to this. Constantly freezes due to dozens of (hanging) background jobs and has to be force-killed.

I thought I was the only one that was running into this problem.  MY CPU is maxing out at 99% and it using using 4 GB of memory while being idle

**Comment by martinlippert** [comment]
We just released the fix for these problems as part of the STS 4.17.1.RELEASE.

**Comment by renanaribeiro** [comment]
> We just released the fix for these problems as part of the STS 4.17.1.RELEASE.

Thank you, after going to **Help -> Check for Updates** and upgrading to 4.17.1 solved this and can finally navigate through Java files =)

**Comment by CyberRookie** [comment]
I believe You have to go into Window>Preferences> and disable Language Server at start up.
Pretty sure that's what I did because that box is unchecked.
I'm using the 4.17.1 release of STS but it should be the same.

Hope that helps!
________________________________

**Comment by BoykoAlex** [comment]
Uncheck the checkbox circled in red as shown in the screenshot below to overcome. the issue
![Screenshot 2023-03-22 at 13 15 31](https://user-images.githubusercontent.com/6433390/226985352-da69b723-4172-4ab0-a220-793fd01b6bc5.png)

Do you mind attaching language server logs by the way? The LS process once started should be up until IDE is shut down. Therefore, I'm puzzled why the process would be terminating in your case... If it is not terminating then the questions remains why it'd attempt to load Rewrite recipes multiple times...

**Comment by youcangetme** [comment]
Why is this still a problem? Can't the Spring folks just disable it until they can figure out what the problem is? I have disabled all of the language servers and its still sits an spins.

**Comment by rgambelli** [comment]
Grazie del supporto, confermo che se disabilito il "start LS at startup", al successivo riavvio non c'è alcun processo BootLanguageServerBootApp.

Ho provato a riabilitarlo per riproddure l'anomalia e generare il thread dump ma in questo momento non si sta più verificando, terrò quindi quel flag attivo e se dovesse ripresentarsi il problema allegherò il thread dump

**Comment by martinlippert** [comment]
@rgambelli Glad to hear that it works again for you

**Comment by youcangetme** [comment]
With all due respect, disabling these features doesn't "fix" them...

**Comment by BoykoAlex** [comment]
@youcangetme we think it's working. Note that the comment above states that issue cannot be reproduced anymore with the setting on. There was an issue with Boot LS starting/stopping quickly over a period of time. This problem was fixed months ago by starting boot LS if Boot is discovered on the classpath in the workspace. Then Boot LS stays around until the IDE is shut down. Therefore, making the issue above impossible. Consequently, if one sees "Loading Recipes..." jobs in the progress view it would be caused by something else and we are curious to see the logs to understand what caused this problem this time as it might be that the same problem can be caused by a number of things.

Do you experience problems with the "Start Language Server at start up if Spring Boot is a dependency" setting on yourself? Is it in version 4.18.0? Attach Boot LS log then - please help us to get to the bottom of it.

**Comment by youcangetme** [comment]
I made the rounds today to force my developers to update to 4.18 and there are only 3 developers on my team still using Spring tools. So it looks like they solved this issue by all themselves months ago.

Every time I reinstall it works for a few days before returning to the failure state so we will see.

**Comment by youcangetme** [comment]
![image](https://user-images.githubusercontent.com/14304995/230215661-42801321-0935-45b6-8418-bf7ae4ffb557.png)
![image](https://user-images.githubusercontent.com/14304995/230215856-f537ae3d-881f-492c-9aa7-f494677f68c6.png)

So v4.18 also does the infinite Spring Language Server thing. Same as the past 8 to 10 month. I couldn't grab the actual log from the console because it is spawning so many consoles but I got a screen grab.

**Comment by BoykoAlex** [comment]
@youcangetme looks like it still start up and shutting down Boot LS processes for some reason... I'm going to add more log statements in the code: Boot LS side and the Eclipse side. This extra logging should hopefully help us see why Boot LS is being shut down and then started again... Once this is done and the build is passing I'll post the p2 snapshot update site for you to upgrade your boot eclipse tools and then once you encounter this issue again logs would tell us more. I don't exactly remember the location for the log file for Boot LS... think it'd write log to a file if you don't put it out in the console. I'll recall where that file is and post instructions.
Meanwhile, can you please attach your Eclipse log please?

**Comment by BoykoAlex** [comment]
@youcangetme I have pushed changes to log some extra stuff. I have also enabled streaming Boot LS log to a file under your workspace folder `/.metadata/.plugins/org.springframework.tooling.boot.ls/boot-ls.log` also for JVM crash there will be a file created `fatal-error-boot-ls.log` under the same folder. The log is streamed to the file above only if logging to console view is disabled, hence please disable it.
Please use p2 update site https://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.27 for Eclipse 4.27 or see https://dist.springsource.com/snapshot/STS4/nightly-distributions.html to download a distribution build or use a different eclipse version update site.
Please try to reproduce the issue with the updated STS or a new snapshot distro. Once reproduce please attach eclipse log from `<workspace folder>/.metadata/.log` and boot ls log from `<workspace folder>/.metadata/.plugins/org.springframework.tooling.boot.ls/boot-ls.log`
The question is why Boot LS being shut down... i have a feeling it is crashing for some reason and being started again...

**Comment by youcangetme** [comment]
I tried to update to this p2 build but I am not sure it took. I do not see the directory being created or the files being written... yet. I added the URL to the update and install sites under the preferences and got an update. I did not see and update before I added the update link so I think I am good. I did disable the log to console like you requested.

Interesting point is I cannot repeat the earlier issue. It seems to be the first start of the day from a cold computer when it happens.

I just tried to restart multiple times to see if that would kick it off but no luck. These bugs are just the worst. I am sure its as frustrating for you all as it for use little users.

I will give it a shot in the morning and see if it will give me a log you can use.

**Comment by BoykoAlex** [comment]
Sorry, the builds aren't getting through I just noticed this :-\ Will let you know when it is ready to try... Thought it would just run without issues over night...

**Comment by BoykoAlex** [comment]
@youcangetme looks like the builds are through so please try again either the snapshot update site (https://dist.springsource.com/snapshot/TOOLS/sts4/nightly/e4.27) or the distro from https://dist.springsource.com/snapshot/STS4/nightly-distributions.html

**Comment by youcangetme** [comment]
Sorry, terribly busy. To answer the question about how we resolve it, when it happens we shut down eclipse and wait a minute and start it back up again. It seems like a cold start type bug. If its going to happen it will do it first thing in the morning. A restart seems to fix it now which is welcome. Before, in 4.17 it was all the time and some days worse unless you just shut down the language server entirely.

Let me try and get this update and see if I can capture a log tomorrow.

**Comment by youcangetme** [comment]
Ok, here is the lang server going crazy! Finally! I was away from work today and this was the first time starting tool suite.

Hopefully this can shed some light on this problem. 

[boot-ls.log](https://github.com/spring-projects/sts4/files/11217313/boot-ls.log)

**Comment by youcangetme** [comment]
When I restarted Eclipse it seem to come up fine. Then I was adding values to a properties file and started clicking the suggested add value to the meta data and then I got the following popups. Not sure if its related.
![image](https://user-images.githubusercontent.com/14304995/231622622-52e6fe2c-ffba-449e-a51a-c74dfde5bf99.png)

**Comment by BoykoAlex** [comment]
@youcangetme is there an eclipse/STS log available for the same period of time? Should under `<workspace folder>/.metadata/.log`.
I can see in the log that a large number of LS processes was started... Are all of those processes running or just one. What do you see if `jps` command is executed in the terminal.
Overall, seems like eclipse log would be most useful at this point. I have made a chunk of code `synchronized` and hope that this might be it. Therefore, please update from the snapshot again tomorrow if you don't mind and please give it another try.

As for the error you've observed above via applying a quick fix in a properties file, I doubt it is related but I'd take a look at this error separately. I wasn't abe to reproduce it on mac so far. I'll try tomorrow on win 10... The quick fix is supposed to create a file `<project root>/src/main/resources/META-INF/additional-spring-configuration-metadata.json` with metadata for the property. Looks like the "edit" received from the Boot LS was invalid hence the exception... Again, it'd be good to know what was in the boot ls log at the moment of the error. The stack trace of the exception in Eclipse would be good too. Is it reproducible all the time?

**Comment by youcangetme** [comment]
I have been busy and I can't tell which were from that period so I am sending everything.

[metadata.zip](https://github.com/spring-projects/sts4/files/11217872/metadata.zip)

**Comment by youcangetme** [comment]
What I saw was the processes would spin up and die repeatedly. To the point Eclipse would freeze and I couldn't click on any buttons. Eventually I either kill it through the OS or the X button would finally respond. After that it will restart no issues.

**Comment by BoykoAlex** [comment]
@youcangetme RE: `IllegalArgumentException` - I'd say that under normal circumstances this error shouldn't had happened. The log indicates that current active workbench window or page was `null` which under normal circumstances shouldn't occur. In addition this exception originates from LSP4E project and the code in question seems to be in some kind of WIP.
Still trying to understand why Boot LS is being shut down... Feels like initial LS initialization sequence errors out somewhere and hence LS is started again and again...

**Comment by BoykoAlex** [comment]
@youcangetme There are 2 fixes that went into LSP4E. One that could help with infinite start/stop loop: https://github.com/eclipse/lsp4e/pull/611 and the other that fixes `IllegalArgumentException` https://github.com/eclipse/lsp4e/pull/584. I'll let you know when the snapshot build from our side is ready for another try (hope you don't mind to give it another go :-))

**Comment by youcangetme** [comment]
Sorry, been busy. Will do the update ASAP. Thanks.

**Comment by youcangetme** [comment]
I think the updates were finally recognized by my install. I had a bunch of stuff get installed.

**Comment by BoykoAlex** [comment]
@youcangetme were you able to run into the same issue with LS starting/stopping over and over again?

If yes, again, logs for Eclipse and Boot LS would be very useful. If no (I sincerely hope it is a "no" :-)) then we should be in a good shape for 4.18.1 release.

**Comment by youcangetme** [comment]
Hmmmmm.... I haven't seen the issue yet. Their could be a light at the end of the tunnel.

**Comment by martinlippert** [comment]
That sounds promising. Let me close this issue then for the upcoming 4.18.1 release. We can re-open or create a new one for further improvements in this space if you come across this again. Many many thanks for your help digging into this issue, very much appreciated.

**Comment by youcangetme** [comment]
I haven't seen it on any updated systems. I do see it consistently on ones that are not.

**Comment by youcangetme** [comment]
OK, here are the logs. The language servers went crazy again :( 

We jinxed it by closing this ticket...

[metadata.zip](https://github.com/spring-projects/sts4/files/11377412/metadata.zip)

**Comment by BoykoAlex** [comment]
@youcangetme are there files such as `.metadata\.bak_1.log` bak_1.log etc. Could you please attach those as well?
Seems like the issue with starting/stopping is triggered by 2 Boot LS running at the same time... if that occurs then the infinite start/stop loop kicks off...

**Comment by youcangetme** [comment]
[more_metadata.zip](https://github.com/spring-projects/sts4/files/11378959/more_metadata.zip)

Yep, I do distinctly recall starting a new instance by accident. It is rare for me to do that which is why I remember it.

**Comment by youcangetme** [comment]
Ok, I cleared the logs and installed the feature. I will drop a log zip when I get the problem again.

**Comment by youcangetme** [comment]
[even_more_metadata.zip](https://github.com/spring-projects/sts4/files/11392903/even_more_metadata.zip)

I did not double start my instance this time.

**Comment by youcangetme** [comment]
I deleted the logs and installed the new patch. i will post the logs when it blows up again.

**Comment by BoykoAlex** [comment]
@youcangetme missed one place in the code with a possible fix. Here is the updated zip:
[repository-0.13.1-SNAPSHOT.zip](https://github.com/spring-projects/sts4/files/11402365/repository-0.13.1-SNAPSHOT.zip)

Sorry about the late notice :-\

**Comment by youcangetme** [comment]
[mega-metadata.zip](https://github.com/spring-projects/sts4/files/11417271/mega-metadata.zip)

Well, this is with the new snapshot so hopefully you have usable logs.

**Comment by BoykoAlex** [comment]
Looks to me like the issue has two parts to it.

Part One.
The Boot LS process sometimes doesn't start normally. There is no logging info for this as logging didn't seem to start in this case at all.
For example Eclipse side logging is:
```
ENTRY org.eclipse.lsp4e 1 0 2023-05-07 22:39:47.517
!MESSAGE getLSWrappers(document)

!ENTRY org.eclipse.lsp4e 1 0 2023-05-07 22:39:47.517
!MESSAGE About to start LS via Wrapper `org.eclipse.languageserver.languages.springboot'. Currently started wrappers (total=0):

!ENTRY org.eclipse.lsp4e 1 0 2023-05-07 22:39:47.531
!MESSAGE Creating Wrapper for `org.eclipse.languageserver.languages.springboot' with initialPath=null project=resource

!ENTRY org.eclipse.lsp4e 1 0 2023-05-07 22:39:47.532
!MESSAGE Starting LS 'org.eclipse.languageserver.languages.springboot'

!ENTRY org.springframework.tooling.boot.ls 1 0 2023-05-07 22:39:47.700
!MESSAGE DelegatingStreamConnectionProvider - Starting Boot LS

!ENTRY org.springframework.tooling.ls.eclipse.commons 1 0 2023-05-07 22:39:47.714
!MESSAGE Started org.springframework.tooling.boot.ls LS process 2464

!ENTRY org.eclipse.lsp4e 1 0 2023-05-07 22:39:47.715
!MESSAGE LS `org.eclipse.languageserver.languages.springboot' process is started: 6188

!ENTRY org.eclipse.lsp4e 1 0 2023-05-07 22:39:47.931
!MESSAGE Initializing server-client comm for LS `org.eclipse.languageserver.languages.springboot' with pid=6188

!ENTRY org.eclipse.lsp4e 1 0 2023-05-07 22:39:47.949
!MESSAGE Sending initialize message to LS `org.eclipse.languageserver.languages.springboot' with pid=6188

!ENTRY org.eclipse.lsp4e 2 0 2023-05-07 22:39:48.795
!MESSAGE Could not get if the workspace folder capability is supported due to timeout after 1 second
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.eclipse.lsp4e.LanguageServerWrapper.supportsWorkspaceFolderCapability(LanguageServerWrapper.java:587)
	at org.eclipse.lsp4e.LanguageServerWrapper.canOperate(LanguageServerWrapper.java:576)
	at org.eclipse.lsp4e.LanguageServerWrapper.c
```

There is no matching log entries on the LS side (no entries at 22:39:47 and 22:39:48):
```
1:18:03.765 [pool-11-thread-1] INFO  o.s.i.v.b.j.u.CompilationUnitCache - CU Cache: invalidate AST for file:///C:/Users/youca/Documents/Eclipse_Workspace_JDK17/eStore_v2/orders/src/main/java/net/subnoize/estore/orders/model/Order.java
01:18:03.790 [pool-11-thread-1] INFO  o.s.i.v.c.l.u.SimpleTextDocumentService - Closed: file:///C:/Users/youca/Documents/Eclipse_Workspace_JDK17/eStore_v2/resource/src/main/java/net/subnoize/estore/orders/OrderController.java
01:18:03.790 [pool-11-thread-1] INFO  o.s.i.v.b.j.u.CompilationUnitCache - CU Cache: invalidate AST for file:///C:/Users/youca/Documents/Eclipse_Workspace_JDK17/eStore_v2/resource/src/main/java/net/subnoize/estore/orders/OrderController.java
22:39:52.748 [main] INFO  o.s.i.v.b.a.BootLanguageServerBootApp - Starting BootLanguageServerBootApp using Java 17.0.6 with PID 1864 (C:\Data\Java\sts-4.18.0.RELEASE\plugins\org.springframework.tooling.boot.ls_1.46.0.202304251920\servers\spring-boot-language-server\BOOT-INF\classes started by youca in C:\Data\Java\sts-4.18.0.RELEASE)
22:39:52.756 [main] INFO  o.s.i.v.b.a.BootLanguageServerBootApp - No active profile set, falling back to 1 default profile: "default"
22:39:54.200 [main] INFO  o.s.i.v.boot.app.SpringSymbolIndex - project listener registered
22:39:54.989 [main] INFO  o.s.i.v.b.a.BootLanguageServerBootApp - Started BootLanguageServerBootApp in 2.635 seconds (process running for 3.151)
22:39:54.990 [main] INFO  o.s.i.v.c.l.LanguageServerRunner - java.home = C:\Data\Java\sts-4.18.0.RELEASE\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.6.v20230204-1729\jre
22:39:54.991 [LanguageServerApp-lifecycle] INFO  o.s.i.v.c.l.LanguageServerRunner - Server ready to start after 3154 ms

```

Therefore timeouts for this: 
```
org.eclipse.lsp4e.LanguageServerWrapper.supportsWorkspaceFolderCapability(LanguageServerWrapper.java:587)
```
as nothing has been received from the language server at all, however, the process seem to have started...

Part Two
Attempt to start the second language server while the first one is either stuck or being initialized or just slow. The attempt to start the second language server comes from the fact that the check whether currently started LS can work on a document from one of the projects in the workspace returns `false`, hence the same definition language server is being started.
The check would start returning `true` if server was marked as `singleton`.
Another instance of starting the same boot LS can be initiated from the `LanguageServerWrapper#start()` method if comm pipe has been closed (failed LS process start i suppose). This re-start is valid though...

I'd try to limit Boot LS t only one process/LS wrapper properly by setting `singleton` property in the extension point: b19c16cee6a003cbff46036e6b31f0a5d4a7b468 Should be available in the next snapshot build of STS4 for Eclipse. Will post here once available.

Also logging adjusted for lsp4e: 
[repository-0.13.1-SNAPSHOT.zip](https://github.com/spring-projects/sts4/files/11424909/repository-0.13.1-SNAPSHOT.zip)

**Comment by BoykoAlex** [comment]
@youcangetme should be ok to install snapshot of sts4 for eclipse from an nightly/snapshot update site found on this page: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html
Combined with lsp4e from the comment above, please, give it another try. The change in STS4 has chances to fix the issue... but lets wait until you try it out.

**Comment by youcangetme** [comment]
Ok, logs reset and everything installed and updated.

**Comment by BoykoAlex** [comment]
@youcangetme how's it going with the new sts4 snapshot and a modified lsp4e? Have you been busy and not had time to watch this stuff or is it just working now? :-)

**Comment by CyberRookie** [comment]
I've been running 4.18.1 release for over a week now and no issues. Good job!
________________________________

**Comment by youcangetme** [comment]
Hmmmm, I have not seen the language server go nuts on any machine with the new patches installed. I am wary to pronounce it "fixed." But I am willing to say (while knocking on wood) "sure, give it prime time exposure and see."

**Comment by youcangetme** [comment]
I still haven't seen anything bad yet and I have been banging on it pretty darn hard.

**Comment by BoykoAlex** [comment]
@youcangetme could you please attach your logs (eclipse and boot ls) from these few past days? Are STS tools working though? Do you content assists in boot properties files, spring symbols showing up after Ctrl-6, etc?

I think the singleton property for the LS extension point is the real fix to the problem... Stuff that went into LSP4E is mostly for logging... Thus if at some point you switch to just the snapshot distro of STS4 it should work just as well ideally.

**Comment by youcangetme** [comment]
Sorry I missed your message. I will upload the logs in the morning.

**Comment by youcangetme** [comment]
[metadata.zip](https://github.com/spring-projects/sts4/files/11514037/metadata.zip)

This one seems awfully small. Sorry for the delay.

**Comment by BoykoAlex** [comment]
@youcangetme I have gone through the logs and it seems fixed to me - only one Boot LS at all times. Seems reasonable to mark this as fixed. The actual fix is in STS4: b19c16cee6a003cbff46036e6b31f0a5d4a7b468

**Comment by youcangetme** [comment]
@martinlippert glad to help. Everything continues to work as expected so I am changing back to the regular distro to keep in sync with my developers.
