### ISSUE TITLE
STS stuck on Updating Maven Project - Resolving Plugin Dependency 75%

### ISSUE THREAD

**Issue by bberto** [spring-projects/sts4#940]
Using STS 4.17.0 - JDK 17.0.2 - Windows 10 I often have eclipse stuck on Updating Maven Project - Resolving Plugin Dependency 75%. The GUI is freezed and I have to kill the process.

The issue is very similar to https://github.com/spring-projects/sts4/issues/703 (fixed), but the reported steps to reproduce the issue doesn't work in my case. I'm trying to figure out a way to reproduce the issue. 

I observed that is happening more frequently on a multimodule project using compiler postprocessors (lombok and mapstruct).

Using VisualVM I got the same threaddump of related issue:
```
"Worker-2: Updating Maven Project" #65 prio=5 os_prio=0 cpu=19453.12ms elapsed=87.52s tid=0x000001c59083b430 nid=0x2c34 in Object.wait()  [0x00000028accfd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.2/Native Method)
        - waiting on <no object reference available>
        at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:1074)
        - locked <0x0000000766700020> (a java.util.Collections$SynchronizedSet)
        at org.eclipse.jdt.apt.core.internal.generatedfile.GeneratedSourceFolderManager.removeFolder(GeneratedSourceFolderManager.java:508)
        at org.eclipse.jdt.apt.core.internal.generatedfile.GeneratedSourceFolderManager.folderNamePreferenceChanged(GeneratedSourceFolderManager.java:321)
        at org.eclipse.jdt.apt.core.internal.AptProject.preferenceChanged(AptProject.java:81)
        at org.eclipse.jdt.apt.core.util.AptConfig.setString(AptConfig.java:969)
        at org.eclipse.jdt.apt.core.util.AptConfig.setGenSrcDir(AptConfig.java:917)
        at org.eclipse.m2e.apt.internal.AbstractAptConfiguratorDelegate.configureProject(AbstractAptConfiguratorDelegate.java:171)
        at org.eclipse.m2e.apt.internal.AbstractAptProjectConfigurator.lambda$0(AbstractAptProjectConfigurator.java:95)
        at org.eclipse.m2e.apt.internal.AbstractAptProjectConfigurator$$Lambda$1718/0x0000000801bedcc8.call(Unknown Source)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:364)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:213)
        at org.eclipse.m2e.apt.internal.AbstractAptProjectConfigurator.configure(AbstractAptProjectConfigurator.java:88)
        at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:123)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$6(ProjectConfigurationManager.java:494)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$$Lambda$1694/0x0000000801b8e4d8.call(Unknown Source)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:364)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:488)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$4(ProjectConfigurationManager.java:416)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$$Lambda$1693/0x0000000801b8e288.test(Unknown Source)
        at java.util.Collection.removeIf(java.base@17.0.2/Collection.java:576)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:410)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$3(ProjectConfigurationManager.java:340)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$$Lambda$1671/0x0000000801b8d028.call(Unknown Source)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:364)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:213)
        at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1102)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:339)
        at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Anyone else out there having the some issue?

**Comment by martinlippert** [comment]
Do you have the Lombok extension for Eclipse installed into your STS? If so, can you try to remove that to see if that makes a difference?

Also, there is a newer version of STS (4.17.1) out there, so you might want to update that as well. I don't think it will solve the issue, but the update would make sense independent of that anyway... :-)

**Comment by dogilvie** [comment]
Google led me here. Seeing a similar issue with "Updating Maven Project" locking up. Cancel request has no effect.

STS 4.17.1, Liberica JDK 17.0.3, Eclipse 4.26.0.20221201-1200, Lombok 1.18.24

**Comment by dogilvie** [comment]
> @dogilvie Can you reproduce this with a vanilla Eclipse or with a vanilla Eclipse + Lombok extension? Since this sounds something that is unrelated to the Spring tooling, I would like to verify that guess first and then (if correct) report this to the m2e project probably. So would be awesome if you could give this a try with a vanilla Eclipse and a vanilla Eclipse + Lombok.

Hi Martin, I did exactly this yesterday, with a fresh install of current eclipse + lombok, using the eclipse provided 17.0.5 JVM

I have not seen the problem (yet) with this configuration (no STS install).

My failing installation had been through multiple eclipse "software updates" from an earlier eclipse baseline. It is *possible* that this is involved (remnants of old m2e components?).

I will next try to add STS to the equation on the fresh install.

**Comment by martinlippert** [comment]
@dogilvie Sounds like a good plan, let's see what happens when you add the STS components to the fresh install.

**Comment by bberto** [comment]
This m2e setting: 
`Preferences > Maven > Annotation Processing > Do not automatically configure/execute annotation processing from pom.xml` 
fixed the issue in my case

**Comment by martinlippert** [comment]
@dogilvie Any news about trying a fresh Eclipse with STS components added?

**Comment by fltad** [comment]
> This m2e setting: `Preferences > Maven > Annotation Processing > Do not automatically configure/execute annotation processing from pom.xml` fixed the issue in my case

This worked for me as well.

**Comment by martinlippert** [comment]
So closing this one here for now. If the mentioned m2e setting doesn't solve the issue for someone, please comment and we can re-open.

**Comment by dogilvie** [comment]
> @dogilvie Any news about trying a fresh Eclipse with STS components added?

I have not seen the issue using a fresh 2022-12 install of eclipse, with STS installed.

So, I put this down to some degree of corruption of the eclipse install through a number of Eclipse updates.

**Comment by rgb255** [comment]
> This m2e setting: Preferences > Maven > Annotation Processing > Do not automatically configure/execute annotation processing from pom.xml fixed the issue in my case

This worked for me as well.

**Comment by eapereira** [comment]
using eclipse 2022-12 I got stuck on that "Updating Maven project 75%" message
I had to kill eclipse and do:
mvn eclipse:clean
mvn eclipse:eclipse

then I reopen eclipse and removed the project from IDE, shutdown eclipse and after open it again and imported my project as a maven project, now its working fine

**Comment by martinlippert** [comment]
@eapereira Usually the commands `mvn eclipse:clean` and `mvn eclipse:eclipse` should not be necessary when using the Maven Integration for Eclipse (m2e), since m2e takes care of configuring the Maven project in Eclipse and keeps that Eclipse-internal metadata for the project up-to-date.

If you are still seeing this with the latest Spring Tools for Eclipse 4.19.0 on Eclipse 2023-06, please raise this issue against the m2e project. As far as I can see from the comments above, the m2e APT support seems to be involved here, so probably worth to report that against m2e itself in case this still happens on the latest versions.

**Comment by osparking** [comment]
Very similar issue - mine(STS 4, loaded with a couple of Spring Boot Maven project) stucked updating on 0%. I had to change project folder name to a random one. Then, in the package explorer pane, the project node appeared "closed" and the forever running "updating ..." sign disappeared. Thanks for the discussion.
