### ISSUE TITLE
NPE when invoking content-assist in application.properties file for the first time

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#961]
Installed a vanilla STS 4.17.1.RELEASE distribution, created a RestService guide project, added an `application.properties` file, and pressed `Ctrl-Space` in the empty editor. Everything seems to work just fine, but I see this error showing up in the Error Log view:

```
java.lang.NullPointerException: Cannot invoke "String.length()" because "typeSignature" is null
	at org.eclipse.jdt.internal.compiler.parser.TypeConverter.createTypeReference(TypeConverter.java:145)
	at org.eclipse.jdt.internal.core.BinaryTypeConverter.createTypeReference(BinaryTypeConverter.java:366)
	at org.eclipse.jdt.internal.core.BinaryTypeConverter.convert(BinaryTypeConverter.java:214)
	at org.eclipse.jdt.internal.core.BinaryTypeConverter.convert(BinaryTypeConverter.java:330)
	at org.eclipse.jdt.internal.core.BinaryTypeConverter.buildTypeDeclaration(BinaryTypeConverter.java:111)
	at org.eclipse.jdt.internal.codeassist.SelectionEngine.selectType(SelectionEngine.java:1648)
	at org.eclipse.jdt.internal.core.NamedMember.resolveType(NamedMember.java:328)
	at org.eclipse.jdt.internal.core.NamedMember.resolveType(NamedMember.java:270)
	at org.springframework.tooling.jdt.ls.commons.java.JavaData.resolveFQName(JavaData.java:523)
	at org.springframework.tooling.jdt.ls.commons.java.JavaData.fillTypeDescriptorData(JavaData.java:294)
	at org.springframework.tooling.jdt.ls.commons.java.JavaData.fillTypeData(JavaData.java:302)
	at org.springframework.tooling.jdt.ls.commons.java.JavaData.createTypeData(JavaData.java:276)
	at org.springframework.tooling.jdt.ls.commons.java.JavaData.typeData(JavaData.java:69)
	at org.springframework.tooling.ls.eclipse.commons.STS4LanguageClientImpl.lambda$16(STS4LanguageClientImpl.java:493)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

Additional observation:
I get this exception only once, when invoking content-assist for the first time in an `application.properties` file after starting up the IDE. I can't reproduce the exception in the running IDE. But shutting it down and starting it up again makes the exception appear again after invoking content-assist in the properties file for the first time.

**Comment by martinlippert** [comment]
Testing this more creates more questions than answers. It seems like my previous observation is not precise. The exception happens sometimes under the described circumstances, and sometimes not. And I have no idea so far under which circumstances the exception appears.

**Comment by BoykoAlex** [comment]
Do you know which FQ name is being resolved and throws NPE? I suspect that Java type is being resolved for the purposes of building Spring Property Index... hence only occurs ones per IDE session... Something goes wrong resolving that type. Would be interesting to know whether it is the same type all the time, if the type is on the classpath, if pass the proper binding key, etc.

**Comment by martinlippert** [comment]
It happens when hitting content-assist on an empty properties file, so no idea which FQ name is causing the problem unfortunately...

**Comment by martinlippert** [comment]
I can't reproduce this anymore, so closing this for now.
